function BOUTP_outputs(varargin)
%===========$Update Time :  2025-09-11 17:42:20 $=========
disp('Loading $Id: BOUTP_outputs.m  2025-09-11 17:42:20    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2025-09-11 17:42:20 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BOUTP_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VOUTP_iDCurrAct_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_iQCurrAct_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_ADCKL30_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_ADCKL15_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_uDC_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_RotSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_OilTemp_degC'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_BusCurr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_PwrEleAct_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_bMotEnaReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_nEOPSpdReq_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_volfCooltFlowTar_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_MotMod_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_IVTROpMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_MCUEna_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_TMReady_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_BoostOPSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_tqTMTqMax_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VOUTP_tqTMTqMin_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
