/* Os_rtewrappers.c
 *
 * This file contains the OS function wrappers used from the RTE.
 *
 * CHECK: TABS 4 (see editor commands at end of file)
 *
 * Copyright Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
*/

#include <Os_configuration.h> /* for OS_INCLUDE_RTE */
#include <Os_api.h> /* for API functions */

#if (OS_INCLUDE_RTE == 1) /* only needed when RTE is used */

#include <Rte_Os.h> /* prototypes generated by RTE */

#include <memmap/Os_mm_code_begin.h>

/*
 * When using the OS SWC interface, the RTE can't directly use the OS API
 * calls as the OS macro definitions don't match the function prototypes
 * generated by the RTE.
 * So in case the OS is used by SWCs using its SWC interface, we provide
 * wrapper functions for the API exported to the RTE SWCs. This has the
 * additional benefit that compiler or MISRA-C checker might complain if
 * there's something wrong (implicit casts, mismatching prototypes).
 *
 * Note: The types and signatures are defined by the SWC description. Hence
 * the public signatures should use the types defined in the generated RTE
 * header. The actual calls must use OS types and call OS functionality.
*/

/* !LINKSTO Kernel.Autosar.Interfaces.SoftwareComponents, 1
 */
/*
 * GetCounterValue
*/
OS_TOOL_FUNCTION_ATTRIB_PRE
StatusType Os_RteGetCounterValue(CounterType c, TickRefType tr)
OS_TOOL_FUNCTION_ATTRIB_POST
{
	/* COVPT-1 */
	return GetCounterValue((CounterType)c, tr);
}

/*
 * GetElapsedCounterValue/GetElapsedValue
*/
OS_TOOL_FUNCTION_ATTRIB_PRE
StatusType Os_RteGetElapsedCounterValue(CounterType c, TickRefType prev, TickRefType tr)
OS_TOOL_FUNCTION_ATTRIB_POST
{
	/* COVPT-2 */
	return GetElapsedCounterValue((CounterType)c, prev, tr);
}

/* Interfaces used in AS403 package */
/*
 * TerminateApplication
*/
OS_TOOL_FUNCTION_ATTRIB_PRE
StatusType Os_RteTerminateApplication(ApplicationType a, RestartType r)
OS_TOOL_FUNCTION_ATTRIB_POST
{
	/* COVPT-3 */
	return TerminateApplication((ApplicationType)a, r);
}

/*
 * GetApplicationState
*/
OS_TOOL_FUNCTION_ATTRIB_PRE
StatusType Os_RteGetApplicationState(ApplicationType a, ApplicationStateRefType ar)
OS_TOOL_FUNCTION_ATTRIB_POST
{
	/* COVPT-4 */
	return GetApplicationState((ApplicationType)a, ar);
}

#include <memmap/Os_mm_code_end.h>

#endif /* OS_INCLUDE_RTE */

/* Editor settings; DO NOT DELETE
 * vi:set ts=4:
*/
