[!/**
 * \file
 *
 * \brief AUTOSAR ComM
 *
 * This file contains the implementation of the AUTOSAR
 * module ComM.
 *
 * \version 5.21.4
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2024 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */!][!//

[!/* *** multiple inclusion protection *** */!]
[!IF "not(var:defined('COMM_FUNCTIONS_M'))"!]
[!VAR "COMM_FUNCTIONS_M" = "'true'"!]

[!NOCODE!][!//

[!MACRO "GetMasterCoreId"!][!//
[!VAR "MasterCoreId"="''"!][!//
[!VAR "PartitionRef" = "as:modconf('ComM')[1]/ComMGeneral/ComMMasterCoreEcuCPartitionRef"!][!//
[!LOOP "as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $PartitionRef)]"!][!/*
  */!][!IF "node:exists(OsApplicationCoreRef)"!][!/*
    */!][!VAR "MasterOsApplicationCoreRefFound" = "'false'"!][!/*
    */!][!FOR "Idx" = "1" TO "count(text:split($MasterCoreId,'_'))"!][!/*
      */!][!IF "num:i(string(text:split($MasterCoreId,'_')[position() = $Idx])) = num:i(node:ref(OsApplicationCoreRef)/EcucCoreId)"!][!/*
        */!][!VAR "MasterOsApplicationCoreRefFound" = "'true'"!][!/*
      */!][!ENDIF!][!/*
    */!][!ENDFOR!][!/*
    */!][!IF "$MasterOsApplicationCoreRefFound = 'false'"!][!/*
      */!][!IF "count(text:split($MasterCoreId,'_')) = 0"!][!/*
        */!][!VAR "MasterCoreId" = "num:i(node:ref(OsApplicationCoreRef)/EcucCoreId)"!][!/*
      */!][!ELSE!][!/*
        */!][!VAR "MasterCoreId" = "concat($MasterCoreId,'_')"!][!/*
        */!][!VAR "MasterCoreId" = "concat($MasterCoreId,num:i(node:ref(OsApplicationCoreRef)/EcucCoreId))"!][!/*
      */!][!ENDIF!][!/*
    */!][!ENDIF!][!/*
  */!][!ELSE!][!/*
    */!][!IF "node:exists(OsApplicationCoreAssignment)"!][!/*
      */!][!VAR "MasterOsApplicationCoreAssignmentFound" = "'false'"!][!/*
      */!][!FOR "Idx" = "1" TO "count(text:split($MasterCoreId,'_'))"!][!/*
        */!][!IF "num:i(string(text:split($MasterCoreId,'_')[position() = $Idx])) = num:i(OsApplicationCoreAssignment)"!][!/*
          */!][!VAR "MasterOsApplicationCoreAssignmentFound" = "'true'"!][!/*
        */!][!ENDIF!][!/*
      */!][!ENDFOR!][!/*
      */!][!IF "$MasterOsApplicationCoreAssignmentFound = 'false'"!][!/*
        */!][!IF "count(text:split($MasterCoreId,'_')) = 0"!][!/*
          */!][!VAR "MasterCoreId" = "num:i(OsApplicationCoreAssignment)"!][!/*
        */!][!ELSE!][!/*
          */!][!VAR "MasterCoreId" = "concat($MasterCoreId,'_')"!][!/*
          */!][!VAR "MasterCoreId" = "concat($MasterCoreId,num:i(OsApplicationCoreAssignment))"!][!/*
        */!][!ENDIF!][!/*
      */!][!ENDIF!][!/*
    */!][!ENDIF!][!/*
  */!][!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDMACRO!][!//
[!MACRO "GetCore","SignalHandle","Direction"!][!//
[!VAR "SignalRef" = "as:modconf('ComM')[1]/ComMConfigSet/*/ComMPnc/*/ComMPncComSignal/*[string(ComMPncComSignalDirection) = $Direction][number(node:ref(ComMPncComSignalRef)/ComHandleId) = $SignalHandle]/ComMPncComSignalRef"!][!//
[!VAR "MainFunctionRef" = "as:modconf('Com')[1]/ComConfig/*/ComIPdu/*/ComIPduSignalRef/*[node:exists(.) and (string(.) = $SignalRef)]/../../ComMainFunctionRef"!][!//
[!VAR "PartitionRef" = "node:ref($MainFunctionRef)/ComPartitionRef"!][!//
[!LOOP "as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $PartitionRef)]"!][!/*
  */!][!IF "node:exists(OsApplicationCoreRef)"!][!/*
    */!][!VAR "SlaveOsApplicationCoreCoreRef" = "'false'"!][!/*
    */!][!FOR "Idx" = "1" TO "count(text:split($FoundCore,'_'))"!][!/*
      */!][!IF "num:i(string(text:split($FoundCore,'_')[position() = $Idx])) = num:i(node:ref(OsApplicationCoreRef)/EcucCoreId)"!][!/*
        */!][!VAR "SlaveOsApplicationCoreCoreRef" = "'true'"!][!/*
      */!][!ENDIF!][!/*
    */!][!ENDFOR!][!/*
    */!][!IF "$SlaveOsApplicationCoreCoreRef = 'false'"!][!/*
      */!][!IF "count(text:split($FoundCore,'_')) = 0"!][!/*
        */!][!VAR "FoundCore" = "num:i(node:ref(OsApplicationCoreRef)/EcucCoreId)"!][!/*
      */!][!ELSE!][!/*
        */!][!VAR "FoundCore" = "concat($FoundCore,'_')"!][!/*
        */!][!VAR "FoundCore" = "concat($FoundCore,num:i(node:ref(OsApplicationCoreRef)/EcucCoreId))"!][!/*
      */!][!ENDIF!][!/*
    */!][!ENDIF!][!/*
  */!][!ELSE!][!/*
    */!][!IF "node:exists(OsApplicationCoreAssignment)"!][!/*
      */!][!VAR "SlaveOsApplicationCoreAssignmentFound" = "'false'"!][!/*
      */!][!FOR "Idx" = "1" TO "count(text:split($FoundCore,'_'))"!][!/*
        */!][!IF "num:i(string(text:split($FoundCore,'_')[position() = $Idx])) = num:i(OsApplicationCoreAssignment)"!][!/*
          */!][!VAR "SlaveOsApplicationCoreAssignmentFound" = "'true'"!][!/*
        */!][!ENDIF!][!/*
      */!][!ENDFOR!][!/*
      */!][!IF "$SlaveOsApplicationCoreAssignmentFound = 'false'"!][!/*
        */!][!IF "count(text:split($FoundCore,'_')) = 0"!][!/*
          */!][!VAR "FoundCore" = "num:i(OsApplicationCoreAssignment)"!][!/*
        */!][!ELSE!][!/*
          */!][!VAR "FoundCore" = "concat($FoundCore,'_')"!][!/*
          */!][!VAR "FoundCore" = "concat($FoundCore,num:i(OsApplicationCoreAssignment))"!][!/*
        */!][!ENDIF!][!/*
      */!][!ENDIF!][!/*
    */!][!ENDIF!][!/*
  */!][!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDMACRO!][!//

[!MACRO "GetUsedCores"!][!//
[!CALL "GetMasterCoreId"!][!//
[!VAR "FoundCore"="$MasterCoreId"!][!//
[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*[ComMPncComSignalDirection='RX']/ComMPncComSignalRef)),'ComHandleId'))"!][!/*
  */!][!CALL "GetCore","SignalHandle"="ComHandleId","Direction"="'RX'"!][!//
[!ENDLOOP!][!//
[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*[ComMPncComSignalDirection='TX']/ComMPncComSignalRef)),'ComHandleId'))"!][!/*
  */!][!CALL "GetCore","SignalHandle"="ComHandleId","Direction"="'TX'"!][!//
[!ENDLOOP!][!//
[!VAR "UsedCores"="$FoundCore"!][!//
[!ENDMACRO!][!//

[!MACRO "GetPnInfoLength"!][!//
[!VAR "SigSize1" = "0"!][!//
[!VAR "SigSize2" = "0"!][!//
[!/* Get the length of the largest Com signal for array-type signals */!]
[!IF "count(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*/ComMPncComSignalRef))[text:contains(string(ComSignalType), 'UINT8_')]) != 0"!][!//
[!VAR "SigSize1" = "num:max(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*/ComMPncComSignalRef))[text:contains(string(ComSignalType), 'UINT8_')]/ComSignalLength)"!][!//
[!ENDIF!][!//
[!/* Get the length of the largest Com signal for non array-type signals */!]
[!IF "count(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*/ComMPncComSignalRef))[not(text:contains(string(ComSignalType), 'UINT8_'))]) != 0"!][!//
[!VAR "SigSize2" = "num:max(node:foreach(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*/ComMPncComSignalRef))[not(text:contains(string(ComSignalType), 'UINT8_'))]/ComSignalType, 'SigType', 'node:when($SigType = "BOOLEAN", "8", substring-after($SigType, "T"))')) div 8 "!][!//
[!ENDIF!][!//
[!IF "$SigSize1 > $SigSize2"!][!//
[!VAR "PnInfoLength" = "num:i($SigSize1)"!][!//
[!ELSE!][!//
[!VAR "PnInfoLength" = "num:i($SigSize2)"!][!//
[!ENDIF!][!//
[!ENDMACRO!][!//

[!MACRO "GetInhibitionOsApplication"!]
[!VAR "InhibitionOsApplication" = "node:name(as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (OsAppEcucPartitionRef = as:modconf('ComM')[1]/ComMGeneral/ComMInhibitionEcuCPartitionRef)])"!]
[!ENDMACRO!]

[!MACRO "GetUsedInhibitionOsApplication"!]
[!VAR "FoundInhibitionOsApplication"="''"!]
[!IF "node:exists(as:modconf('ComM')[1]/ComMGeneral/ComMInhibitionEcuCPartitionRef)"!]
  [!VAR "FoundInhibitionOsApplication" = "node:name(as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (OsAppEcucPartitionRef = as:modconf('ComM')[1]/ComMGeneral/ComMInhibitionEcuCPartitionRef)])"!]
[!ENDIF!] [!/*[!IF "node:exists(as:modconf('ComM')[1]/ComMGeneral/ComMInhibitionEcuCPartitionRef))"!]*/!]
[!ENDMACRO!]

[!MACRO "GetMasterPncOsApplication"!]
[!VAR "MasterPncOsApplication"="''"!]
[!IF "node:exists(as:modconf('ComM')[1]/ComMGeneral/ComMMasterPNCEcuCPartitionRef)"!]
  [!VAR "MasterPncOsApplication" = "node:name(as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (OsAppEcucPartitionRef = as:modconf('ComM')[1]/ComMGeneral/ComMMasterPNCEcuCPartitionRef)])"!]
[!ENDIF!]  
[!ENDMACRO!]

[!MACRO "GetUsedChannelsOsApplications"!]
[!VAR "FoundChannelsOsApplications"="''"!]
[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
  [!IF "node:exists(ComMChannelPartitionRef)"!]
    [!VAR "PartitionRef" = "ComMChannelPartitionRef"!]
    [!LOOP "as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $PartitionRef)]"!]
      [!VAR "OsApplicationAssignmentFound" = "'false'"!]
      [!FOR "Idx" = "1" TO "count(text:split($FoundChannelsOsApplications,' '))"!]
        [!IF "(string(text:split($FoundChannelsOsApplications,' ')[position() = $Idx]) = node:name(.))"!]
          [!VAR "OsApplicationAssignmentFound" = "'true'"!]
        [!ENDIF!]
      [!ENDFOR!]
      [!IF "$OsApplicationAssignmentFound = 'false'"!]
        [!IF "count(text:split($FoundChannelsOsApplications,' ')) = 0"!]
          [!VAR "FoundChannelsOsApplications" = "node:name(.)"!]
        [!ELSE!]
         [!VAR "FoundChannelsOsApplications" = "concat($FoundChannelsOsApplications,' ')"!]
         [!VAR "FoundChannelsOsApplications" = "concat($FoundChannelsOsApplications,node:name(.))"!]
        [!ENDIF!]
      [!ENDIF!]
    [!ENDLOOP!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetSignalOsApplication","SignalHandle","Direction"!]
  [!VAR "SignalOsApplication" = "''"!]
  [!VAR "SignalRef" = "as:modconf('ComM')[1]/ComMConfigSet/*/ComMPnc/*/ComMPncComSignal/*[string(ComMPncComSignalDirection) = $Direction][number(node:ref(ComMPncComSignalRef)/ComHandleId) = $SignalHandle]/ComMPncComSignalRef"!]
  [!VAR "MainFunctionRef" = "as:modconf('Com')[1]/ComConfig/*/ComIPdu/*/ComIPduSignalRef/*[node:exists(.) and (string(.) = $SignalRef)]/../../ComMainFunctionRef"!]
  [!VAR "PartitionRef" = "node:ref($MainFunctionRef)/ComPartitionRef"!]
  [!VAR "SignalOsApplication" = "node:name(as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $PartitionRef)])"!]
[!ENDMACRO!]

[!MACRO "GetUsedSignalsPlusMasterPncOsApplications"!]
[!CALL "GetMasterPncOsApplication"!]
[!VAR "FoundMasterPncPlusSignalsOsApplications"="$MasterPncOsApplication"!]
[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*[ComMPncComSignalDirection='RX']/ComMPncComSignalRef)),'ComHandleId'))"!]
  [!CALL "GetSignalOsApplication","SignalHandle"="ComHandleId","Direction"="'RX'"!]
  [!VAR "OsAssignmentFound" = "'false'"!]
  [!FOR "Idx" = "1" TO "count(text:split($FoundMasterPncPlusSignalsOsApplications,' '))"!]
    [!IF "string(text:split($FoundMasterPncPlusSignalsOsApplications,' ')[position() = $Idx]) = $SignalOsApplication"!]
      [!VAR "OsAssignmentFound" = "'true'"!]
    [!ENDIF!]
  [!ENDFOR!]
  [!IF "$OsAssignmentFound = 'false'"!]
    [!VAR "FoundMasterPncPlusSignalsOsApplications" = "concat($FoundMasterPncPlusSignalsOsApplications,' ')"!]
    [!VAR "FoundMasterPncPlusSignalsOsApplications" = "concat($FoundMasterPncPlusSignalsOsApplications,$SignalOsApplication)"!]
  [!ENDIF!]  
[!ENDLOOP!]
[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*[ComMPncComSignalDirection='TX']/ComMPncComSignalRef)),'ComHandleId'))"!]
  [!CALL "GetSignalOsApplication","SignalHandle"="ComHandleId","Direction"="'TX'"!]
  [!VAR "OsAssignmentFound" = "'false'"!]
  [!FOR "Idx" = "1" TO "count(text:split($FoundMasterPncPlusSignalsOsApplications,' '))"!]
    [!IF "string(text:split($FoundMasterPncPlusSignalsOsApplications,' ')[position() = $Idx]) = $SignalOsApplication"!]
      [!VAR "OsAssignmentFound" = "'true'"!]
    [!ENDIF!]
  [!ENDFOR!]
  [!IF "$OsAssignmentFound = 'false'"!]
    [!VAR "FoundMasterPncPlusSignalsOsApplications" = "concat($FoundMasterPncPlusSignalsOsApplications,' ')"!]
    [!VAR "FoundMasterPncPlusSignalsOsApplications" = "concat($FoundMasterPncPlusSignalsOsApplications,$SignalOsApplication)"!]
  [!ENDIF!]    
[!ENDLOOP!]

[!ENDMACRO!]

[!MACRO "GetUsedUserOsApplications"!]
[!VAR "FoundUserOsApplications"="''"!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]
  [!IF "node:exists(ComMUserEcucPartitionRef)"!]
    [!CALL "GetUserOsApplication","UserEcuCPartitionRef"="ComMUserEcucPartitionRef"!]
    [!VAR "OsApplicationAssignmentFound" = "'false'"!]
    [!FOR "Idx" = "1" TO "count(text:split($FoundUserOsApplications,' '))"!]
      [!IF "(string(text:split($FoundUserOsApplications,' ')[position() = $Idx]) = $UserOsApplication)"!]
        [!VAR "OsApplicationAssignmentFound" = "'true'"!]
      [!ENDIF!]
    [!ENDFOR!]
    [!IF "$OsApplicationAssignmentFound = 'false'"!]
      [!IF "count(text:split($FoundUserOsApplications,' ')) = 0"!]
        [!VAR "FoundUserOsApplications" = "$UserOsApplication"!]
      [!ELSE!]
        [!VAR "FoundUserOsApplications" = "concat($FoundUserOsApplications,' ')"!]
        [!VAR "FoundUserOsApplications" = "concat($FoundUserOsApplications,$UserOsApplication)"!]
      [!ENDIF!]
    [!ENDIF!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetChannelOsApplication","ChannelEcuCPartitionRef"!]
[!VAR "ChannelOsApplication" = "node:name(as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $ChannelEcuCPartitionRef)])"!]
[!ENDMACRO!]

[!MACRO "GetUserOsApplication","UserEcuCPartitionRef"!]
[!VAR "UserOsApplication" = "node:name(as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $UserEcuCPartitionRef)])"!]
[!ENDMACRO!]

[!MACRO "GetChannelOsApplicationByName","ChannelName"!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]
  [!IF "node:name(.) = $ChannelName"!]
    [!IF "node:exists(ComMChannelPartitionRef)"!]
      [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef" = "ComMChannelPartitionRef"!]
      [!BREAK!]
    [!ENDIF!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetUserOsApplicationByName","UserName"!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]
  [!IF "node:name(.) = $UserName"!]
    [!IF "node:exists(ComMUserEcucPartitionRef)"!]
      [!CALL "GetUserOsApplication","UserEcuCPartitionRef" = "ComMUserEcucPartitionRef"!]
      [!BREAK!]
    [!ENDIF!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetUsersOfChannel","ChannelName","FilterByOsApplication","OsApplication"!]
[!VAR "FoundUsersOfChannel" = "''"!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]
  [!IF "node:name(.) = $ChannelName"!]
    [!LOOP "ComMUserPerChannel/*"!]
      [!VAR "UserName"= "node:name(node:ref(ComMUserChannel))"!]
      [!CALL "GetUserOsApplicationByName","UserName"="$UserName"!]
      [!IF "(($FilterByOsApplication = 'true') and ($UserOsApplication = $OsApplication)) or ($FilterByOsApplication = 'false')"!]
        [!VAR "UserFound" = "'false'"!]
        [!FOR "Idx" = "1" TO "count(text:split($FoundUsersOfChannel,' '))"!]
          [!IF "(string(text:split($FoundUsersOfChannel,' ')[position() = $Idx]) = $UserName)"!]
            [!VAR "UserFound" = "'true'"!]
          [!ENDIF!]
        [!ENDFOR!]
        [!IF "$UserFound = 'false'"!]
          [!IF "count(text:split($FoundUsersOfChannel,' ')) = 0"!]
            [!VAR "FoundUsersOfChannel" = "$UserName"!]
          [!ELSE!]
           [!VAR "FoundUsersOfChannel" = "concat($FoundUsersOfChannel,' ')"!]
           [!VAR "FoundUsersOfChannel" = "concat($FoundUsersOfChannel, $UserName)"!]
          [!ENDIF!]
        [!ENDIF!]
      [!ENDIF!] [!/*[!IF "(($FilterByOsApplication = 'true') and ($UserOsApplication = $OsApplication)) or ($FilterByOsApplication = 'false')"!]*/!]
    [!ENDLOOP!]
  [!ENDIF!] 
[!ENDLOOP!]    
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMChannelPerPnc/*"!]
  [!IF "node:name(node:ref(.)) = $ChannelName"!]
    [!LOOP "../../ComMUserPerPnc/*"!]
      [!VAR "UserName"= "node:name(node:ref(.))"!]
      [!CALL "GetUserOsApplicationByName","UserName"="$UserName"!]
      [!IF "(($FilterByOsApplication = 'true') and ($UserOsApplication = $OsApplication)) or ($FilterByOsApplication = 'false')"!]
        [!VAR "UserFound" = "'false'"!]
        [!FOR "Idx" = "1" TO "count(text:split($FoundUsersOfChannel,' '))"!]
          [!IF "(string(text:split($FoundUsersOfChannel,' ')[position() = $Idx]) = $UserName)"!]
            [!VAR "UserFound" = "'true'"!]
          [!ENDIF!]
        [!ENDFOR!]
        [!IF "$UserFound = 'false'"!]
          [!IF "count(text:split($FoundUsersOfChannel,' ')) = 0"!]
            [!VAR "FoundUsersOfChannel" = "$UserName"!]
          [!ELSE!]
           [!VAR "FoundUsersOfChannel" = "concat($FoundUsersOfChannel,' ')"!]
           [!VAR "FoundUsersOfChannel" = "concat($FoundUsersOfChannel, $UserName)"!]
          [!ENDIF!]
        [!ENDIF!]
      [!ENDIF!] [!/*[!IF "(($FilterByOsApplication = 'true') and ($UserOsApplication = $OsApplication)) or ($FilterByOsApplication = 'false')"!]*/!]        
    [!ENDLOOP!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetChannelsOfUser","UserName","FilterByOsApplication","OsApplication"!]
[!VAR "FoundChannelsOfUsers" = "''"!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*/ComMUserPerChannel/*"!]
  [!IF "(node:name(node:ref(ComMUserChannel)) = $UserName)"!]
    [!VAR "ChannelName" = "node:name(../..)"!]
    [!CALL "GetChannelOsApplicationByName","ChannelName"="$ChannelName"!]
    [!IF "(($FilterByOsApplication = 'true') and ($ChannelOsApplication = $OsApplication)) or ($FilterByOsApplication = 'false')"!]
      [!VAR "ChannelFound" = "'false'"!]
      [!FOR "Idx" = "1" TO "count(text:split($FoundChannelsOfUsers,' '))"!]
        [!IF "(string(text:split($FoundChannelsOfUsers,' ')[position() = $Idx]) = $ChannelName)"!]
          [!VAR "ChannelFound" = "'true'"!]
        [!ENDIF!]
      [!ENDFOR!]
      [!IF "$ChannelFound = 'false'"!]
        [!IF "count(text:split($FoundChannelsOfUsers,' ')) = 0"!]
          [!VAR "FoundChannelsOfUsers" = "$ChannelName"!]
        [!ELSE!]
         [!VAR "FoundChannelsOfUsers" = "concat($FoundChannelsOfUsers,' ')"!]
         [!VAR "FoundChannelsOfUsers" = "concat($FoundChannelsOfUsers, $ChannelName)"!]
        [!ENDIF!]
      [!ENDIF!]
    [!ENDIF!] [!/*[!IF "(($FilterByOsApplication = 'true') and ($ChannelOsApplication = $OsApplication)) or ($FilterByOsApplication = 'false')"!]*/!]
  [!ENDIF!]
[!ENDLOOP!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMUserPerPnc/*"!] 
  [!IF "node:name(node:ref(.)) = $UserName"!]
    [!LOOP "../../ComMChannelPerPnc/*"!]
      [!VAR "ChannelName" = "node:name(node:ref(.))"!]
      [!CALL "GetChannelOsApplicationByName","ChannelName"="$ChannelName"!]
      [!IF "(($FilterByOsApplication = 'true') and ($ChannelOsApplication = $OsApplication)) or ($FilterByOsApplication = 'false')"!]
        [!VAR "ChannelFound" = "'false'"!]
        [!FOR "Idx" = "1" TO "count(text:split($FoundChannelsOfUsers,' '))"!]
          [!IF "(string(text:split($FoundChannelsOfUsers,' ')[position() = $Idx]) = $ChannelName)"!]
            [!VAR "ChannelFound" = "'true'"!]
          [!ENDIF!]
        [!ENDFOR!]
        [!IF "$ChannelFound = 'false'"!]
          [!IF "count(text:split($FoundChannelsOfUsers,' ')) = 0"!]
            [!VAR "FoundChannelsOfUsers" = "$ChannelName"!]
          [!ELSE!]
           [!VAR "FoundChannelsOfUsers" = "concat($FoundChannelsOfUsers,' ')"!]
           [!VAR "FoundChannelsOfUsers" = "concat($FoundChannelsOfUsers, $ChannelName)"!]
          [!ENDIF!]
        [!ENDIF!]
      [!ENDIF!] [!/*[!IF "(($FilterByOsApplication = 'true') and ($ChannelOsApplication = $OsApplication)) or ($FilterByOsApplication = 'false')"!]*/!]
    [!ENDLOOP!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetUsedUserPlusChannelPlusMasterPncPlusInhibitionOsApplications"!]
[!CALL "GetMasterPncOsApplication"!]
[!CALL "GetUsedUserOsApplications"!]
[!CALL "GetUsedInhibitionOsApplication"!]
[!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications"="$MasterPncOsApplication"!]
[!VAR "OsApplicationAssignmentFound" = "'false'"!]
[!FOR "Idx1" = "1" TO "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' '))"!]
  [!IF "($FoundInhibitionOsApplication) = string(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')[position() = $Idx1])"!]
    [!VAR "OsApplicationAssignmentFound" = "'true'"!]
    [!BREAK!]
  [!ENDIF!]
[!ENDFOR!] [!/* [!FOR "Idx1" = "1" TO "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' '))"!] */!]
[!IF "$OsApplicationAssignmentFound = 'false'"!]
  [!IF "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')) = 0"!]
    [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "$FoundInhibitionOsApplication"!]
  [!ELSE!]
   [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "concat($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')"!]
   [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "concat($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,$FoundInhibitionOsApplication)"!]
  [!ENDIF!]
[!ENDIF!] 
[!FOR "Idx1" = "1" TO "count(text:split($FoundUserOsApplications,' '))"!]
  [!VAR "OsApplicationAssignmentFound" = "'false'"!]
  [!FOR "Idx2" = "1" TO "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' '))"!]
    [!IF "(string(text:split($FoundUserOsApplications,' ')[position() = $Idx1]) = string(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')[position() = $Idx2]))"!]
      [!VAR "OsApplicationAssignmentFound" = "'true'"!]
      [!BREAK!]
    [!ENDIF!]
  [!ENDFOR!] [!/* [!FOR "Idx1" = "1" TO "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' '))"!] */!]
  [!IF "$OsApplicationAssignmentFound = 'false'"!]
    [!IF "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')) = 0"!]
      [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "string(text:split($FoundUserOsApplications,' ')[position() = $Idx1])"!]
    [!ELSE!]
     [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "concat($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')"!]
     [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "concat($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,string(text:split($FoundUserOsApplications,' ')[position() = $Idx1]))"!]
    [!ENDIF!]
  [!ENDIF!] 
[!ENDFOR!] [!/*[!FOR "Idx1" = "1" TO "count(text:split($FoundUserOsApplications,' '))"!]*/!]
[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
  [!IF "node:exists(ComMChannelPartitionRef)"!]
    [!VAR "PartitionRef" = "ComMChannelPartitionRef"!]
    [!LOOP "as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $PartitionRef)]"!]
      [!VAR "OsApplicationAssignmentFound" = "'false'"!]
      [!FOR "Idx" = "1" TO "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' '))"!]
        [!IF "(string(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')[position() = $Idx]) = node:name(.))"!]
          [!VAR "OsApplicationAssignmentFound" = "'true'"!]
        [!ENDIF!]
      [!ENDFOR!]
      [!IF "$OsApplicationAssignmentFound = 'false'"!]
        [!IF "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')) = 0"!]
          [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "node:name(.)"!]
        [!ELSE!]
         [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "concat($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')"!]
         [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "concat($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,node:name(.))"!]
        [!ENDIF!]
      [!ENDIF!]
    [!ENDLOOP!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetChToCh_FromOsAppToOsAppList"!]
[!VAR "ChToChFromOsApp_ToOsApp" = "''"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]
  [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]
    [!IF "node:exists(EcuMComMChannelRef)"!]
      [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(EcuMComMChannelRef)/ComMChannelPartitionRef"!]
      [!VAR "FromOsApplication" ="$ChannelOsApplication"!]
      [!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
        [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef" = "ComMChannelPartitionRef"!]
        [!VAR "ToOsApplication" ="$ChannelOsApplication"!]
        [!IF "$FromOsApplication != $ToOsApplication"!]
          [!VAR "CurrentString" = "''"!]
          [!VAR "CurrentString"= "concat($CurrentString, $FromOsApplication)"!]
          [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
          [!VAR "CurrentString"= "concat($CurrentString, $ToOsApplication)"!]
          [!VAR "StringFound" = "'false'"!]
          [!FOR "Idx" = "1" TO "count(text:split($ChToChFromOsApp_ToOsApp,' '))"!]
            [!IF "string(text:split($ChToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
              [!VAR "StringFound" = "'true'"!]
            [!ENDIF!]
          [!ENDFOR!]
          [!IF "$StringFound = 'false'"!]
            [!IF "count(text:split($ChToChFromOsApp_ToOsApp,' ')) = 0"!]
                [!VAR "ChToChFromOsApp_ToOsApp" = "$CurrentString"!]
            [!ELSE!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp, ' ')"!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp, $FromOsApplication)"!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp,'->')"!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp, $ToOsApplication)"!]
            [!ENDIF!]
          [!ENDIF!]
        [!ENDIF!] [!/*[!IF "$FromOsApplication != $ToOsApplication"!]*/!]      
      [!ENDLOOP!] [!/* [!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!] */!]
    [!ENDIF!] [!/* [!IF "node:exists(EcuMComMChannelRef)"!] */!]
  [!ENDLOOP!] [!/* [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!] */!]
[!ELSE!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]*/!]  
  [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]
    [!IF "node:exists(EcuMComMChannelRef)"!]
      [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(EcuMComMChannelRef)/ComMChannelPartitionRef"!]
      [!VAR "FromOsApplication" ="$ChannelOsApplication"!]
      [!IF "node:exists(node:ref(EcuMComMChannelRef)/ComMManageReference/*[1])"!]
        [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(node:ref(EcuMComMChannelRef)/ComMManageReference/*[1])/ComMChannelPartitionRef"!]
        [!VAR "ToOsApplication" ="$ChannelOsApplication"!]
        [!IF "$FromOsApplication != $ToOsApplication"!]
          [!VAR "CurrentString" = "''"!]
          [!VAR "CurrentString"= "concat($CurrentString, $FromOsApplication)"!]
          [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
          [!VAR "CurrentString"= "concat($CurrentString, $ToOsApplication)"!]
          [!VAR "StringFound" = "'false'"!]
          [!FOR "Idx" = "1" TO "count(text:split($ChToChFromOsApp_ToOsApp,' '))"!]
            [!IF "string(text:split($ChToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
              [!VAR "StringFound" = "'true'"!]
            [!ENDIF!]
          [!ENDFOR!]
          [!IF "$StringFound = 'false'"!]
            [!IF "count(text:split($ChToChFromOsApp_ToOsApp,' ')) = 0"!]
                [!VAR "ChToChFromOsApp_ToOsApp" = "$CurrentString"!]
            [!ELSE!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp, ' ')"!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp, $FromOsApplication)"!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp,'->')"!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp, $ToOsApplication)"!]
            [!ENDIF!]
          [!ENDIF!]
        [!ENDIF!] [!/*[!IF "$FromOsApplication != $ToOsApplication"!]*/!]        
      [!ENDIF!] [!/*[!IF "node:exists(node:ref(EcuMComMChannelRef)/ComMManageReference/*[1])*/!]
    [!ENDIF!] [!/*[!IF "node:exists(EcuMComMChannelRef)"!]*/!]
  [!ENDLOOP!] [!/* [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!] */!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]*/!]
[!ENDMACRO!]

[!MACRO "GetChToChQueueSize","FromOsApplication","ToOsApplication"!]
[!VAR "ChToChQueueSize" = "num:i(0)"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]
  [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]
    [!IF "node:exists(EcuMComMChannelRef)"!]
      [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(EcuMComMChannelRef)/ComMChannelPartitionRef"!]
      [!VAR "FromOsApplicationLocal" ="$ChannelOsApplication"!]
      [!VAR "ChFound" = "'false'"!]
      [!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
        [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef" = "ComMChannelPartitionRef"!]
        [!VAR "ToOsApplicationLocal" ="$ChannelOsApplication"!]
        [!IF "($FromOsApplicationLocal = $FromOsApplication) and ($ToOsApplicationLocal = $ToOsApplication)"!]
           [!VAR "ChFound" = "'true'"!]
        [!ENDIF!] [!/*[!IF "($FromOsApplicationLocal = $FromOsApplication) and ($ToOsApplicationLocal = $ToOsApplication)"!]*/!]
      [!ENDLOOP!] [!/* [!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!] */!]
      [!IF "$ChFound = 'true'"!]
        [!VAR "ChToChQueueSize" = "num:i($ChToChQueueSize + 1)"!]
      [!ENDIF!] [!/*[!IF "$ChFound = 'true'"!]*/!]
    [!ENDIF!] [!/* [!IF "node:exists(EcuMComMChannelRef)"!] */!]
  [!ENDLOOP!] [!/* [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!] */!]
[!ELSE!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]*/!]  
  [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]
    [!IF "node:exists(EcuMComMChannelRef)"!]
      [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(EcuMComMChannelRef)/ComMChannelPartitionRef"!]
      [!VAR "FromOsApplicationLocal" ="$ChannelOsApplication"!]
      [!IF "node:exists(node:ref(EcuMComMChannelRef)/ComMManageReference/*[1])"!]
        [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(node:ref(EcuMComMChannelRef)/ComMManageReference/*[1])/ComMChannelPartitionRef"!]
        [!VAR "ToOsApplicationLocal" ="$ChannelOsApplication"!]
        [!IF "($FromOsApplicationLocal = $FromOsApplication) and ($ToOsApplicationLocal = $ToOsApplication)"!]
          [!VAR "ChToChQueueSize" = "num:i($ChToChQueueSize + 1)"!]
        [!ENDIF!] [!/*[!IF "($FromOsApplicationLocal = $FromOsApplication) and ($ToOsApplicationLocal = $ToOsApplication)"!]*/!]
      [!ENDIF!] [!/*[!IF "node:exists(node:ref(EcuMComMChannelRef)/ComMManageReference/*[1])*/!]
    [!ENDIF!] [!/*[!IF "node:exists(EcuMComMChannelRef)"!]*/!]
  [!ENDLOOP!] [!/* [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!] */!]  
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]*/!]  
[!ENDMACRO!] 

[!MACRO "GetChToMasterPnc_FromOsAppToOsAppList"!]
[!VAR "ChToMasterPncFromOsApp_ToOsApp" = "''"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]
  [!CALL "GetMasterPncOsApplication"!]
  [!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]
    [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]
      [!IF "node:exists(EcuMComMChannelRef)"!]
        [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef" = "node:ref(EcuMComMChannelRef)/ComMChannelPartitionRef"!]    
        [!IF "$ChannelOsApplication != $MasterPncOsApplication "!]
          [!VAR "CurrentString" = "''"!]
          [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
          [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
          [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
          [!VAR "StringFound" = "'false'"!]
          [!FOR "Idx" = "1" TO "count(text:split($ChToMasterPncFromOsApp_ToOsApp,' '))"!]
            [!IF "string(text:split($ChToMasterPncFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
              [!VAR "StringFound" = "'true'"!]
            [!ENDIF!]
          [!ENDFOR!]
          [!IF "$StringFound = 'false'"!]
            [!IF "count(text:split($ChToMasterPncFromOsApp_ToOsApp,' ')) = 0"!]
                [!VAR "ChToMasterPncFromOsApp_ToOsApp" = "$CurrentString"!]
            [!ELSE!]
              [!VAR "ChToMasterPncFromOsApp_ToOsApp"= "concat($ChToMasterPncFromOsApp_ToOsApp, ' ')"!]
              [!VAR "ChToMasterPncFromOsApp_ToOsApp"= "concat($ChToMasterPncFromOsApp_ToOsApp, $ChannelOsApplication)"!]
              [!VAR "ChToMasterPncFromOsApp_ToOsApp"= "concat($ChToMasterPncFromOsApp_ToOsApp,'->')"!]
              [!VAR "ChToMasterPncFromOsApp_ToOsApp"= "concat($ChToMasterPncFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
            [!ENDIF!]
          [!ENDIF!]
        [!ENDIF!] [!/*[!IF "$ChannelOsApplication != $MasterPncOsApplication "!]*/!]      
      [!ENDIF!] [!/*[!IF "node:exists(EcuMComMChannelRef)"!]*/!]
    [!ENDLOOP!] [!/*[!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]*/!]
  [!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]*/!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]*/!]
[!ENDMACRO!]

[!MACRO "GetChToMasterPncQueueSize","FromOsApplication"!]
[!VAR "ChToMasterPncQueueSize" = "num:i(0)"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]
  [!CALL "GetMasterPncOsApplication"!]  
  [!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]
    [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]
      [!IF "node:exists(EcuMComMChannelRef)"!]
        [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef" = "node:ref(EcuMComMChannelRef)/ComMChannelPartitionRef"!]    
        [!IF "$ChannelOsApplication = $FromOsApplication"!]
          [!VAR "ChToMasterPncQueueSize" = "num:i($ChToMasterPncQueueSize + 1)"!]
        [!ENDIF!] [!/*[!IF "$ChannelOsApplication = $FromOsApplication"!]*/!]
      [!ENDIF!] [!/*[!IF "node:exists(EcuMComMChannelRef)"!]*/!]
    [!ENDLOOP!] [!/*[!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]*/!]
  [!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]*/!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]*/!]
[!ENDMACRO!]

[!MACRO "GetUserToCh_FromOsAppToOsAppList"!]
[!VAR "UserToChFromOsApp_ToOsApp" = "''"!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]
  [!VAR "UserId" = "ComMUserIdentifier"!]
  [!CALL "GetUserOsApplication","UserEcuCPartitionRef"="ComMUserEcucPartitionRef"!]
  [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMUserPerPnc/*"!]
    [!IF "$UserId = node:value(node:ref(.)/ComMUserIdentifier)"!]
      [!LOOP "../../ComMChannelPerPnc/*"!]
        [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(.)/ComMChannelPartitionRef"!]
        [!IF "$UserOsApplication != $ChannelOsApplication"!]
          [!VAR "CurrentString" = "''"!]
          [!VAR "CurrentString"= "concat($CurrentString,$UserOsApplication)"!]
          [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
          [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
          [!VAR "UserToChannelFound" = "'false'"!]
          [!FOR "Idx1" = "1" TO "count(text:split($UserToChFromOsApp_ToOsApp,' '))"!]
            [!IF "($CurrentString) = string(text:split($UserToChFromOsApp_ToOsApp,' ')[position() = $Idx1])"!]
              [!VAR "UserToChannelFound" = "'true'"!]
              [!BREAK!]
            [!ENDIF!]
          [!ENDFOR!] [!/* [!FOR "Idx1" = "1" TO "count(text:split($UserToChFromOsApp_ToOsApp,' '))"!] */!]        
          [!IF "$UserToChannelFound = 'false'"!]
            [!IF "count(text:split($UserToChFromOsApp_ToOsApp,' ')) = 0"!]
              [!VAR "UserToChFromOsApp_ToOsApp" = "$CurrentString"!]
            [!ELSE!]
             [!VAR "UserToChFromOsApp_ToOsApp" = "concat($UserToChFromOsApp_ToOsApp,' ')"!]
             [!VAR "UserToChFromOsApp_ToOsApp" = "concat($UserToChFromOsApp_ToOsApp,$CurrentString)"!]
            [!ENDIF!]
          [!ENDIF!]
        [!ENDIF!] [!/*[!IF "$UserOsApplication != $ChannelOsApplication"!]*/!]
      [!ENDLOOP!] [!/*[!LOOP "../../ComMChannelPerPnc/*"!]*/!]
    [!ENDIF!] [!/*[!IF "$UserId = node:value(node:ref(.)/ComMUserIdentifier)"!]*/!]
  [!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMUserPerPnc/*"!]*/!]
  [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*/ComMUserPerChannel/*"!]
    [!IF "number(node:ref(ComMUserChannel)/ComMUserIdentifier) = $UserId"!]
      [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="../../ComMChannelPartitionRef"!]
        [!IF "$UserOsApplication != $ChannelOsApplication"!]
          [!VAR "CurrentString" = "''"!]
          [!VAR "CurrentString"= "concat($CurrentString,$UserOsApplication)"!]
          [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
          [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
          [!VAR "UserToChannelFound" = "'false'"!]
          [!FOR "Idx1" = "1" TO "count(text:split($UserToChFromOsApp_ToOsApp,' '))"!]
            [!IF "($CurrentString) = string(text:split($UserToChFromOsApp_ToOsApp,' ')[position() = $Idx1])"!]
              [!VAR "UserToChannelFound" = "'true'"!]
              [!BREAK!]
            [!ENDIF!]
          [!ENDFOR!] [!/* [!FOR "Idx1" = "1" TO "count(text:split($UserToChFromOsApp_ToOsApp,' '))"!] */!]        
          [!IF "$UserToChannelFound = 'false'"!]
            [!IF "count(text:split($UserToChFromOsApp_ToOsApp,' ')) = 0"!]
              [!VAR "UserToChFromOsApp_ToOsApp" = "$CurrentString"!]
            [!ELSE!]
             [!VAR "UserToChFromOsApp_ToOsApp" = "concat($UserToChFromOsApp_ToOsApp,' ')"!]
             [!VAR "UserToChFromOsApp_ToOsApp" = "concat($UserToChFromOsApp_ToOsApp,$CurrentString)"!]
            [!ENDIF!]
          [!ENDIF!]
        [!ENDIF!] [!/*[!IF "$UserOsApplication != $ChannelOsApplication"!]*/!]
    [!ENDIF!]
  [!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*/ComMUserPerChannel/*"!]*/!]
[!ENDLOOP!] 
[!ENDMACRO!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]*/!]




[!MACRO "GetUserToChannelQueueSize","FromOsApplication","ToOsApplication"!]
[!VAR "UserToChannelQueueSize"="num:i(0)"!]
[!IF "count(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*) > 0"!]
  [!/* Part Needed by ComM_RequestComMode */!]
  [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]
    [!CALL "GetUserOsApplicationByName","UserName"="node:name(.)"!]
    [!IF "$UserOsApplication = $FromOsApplication"!]
      [!CALL "GetChannelsOfUser","UserName"="node:name(.)","FilterByOsApplication"="'true'","OsApplication"="$ToOsApplication"!]
      [!IF "count(text:split($FoundChannelsOfUsers,' ')) > 0"!]
        [!VAR "UserToChannelQueueSize" = "num:i(num:i($UserToChannelQueueSize) + num:i(1))"!]
      [!ENDIF!]
    [!ENDIF!]
  [!ENDLOOP!]
  [!/* Part Needed by ClearUserRequest */!]
  [!IF "as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true'"!]
    [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]
      [!CALL "GetUsersOfChannel","ChannelName"="node:name(.)","FilterByOsApplication"="'true'","OsApplication"="$FromOsApplication"!]
      [!FOR "Idx1" = "1" TO "count(text:split($FoundUsersOfChannel,' '))"!]
        [!CALL "GetChannelsOfUser","UserName"="string(text:split($FoundUsersOfChannel,' ')[position() = $Idx1])","FilterByOsApplication"="'true'","OsApplication"="$ToOsApplication"!]
        [!IF "count(text:split($FoundChannelsOfUsers,' ')) > 0"!]
          [!VAR "UserToChannelQueueSize" = "num:i(num:i($UserToChannelQueueSize) + num:i(1))"!]
        [!ENDIF!]
      [!ENDFOR!]
    [!ENDLOOP!]    
  [!ENDIF!]
[!ENDIF!]
[!ENDMACRO!]

[!MACRO "GetMasterPncToCh_FromOsAppToOsAppList"!]
[!VAR "MasterPncToChFromOsApp_ToOsApp" = "''"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]
  [!CALL "GetMasterPncOsApplication"!]
  [!IF "node:exists(as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*/EcuMComMPNCRef)"!]
    [!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]
      [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]
        [!IF "node:exists(EcuMComMPNCRef)"!]
          [!LOOP "node:ref(EcuMComMPNCRef)/ComMChannelPerPnc/*"!]
            [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(.)/ComMChannelPartitionRef"!]
            [!IF "$MasterPncOsApplication != $ChannelOsApplication"!]
              [!VAR "CurrentString" = "''"!]
              [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
              [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
              [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
              [!VAR "StringFound" = "'false'"!]
              [!FOR "Idx" = "1" TO "count(text:split($MasterPncToChFromOsApp_ToOsApp,' '))"!]
                [!IF "string(text:split($MasterPncToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
                  [!VAR "StringFound" = "'true'"!]
                [!ENDIF!]
              [!ENDFOR!]
              [!IF "$StringFound = 'false'"!]
                [!IF "count(text:split($MasterPncToChFromOsApp_ToOsApp,' ')) = 0"!]
                    [!VAR "MasterPncToChFromOsApp_ToOsApp" = "$CurrentString"!]
                [!ELSE!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, ' ')"!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp,'->')"!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, $ChannelOsApplication)"!]
                [!ENDIF!]
              [!ENDIF!]
            [!ENDIF!] [!/*[!IF "$MasterPncOsApplication != $ChannelOsApplication"!]*/!]
          [!ENDLOOP!]
        [!ENDIF!]
      [!ENDLOOP!]
    [!ELSE!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]*/!]
      [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]
        [!IF "node:exists(EcuMComMPNCRef)"!]
          [!LOOP "node:ref(EcuMComMPNCRef)/ComMChannelPerPnc/*"!]
            [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(.)/ComMChannelPartitionRef"!]
            [!IF "$MasterPncOsApplication != $ChannelOsApplication"!]
              [!VAR "CurrentString" = "''"!]
              [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
              [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
              [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
              [!VAR "StringFound" = "'false'"!]
              [!FOR "Idx" = "1" TO "count(text:split($MasterPncToChFromOsApp_ToOsApp,' '))"!]
                [!IF "string(text:split($MasterPncToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
                  [!VAR "StringFound" = "'true'"!]
                [!ENDIF!]
              [!ENDFOR!]
              [!IF "$StringFound = 'false'"!]
                [!IF "count(text:split($MasterPncToChFromOsApp_ToOsApp,' ')) = 0"!]
                    [!VAR "MasterPncToChFromOsApp_ToOsApp" = "$CurrentString"!]
                [!ELSE!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, ' ')"!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp,'->')"!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, $ChannelOsApplication)"!]
                [!ENDIF!]
              [!ENDIF!]
            [!ENDIF!] [!/*[!IF "$MasterPncOsApplication != $ChannelOsApplication"!]*/!]
            [!IF "node:exists(node:ref(.)/ComMManageReference/*[1])"!]
              [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(node:ref(.)/ComMManageReference/*[1])/ComMChannelPartitionRef"!]
              [!IF "$MasterPncOsApplication != $ChannelOsApplication"!]
                [!VAR "CurrentString" = "''"!]
                [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
                [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
                [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
                [!VAR "StringFound" = "'false'"!]
                [!FOR "Idx" = "1" TO "count(text:split($MasterPncToChFromOsApp_ToOsApp,' '))"!]
                  [!IF "string(text:split($MasterPncToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
                    [!VAR "StringFound" = "'true'"!]
                  [!ENDIF!]
                [!ENDFOR!]
                [!IF "$StringFound = 'false'"!]
                  [!IF "count(text:split($MasterPncToChFromOsApp_ToOsApp,' ')) = 0"!]
                      [!VAR "MasterPncToChFromOsApp_ToOsApp" = "$CurrentString"!]
                  [!ELSE!]
                    [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, ' ')"!]
                    [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
                    [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp,'->')"!]
                    [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, $ChannelOsApplication)"!]
                  [!ENDIF!]
                [!ENDIF!]
              [!ENDIF!] [!/*[!IF "$MasterPncOsApplication != $ChannelOsApplication"!] */!]          
            [!ENDIF!] [!/*[!IF "node:exists(node:ref(.)/ComMManageReference/*[1])"!] */!]          
          [!ENDLOOP!] [!/* [!LOOP "node:ref(EcuMComMPNCRef)/ComMChannelPerPnc/*"!] */!]
        [!ENDIF!] [!/* [!IF "node:exists(EcuMComMPNCRef)"!] */!]
      [!ENDLOOP!] [!/* [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!] */!]
    [!ENDIF!]
  [!ENDIF!] [!/*[!IF "node:exists(as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*/EcuMComMPNCRef)"!]*/!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]*/!]
[!ENDMACRO!]

[!MACRO "GetMasterPncToChQueueSize","ToOsApplication"!]
[!VAR "MasterPncToChQueueSize"="num:i(0)"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]
  [!/* Part needed by ComM_EcuM_PNCWakeUpIndication indication*/!]
  [!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]
    [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]
      [!IF "node:exists(EcuMComMPNCRef)"!]
        [!VAR "ChannelApplicationFound" = "'false'"!]
        [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]
          [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="ComMChannelPartitionRef"!]
          [!IF "$ChannelOsApplication = $ToOsApplication"!]
            [!VAR "ChannelApplicationFound" = "'true'"!]
          [!ENDIF!] [!/*[!IF "$ChannelOsApplication = $ToOsApplication"!]*/!]
        [!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]*/!]
        [!IF "$ChannelApplicationFound = 'true'"!]
          [!VAR "MasterPncToChQueueSize" = "num:i($MasterPncToChQueueSize + 1)"!]        
        [!ENDIF!] [!/* [!IF "$ChannelApplicationFound = 'true'"!] */!]
      [!ENDIF!] [!/*[!IF "node:exists(EcuMComMPNCRef)"!]*/!]
    [!ENDLOOP!] [!/*[!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]*/!]
  [!ELSE!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]*/!]
    [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]
      [!IF "node:exists(EcuMComMPNCRef)"!]
        [!VAR "LocalPncId" = "node:ref(EcuMComMPNCRef)/ComMPncId"!]
        [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*"!]
          [!IF "number(ComMPncId)= $LocalPncId"!]
            [!VAR "ChannelApplicationFound" = "'false'"!]
            [!LOOP "ComMChannelPerPnc/*"!]
              [!VAR "ChannelName" = "node:name(node:ref(.))"!]
              [!CALL "GetChannelOsApplicationByName","ChannelName"="$ChannelName"!]
              [!IF "$ToOsApplication = $ChannelOsApplication"!]
                [!VAR "ChannelApplicationFound" = "'true'"!]
              [!ENDIF!] [!/*[!IF "$ToOsApplication = $ChannelOsApplication"!]*/!]
              [!IF "node:exists(node:ref(.)/ComMManageReference/*[1])"!]
                [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(node:ref(.)/ComMManageReference/*[1])/ComMChannelPartitionRef"!]
                [!IF "$ToOsApplication = $ChannelOsApplication"!]
                  [!VAR "ChannelApplicationFound" = "'true'"!]
                [!ENDIF!] [!/*[!IF "node:exists(node:ref(.)/ComMManageReference/*[1]"!]*/!]
              [!ENDIF!] [!/*[!IF "node:exists(node:ref(.)/ComMManageReference/*[1])"!]*/!]                          
            [!ENDLOOP!] [!/*[!LOOP "ComMChannelPerPnc/*"!] */!]
            [!IF "$ChannelApplicationFound = 'true'"!]
              [!VAR "MasterPncToChQueueSize" = "num:i($MasterPncToChQueueSize + 1)"!]        
            [!ENDIF!] [!/* [!IF "$ChannelApplicationFound = 'true'"!] */!]            
          [!ENDIF!] [!/*[!IF "number(ComMPncId) = $LocalPncId"!]*/!]
        [!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*"!]*/!]
      [!ENDIF!] [!/*[!IF "node:exists(EcuMComMPNCRef)"!] */!]
    [!ENDLOOP!] [!/*[!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]*/!]   
  [!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]*/!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]*/!]
[!ENDMACRO!]

[!MACRO "GetChToUser_FromOsAppToOsAppList"!]
[!VAR "ChToUserFromOsApp_ToOsApp" = "''"!]
[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMRteUsage = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true')"!]
  [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]
    [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="ComMChannelPartitionRef"!]
    [!VAR "ChannelId" = "ComMChannelId"!]
    [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMChannelPerPnc/*"!]
      [!IF "node:value(node:ref(.)/ComMChannelId) = ($ChannelId)"!]
        [!LOOP "../../ComMUserPerPnc/*"!]
          [!CALL "GetUserOsApplication","UserEcuCPartitionRef"="node:ref(.)/ComMUserEcucPartitionRef"!]
          [!IF "$UserOsApplication != $ChannelOsApplication"!]
            [!VAR "CurrentString" = "''"!]
            [!VAR "CurrentString"= "concat($CurrentString,$ChannelOsApplication)"!]
            [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
            [!VAR "CurrentString"= "concat($CurrentString, $UserOsApplication)"!]
            [!VAR "ChannelToUserFound" = "'false'"!]
            [!FOR "Idx1" = "1" TO "count(text:split($ChToUserFromOsApp_ToOsApp,' '))"!]
              [!IF "($CurrentString) = string(text:split($ChToUserFromOsApp_ToOsApp,' ')[position() = $Idx1])"!]
                [!VAR "ChannelToUserFound" = "'true'"!]
                [!BREAK!]
              [!ENDIF!]
            [!ENDFOR!] [!/* [!FOR "Idx1" = "1" TO "count(text:split($ChToUserFromOsApp_ToOsApp,' '))"!] */!]        
            [!IF "$ChannelToUserFound = 'false'"!]
              [!IF "count(text:split($ChToUserFromOsApp_ToOsApp,' ')) = 0"!]
                [!VAR "ChToUserFromOsApp_ToOsApp" = "$CurrentString"!]
              [!ELSE!]
               [!VAR "ChToUserFromOsApp_ToOsApp" = "concat($ChToUserFromOsApp_ToOsApp,' ')"!]
               [!VAR "ChToUserFromOsApp_ToOsApp" = "concat($ChToUserFromOsApp_ToOsApp,$CurrentString)"!]
              [!ENDIF!]
            [!ENDIF!]
          [!ENDIF!]
        [!ENDLOOP!]
      [!ENDIF!]
    [!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMChannelPerPnc/*"!]*/!]
    [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*/ComMUserPerChannel/*"!]
      [!IF "(../../ComMChannelId) = ($ChannelId)"!]
        [!CALL "GetUserOsApplication","UserEcuCPartitionRef"="node:ref(ComMUserChannel)/ComMUserEcucPartitionRef"!]
        [!IF "$UserOsApplication != $ChannelOsApplication"!]
          [!VAR "CurrentString" = "''"!]
          [!VAR "CurrentString"= "concat($CurrentString,$ChannelOsApplication)"!]
          [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
          [!VAR "CurrentString"= "concat($CurrentString, $UserOsApplication)"!]
          [!VAR "ChannelToUserFound" = "'false'"!]
          [!FOR "Idx1" = "1" TO "count(text:split($ChToUserFromOsApp_ToOsApp,' '))"!]
            [!IF "($CurrentString) = string(text:split($ChToUserFromOsApp_ToOsApp,' ')[position() = $Idx1])"!]
              [!VAR "ChannelToUserFound" = "'true'"!]
              [!BREAK!]
            [!ENDIF!]
          [!ENDFOR!] [!/* [!FOR "Idx1" = "1" TO "count(text:split($ChToUserFromOsApp_ToOsApp,' '))"!] */!]        
          [!IF "$ChannelToUserFound = 'false'"!]
            [!IF "count(text:split($ChToUserFromOsApp_ToOsApp,' ')) = 0"!]
              [!VAR "ChToUserFromOsApp_ToOsApp" = "$CurrentString"!]
            [!ELSE!]
             [!VAR "ChToUserFromOsApp_ToOsApp" = "concat($ChToUserFromOsApp_ToOsApp,' ')"!]
             [!VAR "ChToUserFromOsApp_ToOsApp" = "concat($ChToUserFromOsApp_ToOsApp,$CurrentString)"!]
            [!ENDIF!]
          [!ENDIF!]
        [!ENDIF!]
      [!ENDIF!]
    [!ENDLOOP!] [!/* [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*/ComMUserPerChannel/*"!] */!]
  [!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]*/!]
[!ENDIF!] [!/*[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMRteUsage = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true')"!]*/!]
[!ENDMACRO!]

[!MACRO "GetChannelToUserQueueSize","FromOsApplication","ToOsApplication"!]
[!VAR "ChannelToUserQueueSize"="num:i(0)"!]
[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMRteUsage = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true')"!]
  [!VAR "ChannelToUserQueueSizeTemp"="num:i(0)"!]
  [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]
    [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="ComMChannelPartitionRef"!]
    [!IF "$ChannelOsApplication = $FromOsApplication"!]
      [!CALL "GetUsersOfChannel","ChannelName"="node:name(.)","FilterByOsApplication"="'true'","OsApplication"="$ToOsApplication"!]
      [!IF "num:i(count(text:split($FoundUsersOfChannel,' '))) > 0"!]
        [!VAR "ChannelToUserQueueSizeTemp"="num:i($ChannelToUserQueueSizeTemp) + num:i(1)"!]
      [!ENDIF!]
    [!ENDIF!]
  [!ENDLOOP!] [!/* [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!] */!]
  
  [!IF "as:modconf('ComM')[1]/ComMGeneral/ComMRteUsage = 'true'"!]
    [!VAR "ChannelToUserQueueSize"="num:i($ChannelToUserQueueSizeTemp)"!]
  [!ENDIF!] [!/* [!IF "as:modconf('ComM')[1]/ComMGeneral/ComMRteUsage = 'true'"!] */!]

  [!IF "as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true'"!]
    [!VAR "ChannelToUserQueueSize"="num:i($ChannelToUserQueueSizeTemp)"!]
  [!ENDIF!] [!/* [!IF "as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true'"!] */!]

[!ENDIF!] [!/*[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMRteUsage = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true')"!]*/!]
[!ENDMACRO!]

[!MACRO "GetInhibitionToCh_FromOsAppToOsAppList"!]
[!VAR "InhibitionToChFromOsApp_ToOsApp" = "''"!]
[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true')"!]
  [!CALL "GetInhibitionOsApplication"!]
  [!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
    [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef" = "ComMChannelPartitionRef"!]
    [!VAR "ToOsApplication"= "$ChannelOsApplication"!]
    [!IF "$InhibitionOsApplication != $ToOsApplication"!]
      [!VAR "CurrentString" = "''"!]
      [!VAR "CurrentString"= "concat($CurrentString, $InhibitionOsApplication)"!]
      [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
      [!VAR "CurrentString"= "concat($CurrentString, $ToOsApplication)"!]
      [!VAR "StringFound" = "'false'"!]
      [!FOR "Idx" = "1" TO "count(text:split($InhibitionToChFromOsApp_ToOsApp,' '))"!]
        [!IF "string(text:split($InhibitionToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
          [!VAR "StringFound" = "'true'"!]
        [!ENDIF!]
      [!ENDFOR!] 
      [!IF "$StringFound = 'false'"!]
        [!IF "count(text:split($InhibitionToChFromOsApp_ToOsApp,' ')) = 0"!]
            [!VAR "InhibitionToChFromOsApp_ToOsApp" = "$CurrentString"!]
        [!ELSE!]
          [!VAR "InhibitionToChFromOsApp_ToOsApp"= "concat($InhibitionToChFromOsApp_ToOsApp, ' ')"!]
          [!VAR "InhibitionToChFromOsApp_ToOsApp"= "concat($InhibitionToChFromOsApp_ToOsApp, $InhibitionOsApplication)"!]
          [!VAR "InhibitionToChFromOsApp_ToOsApp"= "concat($InhibitionToChFromOsApp_ToOsApp,'->')"!]
          [!VAR "InhibitionToChFromOsApp_ToOsApp"= "concat($InhibitionToChFromOsApp_ToOsApp, $ToOsApplication)"!]
        [!ENDIF!]
      [!ENDIF!]
    [!ENDIF!] [!/*[!IF "$InhibitionOsApplication != $ToOsApplication"!]*/!]
  [!ENDLOOP!] [!/*[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]*/!]
[!ENDIF!] [!/* [!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true')"!] */!]
[!ENDMACRO!]

[!MACRO "GetInhibitionToChQueueSize","ToOsApplication"!]
[!VAR "InhibitionToChQueueSize" = "num:i(0)"!]
[!VAR "FoundChannelsLocalCount"="num:i(0)"!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]
  [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef" = "ComMChannelPartitionRef"!]
  [!IF "string($ToOsApplication) = $ChannelOsApplication"!]
    [!VAR "FoundChannelsLocalCount" = "num:i($FoundChannelsLocalCount + 1)"!]
  [!ENDIF!] [!/* [!IF "string($ToOsApplication) == $ChannelOsApplication"!] */!]    
[!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]*/!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true'"!]
  [!VAR "InhibitionToChQueueSize" = "num:i(2 * $FoundChannelsLocalCount)"!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true'"!]*/!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true'"!]
  [!VAR "InhibitionToChQueueSize" = "num:i($InhibitionToChQueueSize + $FoundChannelsLocalCount)"!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true'"!]*/!]
[!ENDMACRO!]

[!MACRO "GetUserToMasterPnc_FromOsAppToOsAppList"!]
[!VAR "UserToMasterPncFromOsApp_ToOsApp" = "''"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]
  [!CALL "GetMasterPncOsApplication"!]
  [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]
    [!VAR "UserId" = "ComMUserIdentifier"!]
    [!IF "num:i(count(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMUserPerPnc/*[number(node:ref(.)/ComMUserIdentifier) = $UserId])) > 0"!]
      [!CALL "GetUserOsApplication","UserEcuCPartitionRef"="ComMUserEcucPartitionRef"!]
      [!IF "$UserOsApplication != $MasterPncOsApplication"!]
        [!VAR "CurrentString" = "''"!]
        [!VAR "CurrentString"= "concat($CurrentString, $UserOsApplication)"!]
        [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
        [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
        [!VAR "StringFound" = "'false'"!]
        [!FOR "Idx" = "1" TO "count(text:split($UserToMasterPncFromOsApp_ToOsApp,' '))"!]
          [!IF "string(text:split($UserToMasterPncFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
            [!VAR "StringFound" = "'true'"!]
          [!ENDIF!]
        [!ENDFOR!] 
        [!IF "$StringFound = 'false'"!]
          [!IF "count(text:split($UserToMasterPncFromOsApp_ToOsApp,' ')) = 0"!]
              [!VAR "UserToMasterPncFromOsApp_ToOsApp" = "$CurrentString"!]
          [!ELSE!]
            [!VAR "UserToMasterPncFromOsApp_ToOsApp"= "concat($UserToMasterPncFromOsApp_ToOsApp, ' ')"!]
            [!VAR "UserToMasterPncFromOsApp_ToOsApp"= "concat($UserToMasterPncFromOsApp_ToOsApp, $UserOsApplication)"!]
            [!VAR "UserToMasterPncFromOsApp_ToOsApp"= "concat($UserToMasterPncFromOsApp_ToOsApp,'->')"!]
            [!VAR "UserToMasterPncFromOsApp_ToOsApp"= "concat($UserToMasterPncFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
          [!ENDIF!]
        [!ENDIF!]
      [!ENDIF!]
    [!ENDIF!] [!/*[!IF "num:i(count(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*[1]/ComMUserPerPnc/*[number(node:ref(.)/ComMUserIdentifier) = $UserId]))"!]*/!]
  [!ENDLOOP!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]*/!]
[!ENDMACRO!]

[!MACRO "GetUserToMasterPncQueueSize","FromOsApplication"!]
[!VAR "UserToMasterPncQueueSize" = "num:i(0)"!]
[!CALL "GetMasterPncOsApplication"!]
[!VAR "InhibitionCumulativeUsersOfChannel" = "''"!]
[!/* Part needed by ComM_ClearUserRequest */!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true'"!]
  [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]
    [!CALL "GetUsersOfChannel","ChannelName"="node:name(.)","FilterByOsApplication"="'true'","OsApplication"="$FromOsApplication"!]
    [!IF "count(text:split($InhibitionCumulativeUsersOfChannel,' ')) = 0"!]
      [!VAR "InhibitionCumulativeUsersOfChannel" = "$FoundUsersOfChannel"!]
    [!ELSE!]
      [!VAR "InhibitionCumulativeUsersOfChannel" = "concat($InhibitionCumulativeUsersOfChannel,' ')"!]
      [!VAR "InhibitionCumulativeUsersOfChannel" = "concat($InhibitionCumulativeUsersOfChannel, $FoundUsersOfChannel)"!]
    [!ENDIF!]
  [!ENDLOOP!]
  [!FOR "Idx1" = "1" TO "count(text:split($InhibitionCumulativeUsersOfChannel,' '))"!]
    [!VAR "CurrentUserName" = "string(text:split($InhibitionCumulativeUsersOfChannel,' ')[position() = $Idx1])"!]
    [!IF "num:i(count(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMUserPerPnc/*[node:name(node:ref(.)) = $CurrentUserName])) > 0"!]
      [!CALL "GetUserOsApplicationByName","UserName"="$CurrentUserName"!]
      [!IF "$UserOsApplication != $MasterPncOsApplication"!]
        [!VAR "UserToMasterPncQueueSize" = "num:i($UserToMasterPncQueueSize + 1)"!]
      [!ENDIF!] [!/*[!IF "$UserOsApplication != $MasterPncOsApplication"!] */!]
    [!ENDIF!] [!/*[!IF "num:i(count(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMUserPerPnc/*[node:name(node:ref(.)) = $CurrentUserName])) > 0"!]*/!]
  [!ENDFOR!] [!/*[!FOR "Idx1" = "1" TO "count(text:split($InhibitionCumulativeUsersOfChannel,' '))"!]*/!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true'"!]*/!]
[!/* Part needed by ComM_ASR40_RequestComMode */!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]
  [!VAR "CurrentUserName" = "node:name(.)"!]
  [!IF "num:i(count(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMUserPerPnc/*[node:name(node:ref(.)) = $CurrentUserName])) > 0"!]
    [!CALL "GetUserOsApplicationByName","UserName"="$CurrentUserName"!]
    [!IF "(($UserOsApplication = $FromOsApplication) and ($UserOsApplication != $MasterPncOsApplication))"!]
      [!VAR "UserToMasterPncQueueSize" = "num:i($UserToMasterPncQueueSize + 1)"!]
    [!ENDIF!] [!/*[!IF "$UserOsApplication != $MasterPncOsApplication"!] */!]
  [!ENDIF!] [!/*[!IF "num:i(count(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMUserPerPnc/*[node:name(node:ref(.)) = $CurrentUserName])) > 0"!]*/!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetUserToInhibition_FromOsAppToOsAppList"!]
[!VAR "UserToInhibitionFromOsApp_ToOsApp" = "''"!]
[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true')"!]
  [!CALL "GetInhibitionOsApplication"!]
  [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]
    [!CALL "GetChannelsOfUser","UserName"="node:name(.)","FilterByOsApplication"="'false'","OsApplication"="''"!]
    [!CALL "GetUserOsApplication","UserEcuCPartitionRef"="ComMUserEcucPartitionRef"!]
    [!IF "$UserOsApplication != $InhibitionOsApplication"!]
      [!VAR "CurrentString" = "''"!]
      [!VAR "CurrentString"= "concat($CurrentString, $UserOsApplication)"!]
      [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
      [!VAR "CurrentString"= "concat($CurrentString, $InhibitionOsApplication)"!]
      [!VAR "StringFound" = "'false'"!]
      [!FOR "Idx" = "1" TO "count(text:split($UserToInhibitionFromOsApp_ToOsApp,' '))"!]
        [!IF "string(text:split($UserToInhibitionFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
          [!VAR "StringFound" = "'true'"!]
        [!ENDIF!]
      [!ENDFOR!] [!/*[!FOR "Idx" = "1" TO "count(text:split($UserToInhibitionFromOsApp_ToOsApp,' '))"!]*/!]
      [!IF "$StringFound = 'false'"!]
        [!IF "count(text:split($UserToInhibitionFromOsApp_ToOsApp,' ')) = 0"!]
            [!VAR "UserToInhibitionFromOsApp_ToOsApp" = "$CurrentString"!]
        [!ELSE!]
          [!VAR "UserToInhibitionFromOsApp_ToOsApp"= "concat($UserToInhibitionFromOsApp_ToOsApp, ' ')"!]
          [!VAR "UserToInhibitionFromOsApp_ToOsApp"= "concat($UserToInhibitionFromOsApp_ToOsApp, $UserOsApplication)"!]
          [!VAR "UserToInhibitionFromOsApp_ToOsApp"= "concat($UserToInhibitionFromOsApp_ToOsApp,'->')"!]
          [!VAR "UserToInhibitionFromOsApp_ToOsApp"= "concat($UserToInhibitionFromOsApp_ToOsApp, $InhibitionOsApplication)"!]
        [!ENDIF!]
      [!ENDIF!] [!/*[!IF "$StringFound = 'false'"!]*/!]
    [!ENDIF!] [!/*[!IF "$UserOsApplication != $InhibitionOsApplication"!]*/!]
  [!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]*/!]
[!ENDIF!] [!/*[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true')"!]*/!]
[!ENDMACRO!]

[!MACRO "GetUserToInhibitionQueueSize","FromOsApplication"!]
[!CALL "GetInhibitionOsApplication"!]
[!VAR "UserToInhibitionQueueSize"="num:i(0)"!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]
  [!CALL "GetUserOsApplication","UserEcuCPartitionRef"="ComMUserEcucPartitionRef"!]
  [!IF "$FromOsApplication = $UserOsApplication"!]
    [!CALL "GetChannelsOfUser","UserName"="node:name(.)","FilterByOsApplication"="'false'","OsApplication"="''"!]
    [!VAR "UserToInhibitionQueueSize" = "num:i($UserToInhibitionQueueSize + count(text:split($FoundChannelsOfUsers,' ')))"!]
  [!ENDIF!] [!/*[!IF "$FromOsApplication = $UserOsApplication"!]*/!]
[!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]*/!]
[!ENDMACRO!]

[!MACRO "GetChToInhibition_FromOsAppToOsAppList"!]
[!VAR "ChToInhibitionFromOsApp_ToOsApp" = "''"!]
[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true')"!]
  [!CALL "GetInhibitionOsApplication"!]
  [!CALL "GetUsedChannelsOsApplications"!]
  [!FOR "Idx" = "1" TO "count(text:split($FoundChannelsOsApplications,' '))"!]
    [!VAR "FromOsApplication" = "string(text:split($FoundChannelsOsApplications,' ')[position() = $Idx])"!]
    [!VAR "ToOsApplication" = "$InhibitionOsApplication"!]
    [!IF "$FromOsApplication != $ToOsApplication"!]
      [!VAR "CurrentString" = "''"!]
      [!VAR "CurrentString"= "concat($CurrentString, $FromOsApplication)"!]
      [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
      [!VAR "CurrentString"= "concat($CurrentString, $ToOsApplication)"!]
      [!IF "count(text:split($ChToInhibitionFromOsApp_ToOsApp,' ')) = 0"!]
        [!VAR "ChToInhibitionFromOsApp_ToOsApp" = "$CurrentString"!]
      [!ELSE!]
        [!VAR "ChToInhibitionFromOsApp_ToOsApp" = "concat($ChToInhibitionFromOsApp_ToOsApp,' ')"!]
        [!VAR "ChToInhibitionFromOsApp_ToOsApp" = "concat($ChToInhibitionFromOsApp_ToOsApp,$CurrentString)"!]
      [!ENDIF!]
    [!ENDIF!] [!/*[!IF "$FromOsApplication != $ToOsApplication"!]*/!]
  [!ENDFOR!] [!/*[!FOR "Idx" = "1" TO "count(text:split($FoundChannelsOsApplications,' '))"!]*/!]
[!ENDIF!] [!/*[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true')"!]*/!]
[!ENDMACRO!]

[!MACRO "GetChToInhibitionQueueSize","FromOsApplication"!]
[!VAR "ChToInhibitionQueueSize" = "num:i(0)"!]
[!VAR "FoundChannelsLocalCount"="num:i(0)"!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]
  [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef" = "ComMChannelPartitionRef"!]
  [!IF "string($FromOsApplication) = $ChannelOsApplication"!]
    [!VAR "FoundChannelsLocalCount" = "num:i($FoundChannelsLocalCount + 1)"!]
  [!ENDIF!] [!/* [!IF "string($FromOsApplication) == $ChannelOsApplication"!] */!]    
[!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]*/!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true'"!]
  [!VAR "ChToInhibitionQueueSize" = "num:i($FoundChannelsLocalCount)"!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true'"!]*/!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true'"!]
  [!VAR "ChToInhibitionQueueSize" = "num:i($ChToInhibitionQueueSize + $FoundChannelsLocalCount)"!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true'"!]*/!]
[!ENDMACRO!]

[!MACRO "GetDcmChannelFound","CurrentComMChannelId"!]
[!VAR "DcmChannelFound" = "'false'"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMDcmUsage = 'true'"!]
  [!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('Dcm')[1]/DcmConfigSet/*/DcmDsl/DcmDslProtocol/DcmDslProtocolRow/*/DcmDslConnection/*/DcmDslProtocolRx/*/DcmDslProtocolRxComMChannelRef)), 'ComMChannelId'))"!]
    [!IF "number(ComMChannelId) = $CurrentComMChannelId"!]
      [!VAR "DcmChannelFound" = "'true'"!]
      [!BREAK!]
    [!ENDIF!]
  [!ENDLOOP!]
[!ENDIF!]
[!ENDMACRO!]

[!MACRO "GetEcuMChannelFound","CurrentComMChannelId"!]      
[!VAR "EcuMChannelFound" = "'false'"!]
[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*/EcuMComMChannelRef)), 'ComMChannelId'))"!]
  [!IF "number(ComMChannelId) = $CurrentComMChannelId"!]
    [!VAR "EcuMChannelFound" = "'true'"!]
    [!BREAK!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetSynchShutDownChToMasterPnc_FromOsAppToOsAppList"!]
[!VAR "SynchShutDownChToMasterPncFromOsApp_ToOsApp" = "''"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]
  [!IF "node:exists(as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled) and (as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled = 'true')"!]
    [!CALL "GetActiveChMixedWithPassive"!]     
    [!IF "$ActiveChMixedWithPassive"!]
      [!CALL "GetMasterPncOsApplication"!]
      [!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
        [!IF "node:exists(ComMPncGatewayType) and (ComMPncGatewayType = 'COMM_GATEWAY_TYPE_PASSIVE')"!]
          [!CALL "GetChannelOsApplication", "ChannelEcuCPartitionRef" = "ComMChannelPartitionRef"!]
          [!IF "$ChannelOsApplication != $MasterPncOsApplication "!]
            [!VAR "CurrentString" = "''"!]
            [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
            [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
            [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
            [!VAR "StringFound" = "'false'"!]
            [!FOR "Idx" = "1" TO "count(text:split($SynchShutDownChToMasterPncFromOsApp_ToOsApp,' '))"!]
              [!IF "string(text:split($SynchShutDownChToMasterPncFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
                [!VAR "StringFound" = "'true'"!]
              [!ENDIF!]
            [!ENDFOR!]
            [!IF "$StringFound = 'false'"!]
              [!IF "count(text:split($SynchShutDownChToMasterPncFromOsApp_ToOsApp,' ')) = 0"!]
                  [!VAR "SynchShutDownChToMasterPncFromOsApp_ToOsApp" = "$CurrentString"!]
              [!ELSE!]
                [!VAR "SynchShutDownChToMasterPncFromOsApp_ToOsApp"= "concat($SynchShutDownChToMasterPncFromOsApp_ToOsApp, ' ')"!]
                [!VAR "SynchShutDownChToMasterPncFromOsApp_ToOsApp"= "concat($SynchShutDownChToMasterPncFromOsApp_ToOsApp, $ChannelOsApplication)"!]
                [!VAR "SynchShutDownChToMasterPncFromOsApp_ToOsApp"= "concat($SynchShutDownChToMasterPncFromOsApp_ToOsApp,'->')"!]
                [!VAR "SynchShutDownChToMasterPncFromOsApp_ToOsApp"= "concat($SynchShutDownChToMasterPncFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
              [!ENDIF!]
            [!ENDIF!]
          [!ENDIF!][!/*[!IF "$ChannelOsApplication != $MasterPncOsApplication "!]*/!]
        [!ENDIF!][!/*[!IF "node:exists(ComMPncGatewayType) and (ComMPncGatewayType = 'COMM_GATEWAY_TYPE_PASSIVE')"!]*/!]
      [!ENDLOOP!][!/*[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]*/!]
    [!ENDIF!][!/*[!IF "$ActiveChMixedWithPassive"!] */!]
  [!ENDIF!][!/*[!IF "node:exists(as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled) and (as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled = 'true')"!]*/!]
[!ENDIF!][!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]*/!]
[!ENDMACRO!]

[!MACRO "GetSynchShutDownChToMasterPnc_QueueSize","FromOsApplication"!]
[!VAR "SynchShutDownChToMasterPncQueueSize" = "num:i(0)"!]
[!IF "node:exists(as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled) and (as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled = 'true')"!]
  [!CALL "GetMasterPncOsApplication"!]
  [!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
    [!IF "node:exists(ComMPncGatewayType) and (ComMPncGatewayType = 'COMM_GATEWAY_TYPE_PASSIVE')"!]
      [!CALL "GetChannelOsApplication", "ChannelEcuCPartitionRef" = "ComMChannelPartitionRef"!]      
      [!IF "($ChannelOsApplication = $FromOsApplication)"!]
        [!VAR "SynchShutDownChToMasterPncQueueSize" = "num:i($SynchShutDownChToMasterPncQueueSize + 1)"!]
      [!ENDIF!] [!/*[!IF "($ChannelOsApplication = $FromOsApplication)"!]*/!]
    [!ENDIF!] [!/*[!IF "node:exists(ComMPncGatewayType) and (ComMPncGatewayType = 'COMM_GATEWAY_TYPE_PASSIVE')"!]*/!]
  [!ENDLOOP!] [!/*[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]*/!]
[!ENDIF!] [!/*[!IF "node:exists(as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled) and (as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled = 'true')"!]*/!]
[!ENDMACRO!]

[!MACRO "GetActiveChMixedWithPassive"!]
[!VAR "ActiveChMixedWithPassive" = "'false'"!]
[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
  [!VAR "ActiveChannelFound" = "'false'"!]
  [!VAR "PassiveChannelFound" = "'false'"!]
  [!IF "node:exists(ComMPncGatewayType) and (ComMPncGatewayType = 'COMM_GATEWAY_TYPE_ACTIVE')"!]
    [!VAR "ActiveChannelFound" = "'true'"!]
  [!ENDIF!]
  [!IF "node:exists(ComMPncGatewayType) and (ComMPncGatewayType = 'COMM_GATEWAY_TYPE_PASSIVE')"!]
    [!VAR "PassiveChannelFound" = "'true'"!]
  [!ENDIF!]
  [!IF "($ActiveChannelFound) and ($PassiveChannelFound)"!]
    [!VAR "ActiveChMixedWithPassive" = "'true'"!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetSynchShutDownMasterPncToCh_FromOsAppToOsAppList"!]
[!VAR "SynchShutDownMasterPncToChFromOsApp_ToOsApp"= "''"!]
[!IF "node:exists(as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled) and (as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled = 'true')"!]
  [!CALL "GetMasterPncOsApplication"!]
  [!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
    [!IF "node:exists(ComMPncGatewayType) and (ComMPncGatewayType = 'COMM_GATEWAY_TYPE_ACTIVE')"!]
      [!CALL "GetChannelOsApplication", "ChannelEcuCPartitionRef" = "ComMChannelPartitionRef"!]
      [!IF "$ChannelOsApplication != $MasterPncOsApplication "!]
        [!VAR "CurrentString" = "''"!]
        [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
        [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
        [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
        [!VAR "StringFound" = "'false'"!]
        [!FOR "Idx" = "1" TO "count(text:split($SynchShutDownMasterPncToChFromOsApp_ToOsApp,' '))"!]
          [!IF "string(text:split($SynchShutDownMasterPncToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
            [!VAR "StringFound" = "'true'"!]
          [!ENDIF!]
        [!ENDFOR!]
        [!IF "$StringFound = 'false'"!]
          [!IF "count(text:split($SynchShutDownMasterPncToChFromOsApp_ToOsApp,' ')) = 0"!]
              [!VAR "SynchShutDownMasterPncToChFromOsApp_ToOsApp" = "$CurrentString"!]
          [!ELSE!]
            [!VAR "SynchShutDownMasterPncToChFromOsApp_ToOsApp"= "concat($SynchShutDownMasterPncToChFromOsApp_ToOsApp, ' ')"!]
            [!VAR "SynchShutDownMasterPncToChFromOsApp_ToOsApp"= "concat($SynchShutDownMasterPncToChFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
            [!VAR "SynchShutDownMasterPncToChFromOsApp_ToOsApp"= "concat($SynchShutDownMasterPncToChFromOsApp_ToOsApp,'->')"!]
            [!VAR "SynchShutDownMasterPncToChFromOsApp_ToOsApp"= "concat($SynchShutDownMasterPncToChFromOsApp_ToOsApp, $ChannelOsApplication)"!]
          [!ENDIF!]
        [!ENDIF!]
      [!ENDIF!][!/*[!IF "$ChannelOsApplication != $MasterPncOsApplication "!]*/!]
    [!ENDIF!][!/* [!IF "node:exists(node:ref(.)/ComMPncGatewayType) and (node:ref(.)/ComMPncGatewayType = 'COMM_GATEWAY_TYPE_ACTIVE')"!] */!]
  [!ENDLOOP!]
[!ENDIF!]
[!ENDMACRO!]

[!MACRO "GetEvaluateChannelMasterPncToCh_FromOsAppToOsAppList"!]
[!VAR "EvaluateChannelMasterPncToChFromOsApp_ToOsApp" = "''"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]
  [!CALL "GetMasterPncOsApplication"!]
  [!/*Part needed by pnc state machine to channel */!]
  [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*"!]
    [!LOOP "ComMChannelPerPnc/*"!]
      [!VAR "ChannelName" = "node:name(node:ref(.))"!]
      [!CALL "GetChannelOsApplicationByName","ChannelName"="$ChannelName"!]
      [!IF "$MasterPncOsApplication != $ChannelOsApplication"!]
        [!VAR "CurrentString" = "''"!]
        [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
        [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
        [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
        [!VAR "StringFound" = "'false'"!]
        [!FOR "Idx" = "1" TO "count(text:split($EvaluateChannelMasterPncToChFromOsApp_ToOsApp,' '))"!]
          [!IF "string(text:split($EvaluateChannelMasterPncToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
            [!VAR "StringFound" = "'true'"!]
          [!ENDIF!]
        [!ENDFOR!]
        [!IF "$StringFound = 'false'"!]
          [!IF "count(text:split($EvaluateChannelMasterPncToChFromOsApp_ToOsApp,' ')) = 0"!]
              [!VAR "EvaluateChannelMasterPncToChFromOsApp_ToOsApp" = "$CurrentString"!]
          [!ELSE!]
            [!VAR "EvaluateChannelMasterPncToChFromOsApp_ToOsApp"= "concat($EvaluateChannelMasterPncToChFromOsApp_ToOsApp, ' ')"!]
            [!VAR "EvaluateChannelMasterPncToChFromOsApp_ToOsApp"= "concat($EvaluateChannelMasterPncToChFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
            [!VAR "EvaluateChannelMasterPncToChFromOsApp_ToOsApp"= "concat($EvaluateChannelMasterPncToChFromOsApp_ToOsApp,'->')"!]
            [!VAR "EvaluateChannelMasterPncToChFromOsApp_ToOsApp"= "concat($EvaluateChannelMasterPncToChFromOsApp_ToOsApp, $ChannelOsApplication)"!]
          [!ENDIF!]
        [!ENDIF!]
      [!ENDIF!] [!/*[!IF "$MasterPncOsApplication != $ChannelOsApplication"!]*/!]
    [!ENDLOOP!] [!/*[!LOOP "ComMChannelPerPnc/*"!]*/!]
  [!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*"!]*/!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]*/!]
[!ENDMACRO!]

[!ENDNOCODE!][!//
[!ENDIF!][!//