function BINP_CAN_MCU_R1_outputs(varargin)
%===========$Update Time :  2025-09-12 09:35:00 $=========
disp('Loading $Id: BINP_CAN_MCU_R1_outputs.m  2025-09-12 09:35:00    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2025-09-12 09:35:00 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_CAN_MCU_R1_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CANMsgValidEOPFVTRLocal1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EOPFVTRActualSpdSta_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_EOPFVTRCSInvalidSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EOPFVTRCanLossSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EOPFVTREnableOffSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EOPFVTRHallSigErrSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EOPFVTRLocal1CSSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EOPFVTRLocal1RCSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EOPFVTROverTempBCKSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EOPFVTROverTempSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EOPFVTROverVolSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EOPFVTRPumpReadySta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EOPFVTRRCInvalidSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EOPFVTRRunStatusSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EOPFVTRStartFailureSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EOPFVTRUnderVolSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
