/**
 * \file
 *
 * \brief AUTOSAR Cry
 *
 * This file contains the implementation of the AUTOSAR
 * module Cry.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2019 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 *  MISRA deviation report:
 *  - This file violates MISRA-C:2004, Rule 19.6:
 *       "#undef shall not be used"
 *    Reason:
 *       The specification document explicitely describes this mechanism.
 *  - This file violates MISRA-C:2004, Rule 19.15:
 *       "Precautions shall be taken in order to prevent the contents
 *        of a header file being included twice."
 *    Reason:
 *       This file needs to be included more than once in a compilation unit
 */

/*==================[inclusions]=============================================*/

/*==================[macros]=================================================*/

/*------------------[MemMap error checking]----------------------------------*/

#if (defined CRYSTUB_40_MEMMAP_ERROR) /* to prevent double definition */
#error CRYSTUB_40_MEMMAP_ERROR defined, wrong CryStub_40_MemMap.h usage
#endif /* if (!defined CRYSTUB_40_MEMMAP_ERROR) */

/** \brief Checks if this file has been correctly used
 **
 ** This definition checks if this file has been correctly included
 ** the last time.
 ** We do it here, before the big if-elif. */
#define CRYSTUB_40_MEMMAP_ERROR

/* turn off "no #undef" warnings for this file */
#if (defined __TenDRA__)
#pragma TenDRA error "misra98_092" off
#pragma TenDRA error "misra04_19_6" off
#endif

/*------------------[MemMap extensions]--------------------------------------*/

#if 0 /* to be able to use #elif for every module */

/*------------------[Start of a module]--------------------------------------*/

#elif (defined CRYSTUB_40_START_SEC_CODE)
  #undef CRYSTUB_40_START_SEC_CODE
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CODE)
  #undef CRYSTUB_40_STOP_SEC_CODE
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_APPL_CODE || defined CRYSTUB_40_START_SEC_CALLOUT_CODE)
  #undef CRYSTUB_40_START_SEC_APPL_CODE
  #undef CRYSTUB_40_START_SEC_CALLOUT_CODE
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_APPL_CODE || defined CRYSTUB_40_STOP_SEC_CALLOUT_CODE)
  #undef CRYSTUB_40_STOP_SEC_APPL_CODE
  #undef CRYSTUB_40_STOP_SEC_CALLOUT_CODE
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_NOINIT_BOOLEAN || defined CRYSTUB_40_START_SEC_VAR_NO_INIT_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_VAR_NOINIT_BOOLEAN
  #undef CRYSTUB_40_START_SEC_VAR_NO_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_NOINIT_BOOLEAN || defined CRYSTUB_40_STOP_SEC_VAR_NO_INIT_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_VAR_NOINIT_BOOLEAN
  #undef CRYSTUB_40_STOP_SEC_VAR_NO_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_NOINIT_8BIT || defined CRYSTUB_40_START_SEC_VAR_NO_INIT_8)
  #undef CRYSTUB_40_START_SEC_VAR_NOINIT_8BIT
  #undef CRYSTUB_40_START_SEC_VAR_NO_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_NOINIT_8BIT || defined CRYSTUB_40_STOP_SEC_VAR_NO_INIT_8)
  #undef CRYSTUB_40_STOP_SEC_VAR_NOINIT_8BIT
  #undef CRYSTUB_40_STOP_SEC_VAR_NO_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_NOINIT_16BIT || defined CRYSTUB_40_START_SEC_VAR_NO_INIT_16)
  #undef CRYSTUB_40_START_SEC_VAR_NOINIT_16BIT
  #undef CRYSTUB_40_START_SEC_VAR_NO_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_NOINIT_16BIT || defined CRYSTUB_40_STOP_SEC_VAR_NO_INIT_16)
  #undef CRYSTUB_40_STOP_SEC_VAR_NOINIT_16BIT
  #undef CRYSTUB_40_STOP_SEC_VAR_NO_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_NOINIT_32BIT || defined CRYSTUB_40_START_SEC_VAR_NO_INIT_32)
  #undef CRYSTUB_40_START_SEC_VAR_NOINIT_32BIT
  #undef CRYSTUB_40_START_SEC_VAR_NO_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_NOINIT_32BIT || defined CRYSTUB_40_STOP_SEC_VAR_NO_INIT_32)
  #undef CRYSTUB_40_STOP_SEC_VAR_NOINIT_32BIT
  #undef CRYSTUB_40_STOP_SEC_VAR_NO_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_NOINIT_UNSPECIFIED || defined CRYSTUB_40_START_SEC_VAR_NO_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef CRYSTUB_40_START_SEC_VAR_NO_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_NOINIT_UNSPECIFIED || defined CRYSTUB_40_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef CRYSTUB_40_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_BOOLEAN || defined CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN || defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_8BIT || defined CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8 || defined CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_8)
  #undef CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_8BIT
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8
  #undef CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_8BIT || defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8 || defined CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_8)
  #undef CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_8BIT
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8
  #undef CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_16BIT || defined CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16 || defined CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_16)
  #undef CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_16BIT
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16
  #undef CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_16BIT || defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16 || defined CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_16)
  #undef CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_16BIT
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16
  #undef CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_32BIT || defined CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32 || defined CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_32)
  #undef CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_32BIT
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32
  #undef CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_32BIT || defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32 || defined CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_32)
  #undef CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_32BIT
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32
  #undef CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED || defined CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED || defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_BOOLEAN || defined CRYSTUB_40_START_SEC_VAR_FAST_INIT_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_BOOLEAN
  #undef CRYSTUB_40_START_SEC_VAR_FAST_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_BOOLEAN || defined CRYSTUB_40_STOP_SEC_VAR_FAST_INIT_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_BOOLEAN
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_8BIT || defined CRYSTUB_40_START_SEC_VAR_FAST_INIT_8)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_8BIT
  #undef CRYSTUB_40_START_SEC_VAR_FAST_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_8BIT || defined CRYSTUB_40_STOP_SEC_VAR_FAST_INIT_8)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_8BIT
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_16BIT || defined CRYSTUB_40_START_SEC_VAR_FAST_INIT_16)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_16BIT
  #undef CRYSTUB_40_START_SEC_VAR_FAST_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_16BIT || defined CRYSTUB_40_STOP_SEC_VAR_FAST_INIT_16)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_16BIT
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_32BIT || defined CRYSTUB_40_START_SEC_VAR_FAST_INIT_32)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_32BIT
  #undef CRYSTUB_40_START_SEC_VAR_FAST_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_32BIT || defined CRYSTUB_40_STOP_SEC_VAR_FAST_INIT_32)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_32BIT
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_UNSPECIFIED || defined CRYSTUB_40_START_SEC_VAR_FAST_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_UNSPECIFIED
  #undef CRYSTUB_40_START_SEC_VAR_FAST_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_UNSPECIFIED || defined CRYSTUB_40_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_UNSPECIFIED
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_BOOLEAN || defined CRYSTUB_40_START_SEC_INTERNAL_VAR_INIT_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_BOOLEAN
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_BOOLEAN || defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_BOOLEAN
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_8BIT || defined CRYSTUB_40_START_SEC_INTERNAL_VAR_INIT_8)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_8BIT
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_8BIT || defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_INIT_8)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_8BIT
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_16BIT || defined CRYSTUB_40_START_SEC_INTERNAL_VAR_INIT_16)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_16BIT
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_16BIT || defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_INIT_16)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_16BIT
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_32BIT || defined CRYSTUB_40_START_SEC_INTERNAL_VAR_INIT_32)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_32BIT
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_32BIT || defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_INIT_32)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_32BIT
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_UNSPECIFIED || defined CRYSTUB_40_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_UNSPECIFIED
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_UNSPECIFIED || defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_UNSPECIFIED
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_BOOLEAN || defined CRYSTUB_40_START_SEC_VAR_INIT_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_VAR_BOOLEAN
  #undef CRYSTUB_40_START_SEC_VAR_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_BOOLEAN || defined CRYSTUB_40_STOP_SEC_VAR_INIT_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_VAR_BOOLEAN
  #undef CRYSTUB_40_STOP_SEC_VAR_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_8BIT || defined CRYSTUB_40_START_SEC_VAR_INIT_8)
  #undef CRYSTUB_40_START_SEC_VAR_8BIT
  #undef CRYSTUB_40_START_SEC_VAR_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_8BIT || defined CRYSTUB_40_STOP_SEC_VAR_INIT_8)
  #undef CRYSTUB_40_STOP_SEC_VAR_8BIT
  #undef CRYSTUB_40_STOP_SEC_VAR_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_16BIT || defined CRYSTUB_40_START_SEC_VAR_INIT_16)
  #undef CRYSTUB_40_START_SEC_VAR_16BIT
  #undef CRYSTUB_40_START_SEC_VAR_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_16BIT || defined CRYSTUB_40_STOP_SEC_VAR_INIT_16)
  #undef CRYSTUB_40_STOP_SEC_VAR_16BIT
  #undef CRYSTUB_40_STOP_SEC_VAR_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_32BIT || defined CRYSTUB_40_START_SEC_VAR_INIT_32)
  #undef CRYSTUB_40_START_SEC_VAR_32BIT
  #undef CRYSTUB_40_START_SEC_VAR_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_32BIT || defined CRYSTUB_40_STOP_SEC_VAR_INIT_32)
  #undef CRYSTUB_40_STOP_SEC_VAR_32BIT
  #undef CRYSTUB_40_STOP_SEC_VAR_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_UNSPECIFIED || defined CRYSTUB_40_START_SEC_VAR_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_VAR_UNSPECIFIED
  #undef CRYSTUB_40_START_SEC_VAR_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_UNSPECIFIED || defined CRYSTUB_40_STOP_SEC_VAR_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_VAR_UNSPECIFIED
  #undef CRYSTUB_40_STOP_SEC_VAR_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CONST_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_CONST_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CONST_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_CONST_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CONST_8BIT || defined CRYSTUB_40_START_SEC_CONST_8)
  #undef CRYSTUB_40_START_SEC_CONST_8BIT
  #undef CRYSTUB_40_START_SEC_CONST_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CONST_8BIT || defined CRYSTUB_40_STOP_SEC_CONST_8)
  #undef CRYSTUB_40_STOP_SEC_CONST_8BIT
  #undef CRYSTUB_40_STOP_SEC_CONST_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CONST_16BIT || defined CRYSTUB_40_START_SEC_CONST_16)
  #undef CRYSTUB_40_START_SEC_CONST_16BIT
  #undef CRYSTUB_40_START_SEC_CONST_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CONST_16BIT || defined CRYSTUB_40_STOP_SEC_CONST_16)
  #undef CRYSTUB_40_STOP_SEC_CONST_16BIT
  #undef CRYSTUB_40_STOP_SEC_CONST_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CONST_32BIT || defined CRYSTUB_40_START_SEC_CONST_32)
  #undef CRYSTUB_40_START_SEC_CONST_32BIT
  #undef CRYSTUB_40_START_SEC_CONST_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CONST_32BIT || defined CRYSTUB_40_STOP_SEC_CONST_32)
  #undef CRYSTUB_40_STOP_SEC_CONST_32BIT
  #undef CRYSTUB_40_STOP_SEC_CONST_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CONST_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_CONST_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CONST_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_CONST_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CALIB_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_CALIB_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CALIB_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_CALIB_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CALIB_8BIT || defined CRYSTUB_40_START_SEC_CALIB_8)
  #undef CRYSTUB_40_START_SEC_CALIB_8BIT
  #undef CRYSTUB_40_START_SEC_CALIB_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CALIB_8BIT || defined CRYSTUB_40_STOP_SEC_CALIB_8)
  #undef CRYSTUB_40_STOP_SEC_CALIB_8BIT
  #undef CRYSTUB_40_STOP_SEC_CALIB_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CALIB_16BIT || defined CRYSTUB_40_START_SEC_CALIB_16)
  #undef CRYSTUB_40_START_SEC_CALIB_16BIT
  #undef CRYSTUB_40_START_SEC_CALIB_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CALIB_16BIT || defined CRYSTUB_40_STOP_SEC_CALIB_16)
  #undef CRYSTUB_40_STOP_SEC_CALIB_16BIT
  #undef CRYSTUB_40_STOP_SEC_CALIB_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CALIB_32BIT || defined CRYSTUB_40_START_SEC_CALIB_32)
  #undef CRYSTUB_40_START_SEC_CALIB_32BIT
  #undef CRYSTUB_40_START_SEC_CALIB_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CALIB_32BIT || defined CRYSTUB_40_STOP_SEC_CALIB_32)
  #undef CRYSTUB_40_STOP_SEC_CALIB_32BIT
  #undef CRYSTUB_40_STOP_SEC_CALIB_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CALIB_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_CALIB_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CALIB_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_CALIB_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CARTO_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_CARTO_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CARTO_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_CARTO_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CARTO_8BIT || defined CRYSTUB_40_START_SEC_CARTO_8)
  #undef CRYSTUB_40_START_SEC_CARTO_8BIT
  #undef CRYSTUB_40_START_SEC_CARTO_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CARTO_8BIT || defined CRYSTUB_40_STOP_SEC_CARTO_8)
  #undef CRYSTUB_40_STOP_SEC_CARTO_8BIT
  #undef CRYSTUB_40_STOP_SEC_CARTO_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CARTO_16BIT || defined CRYSTUB_40_START_SEC_CARTO_16)
  #undef CRYSTUB_40_START_SEC_CARTO_16BIT
  #undef CRYSTUB_40_START_SEC_CARTO_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CARTO_16BIT || defined CRYSTUB_40_STOP_SEC_CARTO_16)
  #undef CRYSTUB_40_STOP_SEC_CARTO_16BIT
  #undef CRYSTUB_40_STOP_SEC_CARTO_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CARTO_32BIT || defined CRYSTUB_40_START_SEC_CARTO_32)
  #undef CRYSTUB_40_START_SEC_CARTO_32BIT
  #undef CRYSTUB_40_START_SEC_CARTO_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CARTO_32BIT || defined CRYSTUB_40_STOP_SEC_CARTO_32)
  #undef CRYSTUB_40_STOP_SEC_CARTO_32BIT
  #undef CRYSTUB_40_STOP_SEC_CARTO_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CARTO_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_CARTO_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CARTO_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_CARTO_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_CONFIG_DATA_BOOLEAN || defined CRYSTUB_40_START_SEC_CONFIG_DATA_BOOLEAN)
  #undef CRYSTUB_40_START_CONFIG_DATA_BOOLEAN
  #undef CRYSTUB_40_START_SEC_CONFIG_DATA_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_CONFIG_DATA_BOOLEAN || defined CRYSTUB_40_STOP_SEC_CONFIG_DATA_BOOLEAN)
  #undef CRYSTUB_40_STOP_CONFIG_DATA_BOOLEAN
  #undef CRYSTUB_40_STOP_SEC_CONFIG_DATA_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_CONFIG_DATA_8BIT || defined CRYSTUB_40_START_SEC_CONFIG_DATA_8)
  #undef CRYSTUB_40_START_CONFIG_DATA_8BIT
  #undef CRYSTUB_40_START_SEC_CONFIG_DATA_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_CONFIG_DATA_8BIT || defined CRYSTUB_40_STOP_SEC_CONFIG_DATA_8)
  #undef CRYSTUB_40_STOP_CONFIG_DATA_8BIT
  #undef CRYSTUB_40_STOP_SEC_CONFIG_DATA_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_CONFIG_DATA_16BIT || defined CRYSTUB_40_START_SEC_CONFIG_DATA_16)
  #undef CRYSTUB_40_START_CONFIG_DATA_16BIT
  #undef CRYSTUB_40_START_SEC_CONFIG_DATA_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_CONFIG_DATA_16BIT || defined CRYSTUB_40_STOP_SEC_CONFIG_DATA_16)
  #undef CRYSTUB_40_STOP_CONFIG_DATA_16BIT
  #undef CRYSTUB_40_STOP_SEC_CONFIG_DATA_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_CONFIG_DATA_32BIT || defined CRYSTUB_40_START_SEC_CONFIG_DATA_32)
  #undef CRYSTUB_40_START_CONFIG_DATA_32BIT
  #undef CRYSTUB_40_START_SEC_CONFIG_DATA_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_CONFIG_DATA_32BIT || defined CRYSTUB_40_STOP_SEC_CONFIG_DATA_32)
  #undef CRYSTUB_40_STOP_CONFIG_DATA_32BIT
  #undef CRYSTUB_40_STOP_SEC_CONFIG_DATA_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_CONFIG_DATA_UNSPECIFIED || defined CRYSTUB_40_START_SEC_CONFIG_DATA_UNSPECIFIED)
  #undef CRYSTUB_40_START_CONFIG_DATA_UNSPECIFIED
  #undef CRYSTUB_40_START_SEC_CONFIG_DATA_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_CONFIG_DATA_UNSPECIFIED || defined CRYSTUB_40_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_CONFIG_DATA_UNSPECIFIED
  #undef CRYSTUB_40_STOP_SEC_CONFIG_DATA_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_VAR_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_VAR_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_CLEARED_8)
  #undef CRYSTUB_40_START_SEC_VAR_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_CLEARED_8)
  #undef CRYSTUB_40_STOP_SEC_VAR_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_CLEARED_16)
  #undef CRYSTUB_40_START_SEC_VAR_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_CLEARED_16)
  #undef CRYSTUB_40_STOP_SEC_VAR_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_CLEARED_32)
  #undef CRYSTUB_40_START_SEC_VAR_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_CLEARED_32)
  #undef CRYSTUB_40_STOP_SEC_VAR_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_VAR_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_VAR_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_POWER_ON_CLEARED_8)
  #undef CRYSTUB_40_START_SEC_VAR_POWER_ON_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_POWER_ON_CLEARED_8)
  #undef CRYSTUB_40_STOP_SEC_VAR_POWER_ON_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_POWER_ON_CLEARED_16)
  #undef CRYSTUB_40_START_SEC_VAR_POWER_ON_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_POWER_ON_CLEARED_16)
  #undef CRYSTUB_40_STOP_SEC_VAR_POWER_ON_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_POWER_ON_CLEARED_32)
  #undef CRYSTUB_40_START_SEC_VAR_POWER_ON_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_POWER_ON_CLEARED_32)
  #undef CRYSTUB_40_STOP_SEC_VAR_POWER_ON_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_NO_INIT_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_NO_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_NO_INIT_8)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_NO_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_NO_INIT_8)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_NO_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_NO_INIT_16)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_NO_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_NO_INIT_16)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_NO_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_NO_INIT_32)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_NO_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_NO_INIT_32)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_NO_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_CLEARED_8)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_CLEARED_8)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_CLEARED_16)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_CLEARED_16)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_CLEARED_32)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_CLEARED_32)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_CLEARED_8)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_CLEARED_16)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_CLEARED_32)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_INIT_8)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_INIT_8)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_INIT_16)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_INIT_16)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_INIT_32)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_INIT_32)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_NO_INIT_8)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_NO_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_NO_INIT_8)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_NO_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_NO_INIT_16)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_NO_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_NO_INIT_16)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_NO_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_NO_INIT_32)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_NO_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_NO_INIT_32)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_NO_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_CLEARED_8)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_CLEARED_8)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_CLEARED_16)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_CLEARED_16)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_CLEARED_32)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_CLEARED_32)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_INIT_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_INIT_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_INIT_8)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_INIT_8)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_INIT_16)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_INIT_16)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_INIT_32)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_INIT_32)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_INIT_8)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_INIT_16)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_INIT_32)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_NO_INIT_8)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_NO_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_NO_INIT_8)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_NO_INIT_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_NO_INIT_16)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_NO_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_NO_INIT_16)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_NO_INIT_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_NO_INIT_32)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_NO_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_NO_INIT_32)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_NO_INIT_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_CLEARED_8)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_CLEARED_8)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_CLEARED_16)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_CLEARED_16)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_CLEARED_32)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_CLEARED_32)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED)
  #undef CRYSTUB_40_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CODE_FAST)
  #undef CRYSTUB_40_START_SEC_CODE_FAST
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CODE_FAST)
  #undef CRYSTUB_40_STOP_SEC_CODE_FAST
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CODE_SLOW)
  #undef CRYSTUB_40_START_SEC_CODE_SLOW
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CODE_SLOW)
  #undef CRYSTUB_40_STOP_SEC_CODE_SLOW
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_START_SEC_CODE_LIB)
  #undef CRYSTUB_40_START_SEC_CODE_LIB
  #undef CRYSTUB_40_MEMMAP_ERROR

#elif (defined CRYSTUB_40_STOP_SEC_CODE_LIB)
  #undef CRYSTUB_40_STOP_SEC_CODE_LIB
  #undef CRYSTUB_40_MEMMAP_ERROR

#endif

#if (defined __TenDRA__)
/* turn on "no #undef" warnings again */
#pragma TenDRA error "misra98_092" warning
#pragma TenDRA error "misra04_19_6" warning
#endif

/*------------------[MemMap error checking]----------------------------------*/

#if (defined CRYSTUB_40_MEMMAP_ERROR) /* to prevent double definition */
#error CRYSTUB_40_MEMMAP_ERROR defined, wrong CryStub_40_MemMap.h usage
#endif /* if (!defined CRYSTUB_40_MEMMAP_ERROR) */

/*==================[end of file]============================================*/
