/**
 * \file
 *
 * \brief AUTOSAR Dem
 *
 * This file contains the implementation of the AUTOSAR
 * module Dem.
 *
 * \version 6.5.8
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2024 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */
#ifndef DEM_INT_ERR_ID_H
#define DEM_INT_ERR_ID_H

/* This file contains the configuration declarations of the
 * BSW and SEV Event ID symbols for AUTOSAR module Dem. */

[!AUTOSPACING!]
[!INCLUDE "../../generate_common/Dem_Include.m"!]
[!//
/*==================[inclusions]============================================*/

/*==================[macros]================================================*/

/*------------------[Events configuration]----------------------------------*/

/* !LINKSTO Dem.ASR40.SWS_Dem_00115,2 */
/* Symbolic names of configured BSW and SEV event IDs */
[!LOOP "util:distinct(node:order(DemConfigSet/eb-list::*/DemEventParameter/eb-list::*[DemEventKind != 'DEM_EVENT_KIND_SWC'], 'DemEventId'))"!]
  [!INDENT "0"!]

    [!IF "$DemRteUsage = 'true'"!]
      /* Following macro is generated by the RTE to identify if it is in synch with the current DEM configuration.
       * Furthermore, the macro is not only intended for the usage via an RTE interface but also via a c API. */
      #if (DemConf_DemEventParameter_[!"as:name(.)"!] != [!"DemEventId"!]U)
      #error Definition of macro DemConf_DemEventParameter_[!"as:name(.)"!] does not match to the DEM configuration due to RTE and DEM are out of synch. Please update the RTE based on the newest DEM BSWMD file!
      #endif
    [!ELSE!]
      #if (defined DemConf_DemEventParameter_[!"as:name(.)"!])
      #error DemConf_DemEventParameter_[!"as:name(.)"!] already defined
      #endif
      /** \brief Export symbolic name value */
      #define DemConf_DemEventParameter_[!"as:name(.)"!][!CALL "Indent", "Length" = "31 - string-length(as:name(.))"!] [!"DemEventId"!]U
    [!ENDIF!]
    #if (defined DEM_PROVIDE_LEGACY_SYMBOLIC_NAMES)
    #if (defined Dem_[!"as:name(.)"!])
    #error Dem_[!"as:name(.)"!] already defined
    #endif
    /** \brief Export symbolic name value with module abbreviation as prefix only (3.1 rev4 < AUTOSAR version <= AUTOSAR 4.0 rev2) **/
    #define Dem_[!"as:name(.)"!][!CALL "Indent", "Length" = "31 - string-length(as:name(.))"!] [!"DemEventId"!]U
    #endif /* defined DEM_PROVIDE_LEGACY_SYMBOLIC_NAMES */
  [!ENDINDENT!]
[!ENDLOOP!]

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

/*==================[internal function definitions]=========================*/

#endif /* ifndef DEM_INT_ERR_ID_H */
/*==================[end of file]===========================================*/
