/* Os_errorcodes_TRICORE.h - kernel error code translations
 *
 * This is a generated file - DO NOT EDIT
 *
 * Generated by errdb-to-c.pl on 2024-06-03 13:39
 *
 * (c) 2024 Elektrobit Automotive GmbH
*/

#if defined(OS_SID) && !defined(OS_ERRORCODES_TRICORE_H)
#define OS_ERRORCODES_TRICORE_H

#ifndef OS_SID_EC
#define OS_SID_EC OS_SID
#endif

#include <Os_error.h>


#if OS_SID_EC == OS_SID_ArchTrapHandler
#define OS_EC_OS_ERROR_ArithmeticTrap               OS_E_ARITH
#define OS_EC_OS_ERROR_MemoryProtection             OS_E_MEMPROT
#define OS_EC_OS_ERROR_NonfatalException            OS_E_EXCEPTPROT
#define OS_EC_OS_ERROR_FatalException               OS_E_PANIC
#endif

#endif
