IF "%TARGET%"=="" SET TARGET=TRICORE
IF "%DERIVATE%"=="" SET DERIVATE=TC29XT
IF "%TOOLCHAIN%"=="" SET TOOLCHAIN=tasking
IF [%TOOLPATH_COMPILER%]==[] SET TOOLPATH_COMPILER=%TOOLPATH_COMPILER_Taskingv50r2%
IF [%TRESOS_BASE%]==[] SET TRESOS_BASE=
IF [%PLUGINS_BASE%]==[] set PLUGINS_BASE=%TRESOS_BASE%\plugins
