function BAPP_outputs(varargin)
%===========$Update Time :  2025-09-11 10:09:05 $=========
disp('Loading $Id: BAPP_outputs.m  2025-09-11 10:09:05    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-09-11 10:09:05 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BAPP_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VAPP_iDCurrAct_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPP_iQCurrAct_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPP_ADCKL30_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPP_ADCKL15_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPP_uDC_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPP_RotSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPP_OilTemp_degC'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
