IF "%TARGET%"=="" SET TARGET=TRICORE
IF "%DERIVATE%"=="" SET DERIVATE=TC38XQ
IF "%SUBDERIVATE%"=="" SET SUBDERIVATE=TC387
IF "%TOOLCHAIN%"=="" SET TOOLCHAIN=tasking
IF [%TOOLPATH_COMPILER%]==[] SET TOOLPATH_COMPILER=C:\TASKING\TriCore_v6.3r1\ctc

IF [%TRESOS_BASE%]==[] SET TRESOS_BASE=%PROJECT_ROOT%/tresos
IF [%PLUGINS_BASE%]==[] SET PLUGINS_BASE=%TRESOS_BASE%/plugins
