/* kern-errext-CheckIsrMemoryAccess.c - kernel error database for STATUS=EXTENDED
 *
 * This is a generated file - DO NOT EDIT
 *
 * Generated by errdb-to-c.pl on 2024-06-03 13:39
 *
 * (c) 2024 Elektrobit Automotive GmbH
*/

#include <Os_kernel.h>

#if (OS_KERNEL_TYPE != OS_MICROKERNEL)

#include <Os_error.h>

#include <memmap/Os_mm_const_begin.h>
static const os_errorentry_t OS_errtblCheckIsrMemoryAccess[4] =
{
  {
    OS_E_CALLLEVEL,
    OS_ERROR_WrongContext,
    OS_ACTION_RETURN|OS_ACTION_ERRORHOOK_EB
  },
  {
    OS_E_INTDISABLE,
    OS_ERROR_InterruptDisabled,
    OS_ACTION_RETURN|OS_ACTION_ERRORHOOK_EB
  },
  {
    OS_E_ID,
    OS_ERROR_InvalidIsrId,
    OS_ACTION_RETURN|OS_ACTION_ERRORHOOK_EB
  },
  {
    OS_E_VALUE,
    OS_ERROR_InvalidMemoryRegion,
    OS_ACTION_RETURN|OS_ACTION_ERRORHOOK_EB
  }
};

const os_serviceinfo_t OS_svc_CheckIsrMemoryAccess =
{
    OS_errtblCheckIsrMemoryAccess,
    OS_SID_CheckIsrMemoryAccess,
    4
};
#include <memmap/Os_mm_const_end.h>

#endif /* (OS_KERNEL_TYPE != OS_MICROKERNEL) */

