/**EB_Automotive_C_Source_File */

#ifndef COMM_STUBCFG_H
#define COMM_STUBCFG_H

/*
   Configuration file for the ComM code stub
   The following symbols have the potential to change the behavior of the stub:
   ============================================================================

   - EBSTUBS_FUNCTION_TRACE_COMM
        Values: STD_ON (default)/STD_OFF
        En-/Disables function tracing feature module-wide if the more specific
        symbols for the single API functions are not defined.
        Also defines the default values for the following symbols if they are not set.
        If function tracing is disabled on global level this symbol has no effect.

   - EBSTUBS_FUNCTION_TRACE_COMM_[fctname]
        Values: STD_ON/STD_OFF Default: EBSTUBS_FUNCTION_TRACE_COMM
        En-/Disables function tracing feature for a single API function.
        If function tracing is disabled on global level this symbol has no effect.
        Defining a value overrules the behavior set by the module-wide symbol.
        In detail the symbols are:
      * EBSTUBS_FUNCTION_TRACE_COMM_BUSSM_BUSSLEEPMODE
      * EBSTUBS_FUNCTION_TRACE_COMM_BUSSM_MODEINDICATION
      * EBSTUBS_FUNCTION_TRACE_COMM_COMMUNICATIONALLOWED
      * EBSTUBS_FUNCTION_TRACE_COMM_DCM_ACTIVEDIAGNOSTIC
      * EBSTUBS_FUNCTION_TRACE_COMM_DCM_INACTIVEDIAGNOSTIC
      * EBSTUBS_FUNCTION_TRACE_COMM_DEINIT
      * EBSTUBS_FUNCTION_TRACE_COMM_ECUM_PNCWAKEUPINDICATION
      * EBSTUBS_FUNCTION_TRACE_COMM_ECUM_WAKEUPINDICATION
      * EBSTUBS_FUNCTION_TRACE_COMM_GETCURRENTCOMMODE
      * EBSTUBS_FUNCTION_TRACE_COMM_GETINHIBITIONSTATUS
      * EBSTUBS_FUNCTION_TRACE_COMM_GETMAXCOMMODE
      * EBSTUBS_FUNCTION_TRACE_COMM_GETREQUESTEDCOMMODE
      * EBSTUBS_FUNCTION_TRACE_COMM_GETSTATE
      * EBSTUBS_FUNCTION_TRACE_COMM_GETSTATUS
      * EBSTUBS_FUNCTION_TRACE_COMM_GETVERSIONINFO
      * EBSTUBS_FUNCTION_TRACE_COMM_INIT
      * EBSTUBS_FUNCTION_TRACE_COMM_ISVALIDCONFIG
      * EBSTUBS_FUNCTION_TRACE_COMM_LIMITCHANNELTONOCOMMODE
      * EBSTUBS_FUNCTION_TRACE_COMM_LIMITECUTONOCOMMODE
      * EBSTUBS_FUNCTION_TRACE_COMM_NM_BUSSLEEPMODE
      * EBSTUBS_FUNCTION_TRACE_COMM_NM_FORWARDSYNCHRONIZEDPNCSHUTDOWN
      * EBSTUBS_FUNCTION_TRACE_COMM_NM_NETWORKMODE
      * EBSTUBS_FUNCTION_TRACE_COMM_NM_NETWORKSTARTINDICATION
      * EBSTUBS_FUNCTION_TRACE_COMM_NM_PREPAREBUSSLEEPMODE
      * EBSTUBS_FUNCTION_TRACE_COMM_NM_RESTARTINDICATION
      * EBSTUBS_FUNCTION_TRACE_COMM_PREVENTWAKEUP
      * EBSTUBS_FUNCTION_TRACE_COMM_READINHIBITCOUNTER
      * EBSTUBS_FUNCTION_TRACE_COMM_REQUESTCOMMODE
      * EBSTUBS_FUNCTION_TRACE_COMM_RESETINHIBITCOUNTER
      * EBSTUBS_FUNCTION_TRACE_COMM_SETECUGROUPCLASSIFICATION

   Note: A function is only written to the function tracing buffer if:
         The global symbol EBSTUBS_FUNCTION_TRACE is enabled AND
         the symbol of the relevant function EBSTUBS_FUNCTION_TRACE_[fctname] is enabled.

     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

   - EBSTUBS_FUNCENABLED_COMM
        Values: STD_ON (default)/STD_OFF
        En-/Disables all API functions of a single code stub at pre-compile time.
        Also defines the default values for the following symbols if they are not set.

   - EBSTUBS_FUNCENABLED_[FCTNAME]
        Values: STD_ON/STD_OFF Default: EBSTUBS_FUNCENABLED_COMM
        En-/Disables a single API function at pre-compile time.
        Defining a value overrules the behavior set by the module-wide symbol.
        In detail the symbols are:
      * EBSTUBS_FUNCENABLED_COMM_BUSSM_BUSSLEEPMODE
      * EBSTUBS_FUNCENABLED_COMM_BUSSM_MODEINDICATION
      * EBSTUBS_FUNCENABLED_COMM_COMMUNICATIONALLOWED
      * EBSTUBS_FUNCENABLED_COMM_DCM_ACTIVEDIAGNOSTIC
      * EBSTUBS_FUNCENABLED_COMM_DCM_INACTIVEDIAGNOSTIC
      * EBSTUBS_FUNCENABLED_COMM_DEINIT
      * EBSTUBS_FUNCENABLED_COMM_ECUM_PNCWAKEUPINDICATION
      * EBSTUBS_FUNCENABLED_COMM_ECUM_WAKEUPINDICATION
      * EBSTUBS_FUNCENABLED_COMM_GETCURRENTCOMMODE
      * EBSTUBS_FUNCENABLED_COMM_GETINHIBITIONSTATUS
      * EBSTUBS_FUNCENABLED_COMM_GETMAXCOMMODE
      * EBSTUBS_FUNCENABLED_COMM_GETREQUESTEDCOMMODE
      * EBSTUBS_FUNCENABLED_COMM_GETSTATE
      * EBSTUBS_FUNCENABLED_COMM_GETSTATUS
      * EBSTUBS_FUNCENABLED_COMM_GETVERSIONINFO
      * EBSTUBS_FUNCENABLED_COMM_INIT
      * EBSTUBS_FUNCENABLED_COMM_ISVALIDCONFIG
      * EBSTUBS_FUNCENABLED_COMM_LIMITCHANNELTONOCOMMODE
      * EBSTUBS_FUNCENABLED_COMM_LIMITECUTONOCOMMODE
      * EBSTUBS_FUNCENABLED_COMM_NM_BUSSLEEPMODE
      * EBSTUBS_FUNCENABLED_COMM_NM_FORWARDSYNCHRONIZEDPNCSHUTDOWN
      * EBSTUBS_FUNCENABLED_COMM_NM_NETWORKMODE
      * EBSTUBS_FUNCENABLED_COMM_NM_NETWORKSTARTINDICATION
      * EBSTUBS_FUNCENABLED_COMM_NM_PREPAREBUSSLEEPMODE
      * EBSTUBS_FUNCENABLED_COMM_NM_RESTARTINDICATION
      * EBSTUBS_FUNCENABLED_COMM_PREVENTWAKEUP
      * EBSTUBS_FUNCENABLED_COMM_READINHIBITCOUNTER
      * EBSTUBS_FUNCENABLED_COMM_REQUESTCOMMODE
      * EBSTUBS_FUNCENABLED_COMM_RESETINHIBITCOUNTER
      * EBSTUBS_FUNCENABLED_COMM_SETECUGROUPCLASSIFICATION

     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

   - EBSTUBS_MAX_CALLS_COMM
        Values: [numeric value] Default: 1
        Defines the number of API calls for which the code stubs can store the function arguments.
        Also defines the default values for the following symbols if they are not set.

   - EBSTUBS_MAX_CALLS_COMM_[fctname]
        Values: [numeric value] Default: EBSTUBS_MAX_CALLS_COMM
        Defines the number of API calls for which a specific function can.
        store the function arguments.
        Defining a value overrules the behavior set by the module-wide symbol.
        In detail the symbols are:
      * EBSTUBS_MAX_CALLS_COMM_BUSSM_BUSSLEEPMODE
      * EBSTUBS_MAX_CALLS_COMM_BUSSM_MODEINDICATION
      * EBSTUBS_MAX_CALLS_COMM_COMMUNICATIONALLOWED
      * EBSTUBS_MAX_CALLS_COMM_DCM_ACTIVEDIAGNOSTIC
      * EBSTUBS_MAX_CALLS_COMM_DCM_INACTIVEDIAGNOSTIC
      * EBSTUBS_MAX_CALLS_COMM_DEINIT
      * EBSTUBS_MAX_CALLS_COMM_ECUM_PNCWAKEUPINDICATION
      * EBSTUBS_MAX_CALLS_COMM_ECUM_WAKEUPINDICATION
      * EBSTUBS_MAX_CALLS_COMM_GETCURRENTCOMMODE
      * EBSTUBS_MAX_CALLS_COMM_GETINHIBITIONSTATUS
      * EBSTUBS_MAX_CALLS_COMM_GETMAXCOMMODE
      * EBSTUBS_MAX_CALLS_COMM_GETREQUESTEDCOMMODE
      * EBSTUBS_MAX_CALLS_COMM_GETSTATE
      * EBSTUBS_MAX_CALLS_COMM_GETSTATUS
      * EBSTUBS_MAX_CALLS_COMM_GETVERSIONINFO
      * EBSTUBS_MAX_CALLS_COMM_INIT
      * EBSTUBS_MAX_CALLS_COMM_ISVALIDCONFIG
      * EBSTUBS_MAX_CALLS_COMM_LIMITCHANNELTONOCOMMODE
      * EBSTUBS_MAX_CALLS_COMM_LIMITECUTONOCOMMODE
      * EBSTUBS_MAX_CALLS_COMM_NM_BUSSLEEPMODE
      * EBSTUBS_MAX_CALLS_COMM_NM_FORWARDSYNCHRONIZEDPNCSHUTDOWN
      * EBSTUBS_MAX_CALLS_COMM_NM_NETWORKMODE
      * EBSTUBS_MAX_CALLS_COMM_NM_NETWORKSTARTINDICATION
      * EBSTUBS_MAX_CALLS_COMM_NM_PREPAREBUSSLEEPMODE
      * EBSTUBS_MAX_CALLS_COMM_NM_RESTARTINDICATION
      * EBSTUBS_MAX_CALLS_COMM_PREVENTWAKEUP
      * EBSTUBS_MAX_CALLS_COMM_READINHIBITCOUNTER
      * EBSTUBS_MAX_CALLS_COMM_REQUESTCOMMODE
      * EBSTUBS_MAX_CALLS_COMM_RESETINHIBITCOUNTER
      * EBSTUBS_MAX_CALLS_COMM_SETECUGROUPCLASSIFICATION
*/

#endif /* COMM_STUBCFG_H */
