/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2020 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains an Rte component template / example code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.3.14
 * on Fri Apr 03 02:13:26 EEST 2020. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#include <Rte_SWC_Secured.h>

/* ==================[Definition of functions with external linkage]========== */
/* ------------------------[runnable entity skeletons]------------------------ */
FUNC(void, RTE_CODE) SWC_Secured_Data_Received (void)
{
  uint8 arg_Read_data;
  Std_ReturnType ret_Read;
  uint8 arg_IWrite_data = 0U;
  P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) ret_IWriteRef;

  (void)ret_Read;
  ret_Read = Rte_Read_R_SecuredData_CounterValue(&arg_Read_data);
  Rte_IWrite_UpdateSecureData_P_SecuredData_CounterValue(arg_IWrite_data);
  (void)ret_IWriteRef;
  ret_IWriteRef = Rte_IWriteRef_UpdateSecureData_P_SecuredData_CounterValue();

} /* FUNC(void, RTE_CODE) SWC_Secured_Data_Received (void) */

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------
  ------------------------[per instance memory API]--------------------------
 */

/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
