/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2018 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains an Rte component template / example code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.2.19
 * on Mon Jul 02 14:12:39 EEST 2018. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#include <Rte_ServiceSwComponentDcm.h>

/* ==================[Definition of functions with external linkage]========== */
/* ------------------------[runnable entity skeletons]------------------------ */
FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_SecurityAccess_Level_1_GetSeed (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) SecurityAccessDataRecord, Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Seed, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  /* suppress compiler warnings about unused arguments */
  (void)SecurityAccessDataRecord;
  (void)OpStatus;
  (void)Seed;
  (void)*ErrorCode;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_SecurityAccess_Level_1_GetSeed (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) SecurityAccessDataRecord, Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Seed, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode) */

FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_SecurityAccess_Level_1_CompareKey (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Key, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  /* suppress compiler warnings about unused arguments */
  (void)Key;
  (void)OpStatus;
  (void)*ErrorCode;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_SecurityAccess_Level_1_CompareKey (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Key, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode) */

FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_SecurityAccess_Level_3_GetSeed (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) SecurityAccessDataRecord, Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Seed, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  /* suppress compiler warnings about unused arguments */
  (void)SecurityAccessDataRecord;
  (void)OpStatus;
  (void)Seed;
  (void)*ErrorCode;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_SecurityAccess_Level_3_GetSeed (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) SecurityAccessDataRecord, Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Seed, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode) */

FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_SecurityAccess_Level_3_CompareKey (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Key, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  /* suppress compiler warnings about unused arguments */
  (void)Key;
  (void)OpStatus;
  (void)*ErrorCode;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_SecurityAccess_Level_3_CompareKey (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Key, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode) */

FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_ServiceRequestManufacturerNotification_DcmDslServiceRequestManufacturerNotification_0_Indication (uint8 SID, P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) RequestData, uint16 DataSize, uint8 ReqType, uint16 SourceAddress, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  /* suppress compiler warnings about unused arguments */
  (void)SID;
  (void)RequestData;
  (void)DataSize;
  (void)ReqType;
  (void)SourceAddress;
  (void)*ErrorCode;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_ServiceRequestManufacturerNotification_DcmDslServiceRequestManufacturerNotification_0_Indication (uint8 SID, P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) RequestData, uint16 DataSize, uint8 ReqType, uint16 SourceAddress, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode) */

FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_ServiceRequestManufacturerNotification_DcmDslServiceRequestManufacturerNotification_0_Confirmation (uint8 SID, uint8 ReqType, uint16 SourceAddress, Dcm_ConfirmationStatusType ConfirmationStatus)
{
  /* suppress compiler warnings about unused arguments */
  (void)SID;
  (void)ReqType;
  (void)SourceAddress;
  (void)ConfirmationStatus;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_ServiceRequestManufacturerNotification_DcmDslServiceRequestManufacturerNotification_0_Confirmation (uint8 SID, uint8 ReqType, uint16 SourceAddress, Dcm_ConfirmationStatusType ConfirmationStatus) */

FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_ServiceRequestSupplierNotification_DcmDslServiceRequestSupplierNotification_0_Indication (uint8 SID, P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) RequestData, uint16 DataSize, uint8 ReqType, uint16 SourceAddress, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  /* suppress compiler warnings about unused arguments */
  (void)SID;
  (void)RequestData;
  (void)DataSize;
  (void)ReqType;
  (void)SourceAddress;
  (void)*ErrorCode;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_ServiceRequestSupplierNotification_DcmDslServiceRequestSupplierNotification_0_Indication (uint8 SID, P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) RequestData, uint16 DataSize, uint8 ReqType, uint16 SourceAddress, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode) */

FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_ServiceRequestSupplierNotification_DcmDslServiceRequestSupplierNotification_0_Confirmation (uint8 SID, uint8 ReqType, uint16 SourceAddress, Dcm_ConfirmationStatusType ConfirmationStatus)
{
  /* suppress compiler warnings about unused arguments */
  (void)SID;
  (void)ReqType;
  (void)SourceAddress;
  (void)ConfirmationStatus;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_ServiceRequestSupplierNotification_DcmDslServiceRequestSupplierNotification_0_Confirmation (uint8 SID, uint8 ReqType, uint16 SourceAddress, Dcm_ConfirmationStatusType ConfirmationStatus) */

FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_RoutineServices_DIAGNOSTIC_LOOPBACK_Start (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) dataIn0, Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) currentDataLength, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  uint16 iLoop;
  uint16 bytesToCopy = *currentDataLength;
  /* suppress compiler warnings about unused arguments */
  (void)OpStatus;
  (void)*ErrorCode;
  for( iLoop=0; iLoop<bytesToCopy; iLoop++ )
   {
      dataOut0[iLoop] = dataIn0[iLoop];
   }
   *currentDataLength = bytesToCopy;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_RoutineServices_DIAGNOSTIC_LOOPBACK_Start (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) dataIn0, Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) currentDataLength, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode) */

FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_RoutineServices_DIAGNOSTIC_TRIGGER_DTC_Start (uint8 dataIn0, Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode)
{
  Dem_EventStatusType arg_Call_EventStatus = 0U;
  Std_ReturnType ret_Call;

  ret_Call = Rte_Call_DTC_0x000001_Event_SetEventStatus(1u);
  /* suppress compiler warnings about unused arguments */
  (void)dataIn0;
  (void)OpStatus;
  *dataOut0 = ret_Call;
  (void)*ErrorCode;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDcm_RoutineServices_DIAGNOSTIC_TRIGGER_DTC_Start (uint8 dataIn0, Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode) */

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------
  ------------------------[per instance memory API]--------------------------
 */

/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
