/* TRICORE-user-returnfromcall.s
 *
 * This file contains the system function OS_UserReturnFromCall()
 * Generated by the makesc.pl script
 *
 * Copyright Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
*/
#ifndef OS_ASM
#define OS_ASM
#endif

#include <Os_asm_common.h>
#if (OS_KERNEL_TYPE == OS_SYSTEM_CALL)

#include <Os_tool.h>
#include <Os_syscalls.h>

	_TEXT
	_GLOBAL	OS_UserReturnFromCall
	_GTYPE(OS_UserReturnFromCall,@function)
	_GLOBAL	__callee.OS_UserReturnFromCall.da.v.v
	_GTYPE(__callee.OS_UserReturnFromCall.da.v.v,@function)

/*!
 *	OS_UserReturnFromCall()
 *
 *	This routine makes the system call to OS_SC_ReturnFromCall
*/

_TTYPE(OS_UserReturnFromCall,FUNC)
_TTYPE(__callee.OS_UserReturnFromCall.da.v.v,FUNC)

	syscall	_IMM(#,OS_SC_ReturnFromCall)
	ret

#endif /* (OS_KERNEL_TYPE == OS_SYSTEM_CALL) */

/* Editor settings - DO NOT DELETE
 * vi:set ts=4:
*/
