/* TRICORE-user-checkisrmemoryaccess.s
 *
 * This file contains the system function OS_UserCheckIsrMemoryAccess()
 * Generated by the makesc.pl script
 *
 * Copyright Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
*/
#ifndef OS_ASM
#define OS_ASM
#endif

#include <Os_asm_common.h>
#if (OS_KERNEL_TYPE == OS_SYSTEM_CALL)

#include <Os_tool.h>
#include <Os_syscalls.h>

	_TEXT
	_GLOBAL	OS_UserCheckIsrMemoryAccess
	_GTYPE(OS_UserCheckIsrMemoryAccess,@function)
	_GLOBAL	__callee.OS_UserCheckIsrMemoryAccess.da.i.ipi
	_GTYPE(__callee.OS_UserCheckIsrMemoryAccess.da.i.ipi,@function)

/*!
 *	OS_UserCheckIsrMemoryAccess()
 *
 *	This routine makes the system call to OS_SC_CheckIsrMemoryAccess
*/

_TTYPE(OS_UserCheckIsrMemoryAccess,FUNC)
_TTYPE(__callee.OS_UserCheckIsrMemoryAccess.da.i.ipi,FUNC)

	syscall	_IMM(#,OS_SC_CheckIsrMemoryAccess)
	ret

#endif /* (OS_KERNEL_TYPE == OS_SYSTEM_CALL) */

/* Editor settings - DO NOT DELETE
 * vi:set ts=4:
*/
