/* TRICORE-user-shutdownos.s
 *
 * This file contains the system function OS_UserShutdownOs()
 * Generated by the makesc.pl script
 *
 * Copyright Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
*/
#ifndef OS_ASM
#define OS_ASM
#endif

#include <Os_asm_common.h>
#if (OS_KERNEL_TYPE == OS_SYSTEM_CALL)

#include <Os_tool.h>
#include <Os_syscalls.h>

	_TEXT
	_GLOBAL	OS_UserShutdownOs
	_GTYPE(OS_UserShutdownOs,@function)
	_GLOBAL	__callee.OS_UserShutdownOs.da.v.i
	_GTYPE(__callee.OS_UserShutdownOs.da.v.i,@function)

/*!
 *	OS_UserShutdownOs()
 *
 *	This routine makes the system call to OS_SC_ShutdownOs
*/

_TTYPE(OS_UserShutdownOs,FUNC)
_TTYPE(__callee.OS_UserShutdownOs.da.v.i,FUNC)

	syscall	_IMM(#,OS_SC_ShutdownOs)
	ret

#endif /* (OS_KERNEL_TYPE == OS_SYSTEM_CALL) */

/* Editor settings - DO NOT DELETE
 * vi:set ts=4:
*/
