/* TRICORE-user-getactiveapplicationmode.s
 *
 * This file contains the system function OS_UserGetActiveApplicationMode()
 * Generated by the makesc.pl script
 *
 * Copyright Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
*/
#ifndef OS_ASM
#define OS_ASM
#endif

#include <Os_asm_common.h>
#if (OS_KERNEL_TYPE == OS_SYSTEM_CALL)

#include <Os_tool.h>
#include <Os_syscalls.h>

	_TEXT
	_GLOBAL	OS_UserGetActiveApplicationMode
	_GTYPE(OS_UserGetActiveApplicationMode,@function)
	_GLOBAL	__callee.OS_UserGetActiveApplicationMode.da.i.v
	_GTYPE(__callee.OS_UserGetActiveApplicationMode.da.i.v,@function)

/*!
 *	OS_UserGetActiveApplicationMode()
 *
 *	This routine makes the system call to OS_SC_GetActiveApplicationMode
*/

_TTYPE(OS_UserGetActiveApplicationMode,FUNC)
_TTYPE(__callee.OS_UserGetActiveApplicationMode.da.i.v,FUNC)

	syscall	_IMM(#,OS_SC_GetActiveApplicationMode)
	ret

#endif /* (OS_KERNEL_TYPE == OS_SYSTEM_CALL) */

/* Editor settings - DO NOT DELETE
 * vi:set ts=4:
*/
