/* TRICORE-user-setabsalarm.s
 *
 * This file contains the system function OS_UserSetAbsAlarm()
 * Generated by the makesc.pl script
 *
 * Copyright Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
*/
#ifndef OS_ASM
#define OS_ASM
#endif

#include <Os_asm_common.h>
#if (OS_KERNEL_TYPE == OS_SYSTEM_CALL)

#include <Os_tool.h>
#include <Os_syscalls.h>

	_TEXT
	_GLOBAL	OS_UserSetAbsAlarm
	_GTYPE(OS_UserSetAbsAlarm,@function)
	_GLOBAL	__callee.OS_UserSetAbsAlarm.da.i.iii
	_GTYPE(__callee.OS_UserSetAbsAlarm.da.i.iii,@function)

/*!
 *	OS_UserSetAbsAlarm()
 *
 *	This routine makes the system call to OS_SC_SetAbsAlarm
*/

_TTYPE(OS_UserSetAbsAlarm,FUNC)
_TTYPE(__callee.OS_UserSetAbsAlarm.da.i.iii,FUNC)

	syscall	_IMM(#,OS_SC_SetAbsAlarm)
	ret

#endif /* (OS_KERNEL_TYPE == OS_SYSTEM_CALL) */

/* Editor settings - DO NOT DELETE
 * vi:set ts=4:
*/
