/* TRICORE-user-trytogetspinlock.s
 *
 * This file contains the system function OS_UserTryToGetSpinlock()
 * Generated by the makesc.pl script
 *
 * Copyright Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
*/
#ifndef OS_ASM
#define OS_ASM
#endif

#include <Os_asm_common.h>
#if (OS_KERNEL_TYPE == OS_SYSTEM_CALL)

#include <Os_tool.h>
#include <Os_syscalls.h>

	_TEXT
	_GLOBAL	OS_UserTryToGetSpinlock
	_GTYPE(OS_UserTryToGetSpinlock,@function)
	_GLOBAL	__callee.OS_UserTryToGetSpinlock.da.i.ip
	_GTYPE(__callee.OS_UserTryToGetSpinlock.da.i.ip,@function)

/*!
 *	OS_UserTryToGetSpinlock()
 *
 *	This routine makes the system call to OS_SC_TryToGetSpinlock
*/

_TTYPE(OS_UserTryToGetSpinlock,FUNC)
_TTYPE(__callee.OS_UserTryToGetSpinlock.da.i.ip,FUNC)

	syscall	_IMM(#,OS_SC_TryToGetSpinlock)
	ret

#endif /* (OS_KERNEL_TYPE == OS_SYSTEM_CALL) */

/* Editor settings - DO NOT DELETE
 * vi:set ts=4:
*/
