/* TRICORE-user-checktaskmemoryaccess.s
 *
 * This file contains the system function OS_UserCheckTaskMemoryAccess()
 * Generated by the makesc.pl script
 *
 * Copyright Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
*/
#ifndef OS_ASM
#define OS_ASM
#endif

#include <Os_asm_common.h>
#if (OS_KERNEL_TYPE == OS_SYSTEM_CALL)

#include <Os_tool.h>
#include <Os_syscalls.h>

	_TEXT
	_GLOBAL	OS_UserCheckTaskMemoryAccess
	_GTYPE(OS_UserCheckTaskMemoryAccess,@function)
	_GLOBAL	__callee.OS_UserCheckTaskMemoryAccess.da.i.ipi
	_GTYPE(__callee.OS_UserCheckTaskMemoryAccess.da.i.ipi,@function)

/*!
 *	OS_UserCheckTaskMemoryAccess()
 *
 *	This routine makes the system call to OS_SC_CheckTaskMemoryAccess
*/

_TTYPE(OS_UserCheckTaskMemoryAccess,FUNC)
_TTYPE(__callee.OS_UserCheckTaskMemoryAccess.da.i.ipi,FUNC)

	syscall	_IMM(#,OS_SC_CheckTaskMemoryAccess)
	ret

#endif /* (OS_KERNEL_TYPE == OS_SYSTEM_CALL) */

/* Editor settings - DO NOT DELETE
 * vi:set ts=4:
*/
