/* TRICORE-errext-ArchTrapHandler.c - kernel error database for STATUS=EXTENDED
 *
 * This is a generated file - DO NOT EDIT
 *
 * Generated by errdb-to-c.pl on 2024-06-03 13:39
 *
 * (c) 2024 Elektrobit Automotive GmbH
*/

#include <Os_kernel.h>

#if (OS_KERNEL_TYPE != OS_MICROKERNEL)

#include <Os_error.h>

#include <memmap/Os_mm_const_begin.h>
static const os_errorentry_t OS_errtblArchTrapHandler[4] =
{
  {
    OS_E_ARITH,
    OS_ERROR_ArithmeticTrap,
    OS_ACTION_KILL|OS_ACTION_ERRORHOOK_APP|OS_ACTION_ERRORHOOK
  },
  {
    OS_E_MEMPROT,
    OS_ERROR_MemoryProtection,
    OS_ACTION_QUARANTINE|OS_ACTION_PROTECTIONHOOK
  },
  {
    OS_E_EXCEPTPROT,
    OS_ERROR_NonfatalException,
    OS_ACTION_QUARANTINE|OS_ACTION_PROTECTIONHOOK
  },
  {
    OS_E_PANIC,
    OS_ERROR_FatalException,
    OS_ACTION_SHUTDOWN|OS_ACTION_ERRORHOOK
  }
};

const os_serviceinfo_t OS_svc_ArchTrapHandler =
{
    OS_errtblArchTrapHandler,
    OS_SID_ArchTrapHandler,
    4
};
#include <memmap/Os_mm_const_end.h>

#endif /* (OS_KERNEL_TYPE != OS_MICROKERNEL) */

