/* TRICORE-user-gettaskid.s
 *
 * This file contains the system function OS_UserGetTaskId()
 * Generated by the makesc.pl script
 *
 * Copyright Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
*/
#ifndef OS_ASM
#define OS_ASM
#endif

#include <Os_asm_common.h>
#if (OS_KERNEL_TYPE == OS_SYSTEM_CALL)

#include <Os_tool.h>
#include <Os_syscalls.h>

	_TEXT
	_GLOBAL	OS_UserGetTaskId
	_GTYPE(OS_UserGetTaskId,@function)
	_GLOBAL	__callee.OS_UserGetTaskId.da.i.p
	_GTYPE(__callee.OS_UserGetTaskId.da.i.p,@function)

/*!
 *	OS_UserGetTaskId()
 *
 *	This routine makes the system call to OS_SC_GetTaskId
*/

_TTYPE(OS_UserGetTaskId,FUNC)
_TTYPE(__callee.OS_UserGetTaskId.da.i.p,FUNC)

	syscall	_IMM(#,OS_SC_GetTaskId)
	ret

#endif /* (OS_KERNEL_TYPE == OS_SYSTEM_CALL) */

/* Editor settings - DO NOT DELETE
 * vi:set ts=4:
*/
