/* TRICORE-user-taskreturn.s
 *
 * This file contains the system function OS_UserTaskReturn()
 * Generated by the makesc.pl script
 *
 * Copyright Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
*/
#ifndef OS_ASM
#define OS_ASM
#endif

#include <Os_asm_common.h>
#if (OS_KERNEL_TYPE == OS_SYSTEM_CALL)

#include <Os_tool.h>
#include <Os_syscalls.h>

	_TEXT
	_GLOBAL	OS_UserTaskReturn
	_GTYPE(OS_UserTaskReturn,@function)
	_GLOBAL	__callee.OS_UserTaskReturn.da.v.v
	_GTYPE(__callee.OS_UserTaskReturn.da.v.v,@function)

/*!
 *	OS_UserTaskReturn()
 *
 *	This routine makes the system call to OS_SC_TaskReturn
*/

_TTYPE(OS_UserTaskReturn,FUNC)
_TTYPE(__callee.OS_UserTaskReturn.da.v.v,FUNC)

	syscall	_IMM(#,OS_SC_TaskReturn)
	ret

#endif /* (OS_KERNEL_TYPE == OS_SYSTEM_CALL) */

/* Editor settings - DO NOT DELETE
 * vi:set ts=4:
*/
