/* TRICORE-user-iocwrite.s
 *
 * This file contains the system function OS_UserIocWrite()
 * Generated by the makesc.pl script
 *
 * Copyright Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
*/
#ifndef OS_ASM
#define OS_ASM
#endif

#include <Os_asm_common.h>
#if (OS_KERNEL_TYPE == OS_SYSTEM_CALL)

#include <Os_tool.h>
#include <Os_syscalls.h>

	_TEXT
	_GLOBAL	OS_UserIocWrite
	_GTYPE(OS_UserIocWrite,@function)
	_GLOBAL	__callee.OS_UserIocWrite.da.i.ip
	_GTYPE(__callee.OS_UserIocWrite.da.i.ip,@function)

/*!
 *	OS_UserIocWrite()
 *
 *	This routine makes the system call to OS_SC_IocWrite
*/

_TTYPE(OS_UserIocWrite,FUNC)
_TTYPE(__callee.OS_UserIocWrite.da.i.ip,FUNC)

	syscall	_IMM(#,OS_SC_IocWrite)
	ret

#endif /* (OS_KERNEL_TYPE == OS_SYSTEM_CALL) */

/* Editor settings - DO NOT DELETE
 * vi:set ts=4:
*/
