/* TRICORE-user-suspendinterrupts.s
 *
 * This file contains the system function OS_UserSuspendInterrupts()
 * Generated by the makesc.pl script
 *
 * Copyright Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
*/
#ifndef OS_ASM
#define OS_ASM
#endif

#include <Os_asm_common.h>
#if (OS_KERNEL_TYPE == OS_SYSTEM_CALL)

#include <Os_tool.h>
#include <Os_syscalls.h>

	_TEXT
	_GLOBAL	OS_UserSuspendInterrupts
	_GTYPE(OS_UserSuspendInterrupts,@function)
	_GLOBAL	__callee.OS_UserSuspendInterrupts.da.v.i
	_GTYPE(__callee.OS_UserSuspendInterrupts.da.v.i,@function)

/*!
 *	OS_UserSuspendInterrupts()
 *
 *	This routine makes the system call to OS_SC_SuspendInterrupts
*/

_TTYPE(OS_UserSuspendInterrupts,FUNC)
_TTYPE(__callee.OS_UserSuspendInterrupts.da.v.i,FUNC)

	syscall	_IMM(#,OS_SC_SuspendInterrupts)
	ret

#endif /* (OS_KERNEL_TYPE == OS_SYSTEM_CALL) */

/* Editor settings - DO NOT DELETE
 * vi:set ts=4:
*/
