function BINP_CAN3_outputs(varargin)
%===========$Update Time :  2025-09-12 09:35:07 $=========
disp('Loading $Id: BINP_CAN3_outputs.m  2025-09-12 09:35:07    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2025-09-12 09:35:07 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_CAN3_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CANMsgValidBMS1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidBMS6_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidFD3C1000_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidFD3VCU1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidFD3VCU2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidFD3VCU5_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidGW3CE1000_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMS1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMS1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBattVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMS6CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMS6RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBContactorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BatteryMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrCoolantflow_Lpmin'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrCoolanttemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ActiveDischReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CSVCU1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PwrSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RCVCU1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ShiftGearPosn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CSVCU2CAN1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RCVCU2CAN1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrActvDmpDisabReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUEnaReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FDCVCURrSpdMaxReq_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FDCVCURrSpdMinReq_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FDCVCURrTMCtrlModeReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FDCVCURrTMSpdReq_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FDCVCURrTMTqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FDCVCURrTqMaxReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FDCVCURrTqMinReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeDay_DAY'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeHour_hr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeMinute_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeMonth_MONTH'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeSecond_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_VehSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
