function BHAL_CAN3_outputs(varargin)
%===========$Update Time :  2025-09-12 09:32:07 $=========
disp('Loading $Id: BHAL_CAN3_outputs.m  2025-09-12 09:32:07    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2025-09-12 09:32:07 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_CAN3_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_CANMsgInvalidBMS1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMS1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMS1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBattVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidBMS6_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMS6CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMS6RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBContactorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidFD3C1000_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BatteryMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrCoolantflow_Lpmin'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrCoolanttemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidFD3VCU1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ActiveDischReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CSVCU1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PwrSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RCVCU1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ShiftGearPosn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidFD3VCU2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CSVCU2CAN1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RCVCU2CAN1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrActvDmpDisabReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMCUEnaReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidFD3VCU5_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FDCVCURrSpdMaxReq_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FDCVCURrSpdMinReq_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FDCVCURrTMCtrlModeReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FDCVCURrTMSpdReq_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FDCVCURrTMTqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FDCVCURrTqMaxReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FDCVCURrTqMinReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidGW3CE1000_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeDay_DAY'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeHour_hr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeMinute_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeMonth_MONTH'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeSecond_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_VehSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
