[!/**
 * \file
 *
 * \brief AUTOSAR ComM
 *
 * This file contains the implementation of the AUTOSAR
 * module ComM.
 *
 * \version 5.21.4
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2024 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */!][!//

[!/* *** multiple inclusion protection *** */!]
[!IF "not(var:defined('COMM_FUNCTIONS_M'))"!]
[!VAR "COMM_FUNCTIONS_M" = "'true'"!]

[!NOCODE!][!//

[!MACRO "macroGetPnOffset"!][!/*
  */!][!VAR "macroRetValGetPnOffset"="'none'"!][!/*
    */!][!VAR "macroGetPnOffset_FoundBusNmOffset" = "'none'"!][!/*
    
    */!][!FOR "i" = "1" TO "num:i((count(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*)))"!][!/*
        */!][!FOR "j" = "1" TO "num:i((count(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*[num:i($i)]/ComMChannelPerPnc/*)))"!][!/*
          */!][!IF "node:exists(as:modconf('Nm')[1]/NmChannelConfig/*[NmComMChannelRef = as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*[num:i($i)]/ComMChannelPerPnc/*[num:i($j)]]/NmBusType/NmStandardBusType)"!][!/*
              */!][!IF "text:contains(string(as:modconf('Nm')[1]/NmChannelConfig/*[NmComMChannelRef = as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*[num:i($i)]/ComMChannelPerPnc/*[num:i($j)]]/NmBusType/NmStandardBusType), 'CANNM')"!][!/*
                  */!][!IF "node:exists( as:modconf('CanNm')[1]/CanNmGlobalConfig/*[1]/CanNmPnInfo)"!][!/*
                      */!][!VAR "macroGetPnOffset_FoundBusNmOffset" = "num:i(as:modconf('CanNm')[1]/CanNmGlobalConfig/*[1]/CanNmPnInfo/CanNmPnInfoOffset)"!][!/*
                      */!][!BREAK!][!/*
                  */!][!ENDIF!][!/*
              */!][!ENDIF!][!/*
              
              */!][!IF "text:contains(string(as:modconf('Nm')[1]/NmChannelConfig/*[NmComMChannelRef = as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*[num:i($i)]/ComMChannelPerPnc/*[num:i($j)]]/NmBusType/NmStandardBusType), 'UDPNM')"!][!/*
                  */!][!IF "node:exists( as:modconf('UdpNm')[1]/UdpNmGlobalConfig/*[1]/UdpNmPnInfo)"!][!/*
                      */!][!VAR "macroGetPnOffset_FoundBusNmOffset" = "num:i(as:modconf('UdpNm')[1]/UdpNmGlobalConfig/*[1]/UdpNmPnInfo/UdpNmPnInfoOffset)"!][!/*
                      */!][!BREAK!][!/*
                  */!][!ENDIF!][!/*
              */!][!ENDIF!][!/*
              
              */!][!IF "text:contains(string(as:modconf('Nm')[1]/NmChannelConfig/*[NmComMChannelRef = as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*[num:i($i)]/ComMChannelPerPnc/*[num:i($j)]]/NmBusType/NmStandardBusType), 'FRNM')"!][!/*
                  */!][!IF "node:exists( as:modconf('FrNm')[1]/FrNmGlobalConfig/FrNmGlobalFeatures/FrNmPnInfo/FrNmPnInfoOffset)"!][!/*
                      */!][!VAR "macroGetPnOffset_FoundBusNmOffset" = "num:i(as:modconf('FrNm')[1]/FrNmGlobalConfig/FrNmGlobalFeatures/FrNmPnInfo/FrNmPnInfoOffset)"!][!/*
                      */!][!BREAK!][!/*
                  */!][!ENDIF!][!/*
              */!][!ENDIF!][!/*
          */!][!ENDIF!][!/*
        */!][!ENDFOR!][!/*
        */!][!IF "num:isnumber($macroGetPnOffset_FoundBusNmOffset) and ($macroGetPnOffset_FoundBusNmOffset >0) "!][!/*
                */!][!BREAK!][!/*
        */!][!ENDIF!][!/*
    */!][!ENDFOR!][!/*
    
    */!][!IF "node:exists(as:modconf('ComM')[1]/ComMGeneral/ComMPnInfoOffset) ='true'"!][!//
            [!/* !LINKSTO ComM.EB.PartialNetworkOffset_ComMPnInfoOffsetEnabled,1 */!] 
            [!VAR "macroRetValGetPnOffset"= "num:i(as:modconf('ComM')[1]/ComMGeneral/ComMPnInfoOffset)"!][!/*
    */!][!ELSE!][!/*
        */!][!IF "num:isnumber($macroGetPnOffset_FoundBusNmOffset)"!][!//
                [!/* !LINKSTO ComM.EB.PartialNetworkOffset_busNmOffsetUsage,1 */!]
                [!VAR "macroRetValGetPnOffset"="num:i($macroGetPnOffset_FoundBusNmOffset)"!][!/*
        */!][!ELSE!][!/*
            */!][!WARNING!] "Could not setup the PNC offset. Consider enabling ComMPnInfoOffset or setup one of PnInfo in CAN/UDP/FR NM." [!ENDWARNING!][!/*
        */!][!ENDIF!][!/*
    */!][!ENDIF!][!//
[!ENDMACRO!][!//

[!MACRO "GetMasterCoreId"!][!//
[!VAR "MasterCoreId"="''"!][!//
[!VAR "PartitionRef" = "as:modconf('ComM')[1]/ComMGeneral/ComMMasterCoreEcuCPartitionRef"!][!//
[!LOOP "as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $PartitionRef)]"!][!/*
  */!][!IF "node:exists(OsApplicationCoreRef)"!][!/*
    */!][!VAR "MasterOsApplicationCoreRefFound" = "'false'"!][!/*
    */!][!FOR "Idx" = "1" TO "count(text:split($MasterCoreId,'_'))"!][!/*
      */!][!IF "num:i(string(text:split($MasterCoreId,'_')[position() = $Idx])) = num:i(node:ref(OsApplicationCoreRef)/EcucCoreId)"!][!/*
        */!][!VAR "MasterOsApplicationCoreRefFound" = "'true'"!][!/*
      */!][!ENDIF!][!/*
    */!][!ENDFOR!][!/*
    */!][!IF "$MasterOsApplicationCoreRefFound = 'false'"!][!/*
      */!][!IF "count(text:split($MasterCoreId,'_')) = 0"!][!/*
        */!][!VAR "MasterCoreId" = "num:i(node:ref(OsApplicationCoreRef)/EcucCoreId)"!][!/*
      */!][!ELSE!][!/*
        */!][!VAR "MasterCoreId" = "concat($MasterCoreId,'_')"!][!/*
        */!][!VAR "MasterCoreId" = "concat($MasterCoreId,num:i(node:ref(OsApplicationCoreRef)/EcucCoreId))"!][!/*
      */!][!ENDIF!][!/*
    */!][!ENDIF!][!/*
  */!][!ELSE!][!/*
    */!][!IF "node:exists(OsApplicationCoreAssignment)"!][!/*
      */!][!VAR "MasterOsApplicationCoreAssignmentFound" = "'false'"!][!/*
      */!][!FOR "Idx" = "1" TO "count(text:split($MasterCoreId,'_'))"!][!/*
        */!][!IF "num:i(string(text:split($MasterCoreId,'_')[position() = $Idx])) = num:i(OsApplicationCoreAssignment)"!][!/*
          */!][!VAR "MasterOsApplicationCoreAssignmentFound" = "'true'"!][!/*
        */!][!ENDIF!][!/*
      */!][!ENDFOR!][!/*
      */!][!IF "$MasterOsApplicationCoreAssignmentFound = 'false'"!][!/*
        */!][!IF "count(text:split($MasterCoreId,'_')) = 0"!][!/*
          */!][!VAR "MasterCoreId" = "num:i(OsApplicationCoreAssignment)"!][!/*
        */!][!ELSE!][!/*
          */!][!VAR "MasterCoreId" = "concat($MasterCoreId,'_')"!][!/*
          */!][!VAR "MasterCoreId" = "concat($MasterCoreId,num:i(OsApplicationCoreAssignment))"!][!/*
        */!][!ENDIF!][!/*
      */!][!ENDIF!][!/*
    */!][!ENDIF!][!/*
  */!][!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDMACRO!][!//
[!MACRO "GetCore","SignalHandle","Direction"!][!//
[!VAR "SignalRef" = "as:modconf('ComM')[1]/ComMConfigSet/*/ComMPnc/*/ComMPncComSignal/*[string(ComMPncComSignalDirection) = $Direction][number(node:ref(ComMPncComSignalRef)/ComHandleId) = $SignalHandle]/ComMPncComSignalRef"!][!//
[!VAR "MainFunctionRef" = "as:modconf('Com')[1]/ComConfig/*/ComIPdu/*/ComIPduSignalRef/*[node:exists(.) and (string(.) = $SignalRef)]/../../ComMainFunctionRef"!][!//
[!VAR "PartitionRef" = "node:ref($MainFunctionRef)/ComPartitionRef"!][!//
[!LOOP "as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $PartitionRef)]"!][!/*
  */!][!IF "node:exists(OsApplicationCoreRef)"!][!/*
    */!][!VAR "SlaveOsApplicationCoreCoreRef" = "'false'"!][!/*
    */!][!FOR "Idx" = "1" TO "count(text:split($FoundCore,'_'))"!][!/*
      */!][!IF "num:i(string(text:split($FoundCore,'_')[position() = $Idx])) = num:i(node:ref(OsApplicationCoreRef)/EcucCoreId)"!][!/*
        */!][!VAR "SlaveOsApplicationCoreCoreRef" = "'true'"!][!/*
      */!][!ENDIF!][!/*
    */!][!ENDFOR!][!/*
    */!][!IF "$SlaveOsApplicationCoreCoreRef = 'false'"!][!/*
      */!][!IF "count(text:split($FoundCore,'_')) = 0"!][!/*
        */!][!VAR "FoundCore" = "num:i(node:ref(OsApplicationCoreRef)/EcucCoreId)"!][!/*
      */!][!ELSE!][!/*
        */!][!VAR "FoundCore" = "concat($FoundCore,'_')"!][!/*
        */!][!VAR "FoundCore" = "concat($FoundCore,num:i(node:ref(OsApplicationCoreRef)/EcucCoreId))"!][!/*
      */!][!ENDIF!][!/*
    */!][!ENDIF!][!/*
  */!][!ELSE!][!/*
    */!][!IF "node:exists(OsApplicationCoreAssignment)"!][!/*
      */!][!VAR "SlaveOsApplicationCoreAssignmentFound" = "'false'"!][!/*
      */!][!FOR "Idx" = "1" TO "count(text:split($FoundCore,'_'))"!][!/*
        */!][!IF "num:i(string(text:split($FoundCore,'_')[position() = $Idx])) = num:i(OsApplicationCoreAssignment)"!][!/*
          */!][!VAR "SlaveOsApplicationCoreAssignmentFound" = "'true'"!][!/*
        */!][!ENDIF!][!/*
      */!][!ENDFOR!][!/*
      */!][!IF "$SlaveOsApplicationCoreAssignmentFound = 'false'"!][!/*
        */!][!IF "count(text:split($FoundCore,'_')) = 0"!][!/*
          */!][!VAR "FoundCore" = "num:i(OsApplicationCoreAssignment)"!][!/*
        */!][!ELSE!][!/*
          */!][!VAR "FoundCore" = "concat($FoundCore,'_')"!][!/*
          */!][!VAR "FoundCore" = "concat($FoundCore,num:i(OsApplicationCoreAssignment))"!][!/*
        */!][!ENDIF!][!/*
      */!][!ENDIF!][!/*
    */!][!ENDIF!][!/*
  */!][!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDMACRO!][!//

[!MACRO "GetUsedCores"!][!//
[!CALL "GetMasterCoreId"!][!//
[!VAR "FoundCore"="$MasterCoreId"!][!//
[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*[ComMPncComSignalDirection='RX']/ComMPncComSignalRef)),'ComHandleId'))"!][!/*
  */!][!CALL "GetCore","SignalHandle"="ComHandleId","Direction"="'RX'"!][!//
[!ENDLOOP!][!//
[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*[ComMPncComSignalDirection='TX']/ComMPncComSignalRef)),'ComHandleId'))"!][!/*
  */!][!CALL "GetCore","SignalHandle"="ComHandleId","Direction"="'TX'"!][!//
[!ENDLOOP!][!//
[!VAR "UsedCores"="$FoundCore"!][!//
[!ENDMACRO!][!//

[!MACRO "GetPnInfoLength"!][!//
[!VAR "SigSize1" = "0"!][!//
[!VAR "SigSize2" = "0"!][!//
[!/* Get the length of the largest Com signal for array-type signals */!]
[!IF "count(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*/ComMPncComSignalRef))[text:contains(string(ComSignalType), 'UINT8_')]) != 0"!][!//
[!VAR "SigSize1" = "num:max(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*/ComMPncComSignalRef))[text:contains(string(ComSignalType), 'UINT8_')]/ComSignalLength)"!][!//
[!ENDIF!][!//
[!/* Get the length of the largest Com signal for non array-type signals */!]
[!IF "count(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*/ComMPncComSignalRef))[not(text:contains(string(ComSignalType), 'UINT8_'))]) != 0"!][!//
[!VAR "SigSize2" = "num:max(node:foreach(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*/ComMPncComSignalRef))[not(text:contains(string(ComSignalType), 'UINT8_'))]/ComSignalType, 'SigType', 'node:when($SigType = "BOOLEAN", "8", substring-after($SigType, "T"))')) div 8 "!][!//
[!ENDIF!][!//
[!IF "$SigSize1 > $SigSize2"!][!//
[!VAR "PnInfoLength" = "num:i($SigSize1)"!][!//
[!ELSE!][!//
[!VAR "PnInfoLength" = "num:i($SigSize2)"!][!//
[!ENDIF!][!//
[!ENDMACRO!][!//

[!MACRO "GetNoOfTxBuffers"!][!//
[!VAR "NoOfTxBuffers" = "0"!][!//
[!CALL "GetMasterCoreId"!][!//
[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*[ComMPncComSignalDirection='TX']/ComMPncComSignalRef)), 'ComHandleId'))"!][!/*
  */!][!VAR "FoundCore" = "''"!][!/*
  */!][!CALL "GetCore","SignalHandle"="ComHandleId","Direction"="'TX'"!][!/*
  */!][!IF "num:i($FoundCore) != num:i($MasterCoreId)"!][!/*
    */!][!VAR "NoOfTxBuffers" = "$NoOfTxBuffers + 1"!][!/*
  */!][!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDMACRO!][!//

[!MACRO "GetNoOfRxBuffers"!][!//
[!VAR "NoOfRxBuffers" = "0"!][!//
[!CALL "GetMasterCoreId"!][!//
[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*[ComMPncComSignalDirection='RX']/ComMPncComSignalRef)), 'ComHandleId'))"!][!/*
  */!][!VAR "FoundCore" = "''"!][!/*
  */!][!CALL "GetCore","SignalHandle"="ComHandleId","Direction"="'RX'"!][!/*
  */!][!IF "num:i($FoundCore) != num:i($MasterCoreId)"!][!/*
    */!][!VAR "NoOfRxBuffers" = "$NoOfRxBuffers + 1"!][!/*
  */!][!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDMACRO!][!//

[!MACRO "GetRxSignalIndex","SignalHandleId"!][!//
[!CALL "GetMasterCoreId"!][!//
[!VAR "RxSignalIndex" = "65535"!][!//
[!VAR "Cntr" = "0"!][!//
[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*[ComMPncComSignalDirection='RX']/ComMPncComSignalRef)), 'ComHandleId'))"!][!/*
  */!][!VAR "FoundCore" = "''"!][!/*
  */!][!CALL "GetCore","SignalHandle"="ComHandleId","Direction"="'RX'"!][!/*
  */!][!IF "num:i($FoundCore) != num:i($MasterCoreId)"!][!/*
    */!][!IF "num:i(ComHandleId) = num:i($SignalHandleId)"!][!/*
      */!][!VAR "RxSignalIndex" = "$Cntr"!][!/*
    */!][!ENDIF!][!/*
    */!][!VAR "Cntr" = "$Cntr + 1"!][!/*
  */!][!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDMACRO!][!//

[!MACRO "GetInhibitionOsApplication"!]
[!VAR "InhibitionOsApplication" = "node:name(as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (OsAppEcucPartitionRef = as:modconf('ComM')[1]/ComMGeneral/ComMInhibitionEcuCPartitionRef)])"!]
[!ENDMACRO!]

[!MACRO "GetUsedInhibitionOsApplication"!]
[!VAR "FoundInhibitionOsApplication"="''"!]
[!IF "node:exists(as:modconf('ComM')[1]/ComMGeneral/ComMInhibitionEcuCPartitionRef)"!]
  [!VAR "FoundInhibitionOsApplication" = "node:name(as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (OsAppEcucPartitionRef = as:modconf('ComM')[1]/ComMGeneral/ComMInhibitionEcuCPartitionRef)])"!]
[!ENDIF!] [!/*[!IF "node:exists(as:modconf('ComM')[1]/ComMGeneral/ComMInhibitionEcuCPartitionRef))"!]*/!]
[!ENDMACRO!]

[!MACRO "GetMasterPncOsApplication"!]
[!VAR "MasterPncOsApplication"="''"!]
[!IF "node:exists(as:modconf('ComM')[1]/ComMGeneral/ComMMasterPNCEcuCPartitionRef)"!]
  [!VAR "MasterPncOsApplication" = "node:name(as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (OsAppEcucPartitionRef = as:modconf('ComM')[1]/ComMGeneral/ComMMasterPNCEcuCPartitionRef)])"!]
[!ENDIF!]  
[!ENDMACRO!]

[!MACRO "GetUsedChannelsOsApplications"!]
[!VAR "FoundChannelsOsApplications"="''"!]
[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
  [!IF "node:exists(ComMChannelPartitionRef)"!]
    [!VAR "PartitionRef" = "ComMChannelPartitionRef"!]
    [!LOOP "as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $PartitionRef)]"!]
      [!VAR "OsApplicationAssignmentFound" = "'false'"!]
      [!FOR "Idx" = "1" TO "count(text:split($FoundChannelsOsApplications,' '))"!]
        [!IF "(string(text:split($FoundChannelsOsApplications,' ')[position() = $Idx]) = node:name(.))"!]
          [!VAR "OsApplicationAssignmentFound" = "'true'"!]
        [!ENDIF!]
      [!ENDFOR!]
      [!IF "$OsApplicationAssignmentFound = 'false'"!]
        [!IF "count(text:split($FoundChannelsOsApplications,' ')) = 0"!]
          [!VAR "FoundChannelsOsApplications" = "node:name(.)"!]
        [!ELSE!]
         [!VAR "FoundChannelsOsApplications" = "concat($FoundChannelsOsApplications,' ')"!]
         [!VAR "FoundChannelsOsApplications" = "concat($FoundChannelsOsApplications,node:name(.))"!]
        [!ENDIF!]
      [!ENDIF!]
    [!ENDLOOP!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetUsedChannelsOsApplicationsForRteNotification"!]
[!VAR "FoundChannelsOsApplicationsForRteNotification"="''"!]
[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
  [!IF "node:exists(ComMChannelPartitionRef)"!]
    [!IF "ComMFullCommRequestNotificationEnabled = 'true'"!]
      [!VAR "PartitionRef" = "ComMChannelPartitionRef"!]
      [!LOOP "as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $PartitionRef)]"!]
        [!VAR "OsApplicationAssignmentFound" = "'false'"!]
        [!FOR "Idx" = "1" TO "count(text:split($FoundChannelsOsApplicationsForRteNotification,' '))"!]
          [!IF "(string(text:split($FoundChannelsOsApplicationsForRteNotification,' ')[position() = $Idx]) = node:name(.))"!]
            [!VAR "OsApplicationAssignmentFound" = "'true'"!]
          [!ENDIF!]
        [!ENDFOR!]
        [!IF "$OsApplicationAssignmentFound = 'false'"!]
          [!IF "count(text:split($FoundChannelsOsApplicationsForRteNotification,' ')) = 0"!]
            [!VAR "FoundChannelsOsApplicationsForRteNotification" = "node:name(.)"!]
          [!ELSE!]
           [!VAR "FoundChannelsOsApplicationsForRteNotification" = "concat($FoundChannelsOsApplicationsForRteNotification,' ')"!]
           [!VAR "FoundChannelsOsApplicationsForRteNotification" = "concat($FoundChannelsOsApplicationsForRteNotification,node:name(.))"!]
          [!ENDIF!]
        [!ENDIF!]
      [!ENDLOOP!]
    [!ENDIF!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetSignalOsApplication","SignalHandle","Direction"!]
  [!VAR "SignalOsApplication" = "''"!]
  [!VAR "SignalRef" = "as:modconf('ComM')[1]/ComMConfigSet/*/ComMPnc/*/ComMPncComSignal/*[string(ComMPncComSignalDirection) = $Direction][number(node:ref(ComMPncComSignalRef)/ComHandleId) = $SignalHandle]/ComMPncComSignalRef"!]
  [!VAR "MainFunctionRef" = "as:modconf('Com')[1]/ComConfig/*/ComIPdu/*/ComIPduSignalRef/*[node:exists(.) and (string(.) = $SignalRef)]/../../ComMainFunctionRef"!]
  [!VAR "PartitionRef" = "node:ref($MainFunctionRef)/ComPartitionRef"!]
  [!VAR "SignalOsApplication" = "node:name(as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $PartitionRef)])"!]
[!ENDMACRO!]

[!MACRO "GetSignalOsApplicationTemp","SignalHandle","Direction"!]
  [!VAR "SignalOsApplicationTemp" = "''"!]
  [!VAR "SignalRef" = "as:modconf('ComM')[1]/ComMConfigSet/*/ComMPnc/*/ComMPncComSignal/*[string(ComMPncComSignalDirection) = $Direction][number(node:ref(ComMPncComSignalRef)/ComHandleId) = $SignalHandle]/ComMPncComSignalRef"!]
  [!VAR "MainFunctionRef" = "as:modconf('Com')[1]/ComConfig/*/ComIPdu/*/ComIPduSignalRef/*[node:exists(.) and (string(.) = $SignalRef)]/../../ComMainFunctionRef"!]
  [!VAR "PartitionRef" = "node:ref($MainFunctionRef)/ComPartitionRef"!]
  [!VAR "SignalOsApplicationTemp" = "node:name(as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $PartitionRef)])"!]
[!ENDMACRO!]

[!MACRO "GetUsedSignalsPlusMasterPncOsApplications"!]
[!CALL "GetMasterPncOsApplication"!]
[!VAR "FoundMasterPncPlusSignalsOsApplications"="$MasterPncOsApplication"!]
[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*[ComMPncComSignalDirection='RX']/ComMPncComSignalRef)),'ComHandleId'))"!]
  [!CALL "GetSignalOsApplication","SignalHandle"="ComHandleId","Direction"="'RX'"!]
  [!VAR "OsAssignmentFound" = "'false'"!]
  [!FOR "Idx" = "1" TO "count(text:split($FoundMasterPncPlusSignalsOsApplications,' '))"!]
    [!IF "string(text:split($FoundMasterPncPlusSignalsOsApplications,' ')[position() = $Idx]) = $SignalOsApplication"!]
      [!VAR "OsAssignmentFound" = "'true'"!]
    [!ENDIF!]
  [!ENDFOR!]
  [!IF "$OsAssignmentFound = 'false'"!]
    [!VAR "FoundMasterPncPlusSignalsOsApplications" = "concat($FoundMasterPncPlusSignalsOsApplications,' ')"!]
    [!VAR "FoundMasterPncPlusSignalsOsApplications" = "concat($FoundMasterPncPlusSignalsOsApplications,$SignalOsApplication)"!]
  [!ENDIF!]  
[!ENDLOOP!]
[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*[ComMPncComSignalDirection='TX']/ComMPncComSignalRef)),'ComHandleId'))"!]
  [!CALL "GetSignalOsApplication","SignalHandle"="ComHandleId","Direction"="'TX'"!]
  [!VAR "OsAssignmentFound" = "'false'"!]
  [!FOR "Idx" = "1" TO "count(text:split($FoundMasterPncPlusSignalsOsApplications,' '))"!]
    [!IF "string(text:split($FoundMasterPncPlusSignalsOsApplications,' ')[position() = $Idx]) = $SignalOsApplication"!]
      [!VAR "OsAssignmentFound" = "'true'"!]
    [!ENDIF!]
  [!ENDFOR!]
  [!IF "$OsAssignmentFound = 'false'"!]
    [!VAR "FoundMasterPncPlusSignalsOsApplications" = "concat($FoundMasterPncPlusSignalsOsApplications,' ')"!]
    [!VAR "FoundMasterPncPlusSignalsOsApplications" = "concat($FoundMasterPncPlusSignalsOsApplications,$SignalOsApplication)"!]
  [!ENDIF!]    
[!ENDLOOP!]

[!ENDMACRO!]

[!MACRO "GetUsedUserOsApplications"!]
[!VAR "FoundUserOsApplications"="''"!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]
  [!IF "node:exists(ComMUserEcucPartitionRef)"!]
    [!CALL "GetUserOsApplication","UserEcuCPartitionRef"="ComMUserEcucPartitionRef"!]
    [!VAR "OsApplicationAssignmentFound" = "'false'"!]
    [!FOR "Idx" = "1" TO "count(text:split($FoundUserOsApplications,' '))"!]
      [!IF "(string(text:split($FoundUserOsApplications,' ')[position() = $Idx]) = $UserOsApplication)"!]
        [!VAR "OsApplicationAssignmentFound" = "'true'"!]
      [!ENDIF!]
    [!ENDFOR!]
    [!IF "$OsApplicationAssignmentFound = 'false'"!]
      [!IF "count(text:split($FoundUserOsApplications,' ')) = 0"!]
        [!VAR "FoundUserOsApplications" = "$UserOsApplication"!]
      [!ELSE!]
        [!VAR "FoundUserOsApplications" = "concat($FoundUserOsApplications,' ')"!]
        [!VAR "FoundUserOsApplications" = "concat($FoundUserOsApplications,$UserOsApplication)"!]
      [!ENDIF!]
    [!ENDIF!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetChannelOsApplication","ChannelEcuCPartitionRef"!]
[!VAR "ChannelOsApplication" = "node:name(as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $ChannelEcuCPartitionRef)])"!]
[!ENDMACRO!]

[!MACRO "GetUserOsApplication","UserEcuCPartitionRef"!]
[!VAR "UserOsApplication" = "node:name(as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $UserEcuCPartitionRef)])"!]
[!ENDMACRO!]

[!MACRO "GetChannelOsApplicationByName","ChannelName"!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]
  [!IF "node:name(.) = $ChannelName"!]
    [!IF "node:exists(ComMChannelPartitionRef)"!]
      [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef" = "ComMChannelPartitionRef"!]
      [!BREAK!]
    [!ENDIF!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetChannelsOfUser","UserName","FilterByOsApplication","OsApplication"!]
[!VAR "FoundChannelsOfUsers" = "''"!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*/ComMUserPerChannel/*"!]
  [!IF "(node:name(node:ref(ComMUserChannel)) = $UserName)"!]
    [!VAR "ChannelName" = "node:name(../..)"!]
    [!CALL "GetChannelOsApplicationByName","ChannelName"="$ChannelName"!]
    [!IF "(($FilterByOsApplication = 'true') and ($ChannelOsApplication = $OsApplication)) or ($FilterByOsApplication = 'false')"!]
      [!VAR "ChannelFound" = "'false'"!]
      [!FOR "Idx" = "1" TO "count(text:split($FoundChannelsOfUsers,' '))"!]
        [!IF "(string(text:split($FoundChannelsOfUsers,' ')[position() = $Idx]) = $ChannelName)"!]
          [!VAR "ChannelFound" = "'true'"!]
        [!ENDIF!]
      [!ENDFOR!]
      [!IF "$ChannelFound = 'false'"!]
        [!IF "count(text:split($FoundChannelsOfUsers,' ')) = 0"!]
          [!VAR "FoundChannelsOfUsers" = "$ChannelName"!]
        [!ELSE!]
         [!VAR "FoundChannelsOfUsers" = "concat($FoundChannelsOfUsers,' ')"!]
         [!VAR "FoundChannelsOfUsers" = "concat($FoundChannelsOfUsers, $ChannelName)"!]
        [!ENDIF!]
      [!ENDIF!]
    [!ENDIF!] [!/*[!IF "(($FilterByOsApplication = 'true') and ($ChannelOsApplication = $OsApplication)) or ($FilterByOsApplication = 'false')"!]*/!]
  [!ENDIF!]
[!ENDLOOP!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMUserPerPnc/*"!] 
  [!IF "node:name(node:ref(.)) = $UserName"!]
    [!LOOP "../../ComMChannelPerPnc/*"!]
      [!VAR "ChannelName" = "node:name(node:ref(.))"!]
      [!CALL "GetChannelOsApplicationByName","ChannelName"="$ChannelName"!]
      [!IF "(($FilterByOsApplication = 'true') and ($ChannelOsApplication = $OsApplication)) or ($FilterByOsApplication = 'false')"!]
        [!VAR "ChannelFound" = "'false'"!]
        [!FOR "Idx" = "1" TO "count(text:split($FoundChannelsOfUsers,' '))"!]
          [!IF "(string(text:split($FoundChannelsOfUsers,' ')[position() = $Idx]) = $ChannelName)"!]
            [!VAR "ChannelFound" = "'true'"!]
          [!ENDIF!]
        [!ENDFOR!]
        [!IF "$ChannelFound = 'false'"!]
          [!IF "count(text:split($FoundChannelsOfUsers,' ')) = 0"!]
            [!VAR "FoundChannelsOfUsers" = "$ChannelName"!]
          [!ELSE!]
           [!VAR "FoundChannelsOfUsers" = "concat($FoundChannelsOfUsers,' ')"!]
           [!VAR "FoundChannelsOfUsers" = "concat($FoundChannelsOfUsers, $ChannelName)"!]
          [!ENDIF!]
        [!ENDIF!]
      [!ENDIF!] [!/*[!IF "(($FilterByOsApplication = 'true') and ($ChannelOsApplication = $OsApplication)) or ($FilterByOsApplication = 'false')"!]*/!]
    [!ENDLOOP!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetUsedUserPlusChannelPlusMasterPncPlusInhibitionOsApplications"!]
[!CALL "GetMasterPncOsApplication"!]
[!CALL "GetUsedUserOsApplications"!]
[!CALL "GetUsedInhibitionOsApplication"!]
[!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications"="$MasterPncOsApplication"!]
[!VAR "OsApplicationAssignmentFound" = "'false'"!]
[!FOR "Idx1" = "1" TO "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' '))"!]
  [!IF "($FoundInhibitionOsApplication) = string(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')[position() = $Idx1])"!]
    [!VAR "OsApplicationAssignmentFound" = "'true'"!]
    [!BREAK!]
  [!ENDIF!]
[!ENDFOR!] [!/* [!FOR "Idx1" = "1" TO "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' '))"!] */!]
[!IF "$OsApplicationAssignmentFound = 'false'"!]
  [!IF "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')) = 0"!]
    [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "$FoundInhibitionOsApplication"!]
  [!ELSE!]
   [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "concat($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')"!]
   [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "concat($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,$FoundInhibitionOsApplication)"!]
  [!ENDIF!]
[!ENDIF!] 
[!FOR "Idx1" = "1" TO "count(text:split($FoundUserOsApplications,' '))"!]
  [!VAR "OsApplicationAssignmentFound" = "'false'"!]
  [!FOR "Idx2" = "1" TO "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' '))"!]
    [!IF "(string(text:split($FoundUserOsApplications,' ')[position() = $Idx1]) = string(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')[position() = $Idx2]))"!]
      [!VAR "OsApplicationAssignmentFound" = "'true'"!]
      [!BREAK!]
    [!ENDIF!]
  [!ENDFOR!] [!/* [!FOR "Idx1" = "1" TO "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' '))"!] */!]
  [!IF "$OsApplicationAssignmentFound = 'false'"!]
    [!IF "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')) = 0"!]
      [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "string(text:split($FoundUserOsApplications,' ')[position() = $Idx1])"!]
    [!ELSE!]
     [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "concat($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')"!]
     [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "concat($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,string(text:split($FoundUserOsApplications,' ')[position() = $Idx1]))"!]
    [!ENDIF!]
  [!ENDIF!] 
[!ENDFOR!] [!/*[!FOR "Idx1" = "1" TO "count(text:split($FoundUserOsApplications,' '))"!]*/!]
[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
  [!IF "node:exists(ComMChannelPartitionRef)"!]
    [!VAR "PartitionRef" = "ComMChannelPartitionRef"!]
    [!LOOP "as:modconf('Os')[1]/OsApplication/*[node:exists(OsAppEcucPartitionRef) and (string(OsAppEcucPartitionRef) = $PartitionRef)]"!]
      [!VAR "OsApplicationAssignmentFound" = "'false'"!]
      [!FOR "Idx" = "1" TO "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' '))"!]
        [!IF "(string(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')[position() = $Idx]) = node:name(.))"!]
          [!VAR "OsApplicationAssignmentFound" = "'true'"!]
        [!ENDIF!]
      [!ENDFOR!]
      [!IF "$OsApplicationAssignmentFound = 'false'"!]
        [!IF "count(text:split($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')) = 0"!]
          [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "node:name(.)"!]
        [!ELSE!]
         [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "concat($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,' ')"!]
         [!VAR "FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications" = "concat($FoundUserPlusChannePlusMasterPncPlusInhibitionOsApplications,node:name(.))"!]
        [!ENDIF!]
      [!ENDIF!]
    [!ENDLOOP!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetMulticoreNoOfTxBuffers"!]
[!VAR "MulticoreNoOfTxBuffers" = "0"!]
[!CALL "GetMasterPncOsApplication"!]
[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*[ComMPncComSignalDirection='TX']/ComMPncComSignalRef)), 'ComHandleId'))"!]
  [!CALL "GetSignalOsApplicationTemp","SignalHandle"="ComHandleId","Direction"="'TX'"!]
  [!IF "$SignalOsApplicationTemp != $MasterPncOsApplication"!]
    [!VAR "MulticoreNoOfTxBuffers" = "$MulticoreNoOfTxBuffers + 1"!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetMulticoreRxSignalIndex","SignalHandleId"!]
[!VAR "MulticoreRxSignalIndex" = "65535"!]
[!VAR "Cntr" = "0"!]
[!CALL "GetMasterPncOsApplication"!]
[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*[ComMPncComSignalDirection='RX']/ComMPncComSignalRef)), 'ComHandleId'))"!]
  [!CALL "GetSignalOsApplicationTemp","SignalHandle"="ComHandleId","Direction"="'RX'"!]
  [!IF "$SignalOsApplicationTemp != $MasterPncOsApplication"!]
    [!IF "num:i(ComHandleId) = num:i($SignalHandleId)"!]
      [!VAR "MulticoreRxSignalIndex" = "$Cntr"!]
    [!ENDIF!]
    [!VAR "Cntr" = "$Cntr + 1"!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetMulticoreNoOfRxBuffers"!]
[!VAR "MulticoreNoOfRxBuffers" = "0"!]
[!CALL "GetMasterPncOsApplication"!]
[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMPncComSignal/*[ComMPncComSignalDirection='RX']/ComMPncComSignalRef)), 'ComHandleId'))"!]
  [!CALL "GetSignalOsApplicationTemp","SignalHandle"="ComHandleId","Direction"="'RX'"!]
  [!IF "$SignalOsApplicationTemp != $MasterPncOsApplication"!]
    [!VAR "MulticoreNoOfRxBuffers" = "$MulticoreNoOfRxBuffers + 1"!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetChToCh_FromOsAppToOsAppList"!]
[!VAR "ChToChFromOsApp_ToOsApp" = "''"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]
  [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]
    [!IF "node:exists(EcuMComMChannelRef)"!]
      [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(EcuMComMChannelRef)/ComMChannelPartitionRef"!]
      [!VAR "FromOsApplication" ="$ChannelOsApplication"!]
      [!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
        [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef" = "ComMChannelPartitionRef"!]
        [!VAR "ToOsApplication" ="$ChannelOsApplication"!]
        [!IF "$FromOsApplication != $ToOsApplication"!]
          [!VAR "CurrentString" = "''"!]
          [!VAR "CurrentString"= "concat($CurrentString, $FromOsApplication)"!]
          [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
          [!VAR "CurrentString"= "concat($CurrentString, $ToOsApplication)"!]
          [!VAR "StringFound" = "'false'"!]
          [!FOR "Idx" = "1" TO "count(text:split($ChToChFromOsApp_ToOsApp,' '))"!]
            [!IF "string(text:split($ChToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
              [!VAR "StringFound" = "'true'"!]
            [!ENDIF!]
          [!ENDFOR!]
          [!IF "$StringFound = 'false'"!]
            [!IF "count(text:split($ChToChFromOsApp_ToOsApp,' ')) = 0"!]
                [!VAR "ChToChFromOsApp_ToOsApp" = "$CurrentString"!]
            [!ELSE!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp, ' ')"!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp, $FromOsApplication)"!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp,'->')"!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp, $ToOsApplication)"!]
            [!ENDIF!]
          [!ENDIF!]
        [!ENDIF!] [!/*[!IF "$FromOsApplication != $ToOsApplication"!]*/!]      
      [!ENDLOOP!] [!/* [!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!] */!]
    [!ENDIF!] [!/* [!IF "node:exists(EcuMComMChannelRef)"!] */!]
  [!ENDLOOP!] [!/* [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!] */!]
[!ELSE!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]*/!]  
  [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]
    [!IF "node:exists(EcuMComMChannelRef)"!]
      [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(EcuMComMChannelRef)/ComMChannelPartitionRef"!]
      [!VAR "FromOsApplication" ="$ChannelOsApplication"!]
      [!IF "node:exists(node:ref(EcuMComMChannelRef)/ComMManageReference/*[1])"!]
        [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(node:ref(EcuMComMChannelRef)/ComMManageReference/*[1])/ComMChannelPartitionRef"!]
        [!VAR "ToOsApplication" ="$ChannelOsApplication"!]
        [!IF "$FromOsApplication != $ToOsApplication"!]
          [!VAR "CurrentString" = "''"!]
          [!VAR "CurrentString"= "concat($CurrentString, $FromOsApplication)"!]
          [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
          [!VAR "CurrentString"= "concat($CurrentString, $ToOsApplication)"!]
          [!VAR "StringFound" = "'false'"!]
          [!FOR "Idx" = "1" TO "count(text:split($ChToChFromOsApp_ToOsApp,' '))"!]
            [!IF "string(text:split($ChToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
              [!VAR "StringFound" = "'true'"!]
            [!ENDIF!]
          [!ENDFOR!]
          [!IF "$StringFound = 'false'"!]
            [!IF "count(text:split($ChToChFromOsApp_ToOsApp,' ')) = 0"!]
                [!VAR "ChToChFromOsApp_ToOsApp" = "$CurrentString"!]
            [!ELSE!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp, ' ')"!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp, $FromOsApplication)"!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp,'->')"!]
              [!VAR "ChToChFromOsApp_ToOsApp"= "concat($ChToChFromOsApp_ToOsApp, $ToOsApplication)"!]
            [!ENDIF!]
          [!ENDIF!]
        [!ENDIF!] [!/*[!IF "$FromOsApplication != $ToOsApplication"!]*/!]        
      [!ENDIF!] [!/*[!IF "node:exists(node:ref(EcuMComMChannelRef)/ComMManageReference/*[1])*/!]
    [!ENDIF!] [!/*[!IF "node:exists(EcuMComMChannelRef)"!]*/!]
  [!ENDLOOP!] [!/* [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!] */!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]*/!]
[!ENDMACRO!]

[!MACRO "GetChToCh_FromOsAppToOsAppIndex","ChToChFromOsApp_ToOsApp","FromOsApplication","ToOsApplication"!]
[!VAR "CurrentString" = "$FromOsApplication"!]
[!VAR "CurrentString" = "concat($CurrentString,'->')"!]
[!VAR "CurrentString" = "concat($CurrentString, $ToOsApplication)"!]
[!VAR "FoundIndex"="'false'"!]
[!VAR "ChToChFctPtrIndex"="num:i(0)"!]
[!FOR "Idx" = "1" TO "count(text:split($ChToChFromOsApp_ToOsApp,' '))"!]
  [!IF "string(text:split($ChToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = ($CurrentString)"!]
    [!VAR "FoundIndex"="'true'"!]  
    [!BREAK!]
  [!ENDIF!]
  [!VAR "ChToChFctPtrIndex" = "$ChToChFctPtrIndex + 1"!]
[!ENDFOR!]
[!IF "$FoundIndex = 'false'"!]
  [!VAR "ChToChFctPtrIndex"= "num:i(255)"!]
[!ENDIF!]
[!ENDMACRO!]

[!MACRO "GetChToMasterPnc_FromOsAppToOsAppList"!]
[!VAR "ChToMasterPncFromOsApp_ToOsApp" = "''"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]
  [!CALL "GetMasterPncOsApplication"!]
  [!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]
    [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]
      [!IF "node:exists(EcuMComMChannelRef)"!]
        [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef" = "node:ref(EcuMComMChannelRef)/ComMChannelPartitionRef"!]    
        [!IF "$ChannelOsApplication != $MasterPncOsApplication "!]
          [!VAR "CurrentString" = "''"!]
          [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
          [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
          [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
          [!VAR "StringFound" = "'false'"!]
          [!FOR "Idx" = "1" TO "count(text:split($ChToMasterPncFromOsApp_ToOsApp,' '))"!]
            [!IF "string(text:split($ChToMasterPncFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
              [!VAR "StringFound" = "'true'"!]
            [!ENDIF!]
          [!ENDFOR!]
          [!IF "$StringFound = 'false'"!]
            [!IF "count(text:split($ChToMasterPncFromOsApp_ToOsApp,' ')) = 0"!]
                [!VAR "ChToMasterPncFromOsApp_ToOsApp" = "$CurrentString"!]
            [!ELSE!]
              [!VAR "ChToMasterPncFromOsApp_ToOsApp"= "concat($ChToMasterPncFromOsApp_ToOsApp, ' ')"!]
              [!VAR "ChToMasterPncFromOsApp_ToOsApp"= "concat($ChToMasterPncFromOsApp_ToOsApp, $ChannelOsApplication)"!]
              [!VAR "ChToMasterPncFromOsApp_ToOsApp"= "concat($ChToMasterPncFromOsApp_ToOsApp,'->')"!]
              [!VAR "ChToMasterPncFromOsApp_ToOsApp"= "concat($ChToMasterPncFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
            [!ENDIF!]
          [!ENDIF!]
        [!ENDIF!] [!/*[!IF "$ChannelOsApplication != $MasterPncOsApplication "!]*/!]      
      [!ENDIF!] [!/*[!IF "node:exists(EcuMComMChannelRef)"!]*/!]
    [!ENDLOOP!] [!/*[!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]*/!]
  [!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]*/!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]*/!]
[!ENDMACRO!]

[!MACRO "GetChToMasterPnc_FromOsAppToOsAppIndex","ChToMasterPncFromOsApp_ToOsApp","FromOsApplication","ToOsApplication"!]
[!VAR "CurrentString" = "$FromOsApplication"!]
[!VAR "CurrentString" = "concat($CurrentString,'->')"!]
[!VAR "CurrentString" = "concat($CurrentString, $ToOsApplication)"!]
[!VAR "FoundIndex"="'false'"!]
[!VAR "ChToMasterPncFctPtrIndex"="num:i(0)"!]
[!FOR "Idx" = "1" TO "count(text:split($ChToMasterPncFromOsApp_ToOsApp,' '))"!]
  [!IF "string(text:split($ChToMasterPncFromOsApp_ToOsApp,' ')[position() = $Idx]) = ($CurrentString)"!]
    [!VAR "FoundIndex"="'true'"!]  
    [!BREAK!]
  [!ENDIF!]
  [!VAR "ChToMasterPncFctPtrIndex" = "$ChToMasterPncFctPtrIndex + 1"!]
[!ENDFOR!]
[!IF "$FoundIndex = 'false'"!]
  [!VAR "ChToMasterPncFctPtrIndex"= "num:i(255)"!]
[!ENDIF!]
[!ENDMACRO!]

[!MACRO "GetUserToCh_FromOsAppToOsAppList"!]
[!VAR "UserToChFromOsApp_ToOsApp" = "''"!]
[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]
  [!VAR "UserId" = "ComMUserIdentifier"!]
  [!CALL "GetUserOsApplication","UserEcuCPartitionRef"="ComMUserEcucPartitionRef"!]
  [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMUserPerPnc/*"!]
    [!IF "$UserId = node:value(node:ref(.)/ComMUserIdentifier)"!]
      [!LOOP "../../ComMChannelPerPnc/*"!]
        [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(.)/ComMChannelPartitionRef"!]
        [!IF "$UserOsApplication != $ChannelOsApplication"!]
          [!VAR "CurrentString" = "''"!]
          [!VAR "CurrentString"= "concat($CurrentString,$UserOsApplication)"!]
          [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
          [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
          [!VAR "UserToChannelFound" = "'false'"!]
          [!FOR "Idx1" = "1" TO "count(text:split($UserToChFromOsApp_ToOsApp,' '))"!]
            [!IF "($CurrentString) = string(text:split($UserToChFromOsApp_ToOsApp,' ')[position() = $Idx1])"!]
              [!VAR "UserToChannelFound" = "'true'"!]
              [!BREAK!]
            [!ENDIF!]
          [!ENDFOR!] [!/* [!FOR "Idx1" = "1" TO "count(text:split($UserToChFromOsApp_ToOsApp,' '))"!] */!]        
          [!IF "$UserToChannelFound = 'false'"!]
            [!IF "count(text:split($UserToChFromOsApp_ToOsApp,' ')) = 0"!]
              [!VAR "UserToChFromOsApp_ToOsApp" = "$CurrentString"!]
            [!ELSE!]
             [!VAR "UserToChFromOsApp_ToOsApp" = "concat($UserToChFromOsApp_ToOsApp,' ')"!]
             [!VAR "UserToChFromOsApp_ToOsApp" = "concat($UserToChFromOsApp_ToOsApp,$CurrentString)"!]
            [!ENDIF!]
          [!ENDIF!]
        [!ENDIF!] [!/*[!IF "$UserOsApplication != $ChannelOsApplication"!]*/!]
      [!ENDLOOP!] [!/*[!LOOP "../../ComMChannelPerPnc/*"!]*/!]
    [!ENDIF!] [!/*[!IF "$UserId = node:value(node:ref(.)/ComMUserIdentifier)"!]*/!]
  [!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMUserPerPnc/*"!]*/!]
  [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*/ComMUserPerChannel/*"!]
    [!IF "number(node:ref(ComMUserChannel)/ComMUserIdentifier) = $UserId"!]
      [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="../../ComMChannelPartitionRef"!]
        [!IF "$UserOsApplication != $ChannelOsApplication"!]
          [!VAR "CurrentString" = "''"!]
          [!VAR "CurrentString"= "concat($CurrentString,$UserOsApplication)"!]
          [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
          [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
          [!VAR "UserToChannelFound" = "'false'"!]
          [!FOR "Idx1" = "1" TO "count(text:split($UserToChFromOsApp_ToOsApp,' '))"!]
            [!IF "($CurrentString) = string(text:split($UserToChFromOsApp_ToOsApp,' ')[position() = $Idx1])"!]
              [!VAR "UserToChannelFound" = "'true'"!]
              [!BREAK!]
            [!ENDIF!]
          [!ENDFOR!] [!/* [!FOR "Idx1" = "1" TO "count(text:split($UserToChFromOsApp_ToOsApp,' '))"!] */!]        
          [!IF "$UserToChannelFound = 'false'"!]
            [!IF "count(text:split($UserToChFromOsApp_ToOsApp,' ')) = 0"!]
              [!VAR "UserToChFromOsApp_ToOsApp" = "$CurrentString"!]
            [!ELSE!]
             [!VAR "UserToChFromOsApp_ToOsApp" = "concat($UserToChFromOsApp_ToOsApp,' ')"!]
             [!VAR "UserToChFromOsApp_ToOsApp" = "concat($UserToChFromOsApp_ToOsApp,$CurrentString)"!]
            [!ENDIF!]
          [!ENDIF!]
        [!ENDIF!] [!/*[!IF "$UserOsApplication != $ChannelOsApplication"!]*/!]
    [!ENDIF!]
  [!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*/ComMUserPerChannel/*"!]*/!]
[!ENDLOOP!] 
[!ENDMACRO!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]*/!]

[!MACRO "GetUserToCh_FromOsAppToOsAppIndex","UserToChFromOsApp_ToOsApp","FromOsApplication","ToOsApplication"!]
[!VAR "CurrentString" = "$FromOsApplication"!]
[!VAR "CurrentString" = "concat($CurrentString,'->')"!]
[!VAR "CurrentString" = "concat($CurrentString, $ToOsApplication)"!]
[!VAR "FoundIndex"="'false'"!]
[!VAR "UserToChFctPtrIndex"="num:i(0)"!]
[!FOR "Idx" = "1" TO "count(text:split($UserToChFromOsApp_ToOsApp,' '))"!]
  [!IF "string(text:split($UserToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = ($CurrentString)"!]
    [!VAR "FoundIndex"="'true'"!]  
    [!BREAK!]
  [!ENDIF!]
  [!VAR "UserToChFctPtrIndex" = "$UserToChFctPtrIndex + 1"!]
[!ENDFOR!]
[!IF "$FoundIndex = 'false'"!]
  [!VAR "UserToChFctPtrIndex"= "num:i(255)"!]
[!ENDIF!]
[!ENDMACRO!]

[!MACRO "GetMasterPncToCh_FromOsAppToOsAppList"!]
[!VAR "MasterPncToChFromOsApp_ToOsApp" = "''"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]
  [!CALL "GetMasterPncOsApplication"!]
  [!IF "node:exists(as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*/EcuMComMPNCRef)"!]
    [!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]
      [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]
        [!IF "node:exists(EcuMComMPNCRef)"!]
          [!LOOP "node:ref(EcuMComMPNCRef)/ComMChannelPerPnc/*"!]
            [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(.)/ComMChannelPartitionRef"!]
            [!IF "$MasterPncOsApplication != $ChannelOsApplication"!]
              [!VAR "CurrentString" = "''"!]
              [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
              [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
              [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
              [!VAR "StringFound" = "'false'"!]
              [!FOR "Idx" = "1" TO "count(text:split($MasterPncToChFromOsApp_ToOsApp,' '))"!]
                [!IF "string(text:split($MasterPncToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
                  [!VAR "StringFound" = "'true'"!]
                [!ENDIF!]
              [!ENDFOR!]
              [!IF "$StringFound = 'false'"!]
                [!IF "count(text:split($MasterPncToChFromOsApp_ToOsApp,' ')) = 0"!]
                    [!VAR "MasterPncToChFromOsApp_ToOsApp" = "$CurrentString"!]
                [!ELSE!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, ' ')"!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp,'->')"!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, $ChannelOsApplication)"!]
                [!ENDIF!]
              [!ENDIF!]
            [!ENDIF!] [!/*[!IF "$MasterPncOsApplication != $ChannelOsApplication"!]*/!]
          [!ENDLOOP!]
        [!ENDIF!]
      [!ENDLOOP!]
    [!ELSE!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMSynchronousWakeUp = 'true'"!]*/!]
      [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!]
        [!IF "node:exists(EcuMComMPNCRef)"!]
          [!LOOP "node:ref(EcuMComMPNCRef)/ComMChannelPerPnc/*"!]
            [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(.)/ComMChannelPartitionRef"!]
            [!IF "$MasterPncOsApplication != $ChannelOsApplication"!]
              [!VAR "CurrentString" = "''"!]
              [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
              [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
              [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
              [!VAR "StringFound" = "'false'"!]
              [!FOR "Idx" = "1" TO "count(text:split($MasterPncToChFromOsApp_ToOsApp,' '))"!]
                [!IF "string(text:split($MasterPncToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
                  [!VAR "StringFound" = "'true'"!]
                [!ENDIF!]
              [!ENDFOR!]
              [!IF "$StringFound = 'false'"!]
                [!IF "count(text:split($MasterPncToChFromOsApp_ToOsApp,' ')) = 0"!]
                    [!VAR "MasterPncToChFromOsApp_ToOsApp" = "$CurrentString"!]
                [!ELSE!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, ' ')"!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp,'->')"!]
                  [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, $ChannelOsApplication)"!]
                [!ENDIF!]
              [!ENDIF!]
            [!ENDIF!] [!/*[!IF "$MasterPncOsApplication != $ChannelOsApplication"!]*/!]
            [!IF "node:exists(node:ref(.)/ComMManageReference/*[1])"!]
              [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="node:ref(node:ref(.)/ComMManageReference/*[1])/ComMChannelPartitionRef"!]
              [!IF "$MasterPncOsApplication != $ChannelOsApplication"!]
                [!VAR "CurrentString" = "''"!]
                [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
                [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
                [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
                [!VAR "StringFound" = "'false'"!]
                [!FOR "Idx" = "1" TO "count(text:split($MasterPncToChFromOsApp_ToOsApp,' '))"!]
                  [!IF "string(text:split($MasterPncToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
                    [!VAR "StringFound" = "'true'"!]
                  [!ENDIF!]
                [!ENDFOR!]
                [!IF "$StringFound = 'false'"!]
                  [!IF "count(text:split($MasterPncToChFromOsApp_ToOsApp,' ')) = 0"!]
                      [!VAR "MasterPncToChFromOsApp_ToOsApp" = "$CurrentString"!]
                  [!ELSE!]
                    [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, ' ')"!]
                    [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
                    [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp,'->')"!]
                    [!VAR "MasterPncToChFromOsApp_ToOsApp"= "concat($MasterPncToChFromOsApp_ToOsApp, $ChannelOsApplication)"!]
                  [!ENDIF!]
                [!ENDIF!]
              [!ENDIF!] [!/*[!IF "$MasterPncOsApplication != $ChannelOsApplication"!] */!]          
            [!ENDIF!] [!/*[!IF "node:exists(node:ref(.)/ComMManageReference/*[1])"!] */!]          
          [!ENDLOOP!] [!/* [!LOOP "node:ref(EcuMComMPNCRef)/ComMChannelPerPnc/*"!] */!]
        [!ENDIF!] [!/* [!IF "node:exists(EcuMComMPNCRef)"!] */!]
      [!ENDLOOP!] [!/* [!LOOP "as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*"!] */!]
    [!ENDIF!]
  [!ENDIF!] [!/*[!IF "node:exists(as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*/EcuMComMPNCRef)"!]*/!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]*/!]
[!ENDMACRO!]


[!MACRO "GetMasterPncToCh_FromOsAppToOsAppIndex","MasterPncToChFromOsApp_ToOsApp","FromOsApplication","ToOsApplication"!]
[!VAR "CurrentString" = "$FromOsApplication"!]
[!VAR "CurrentString" = "concat($CurrentString,'->')"!]
[!VAR "CurrentString" = "concat($CurrentString, $ToOsApplication)"!]
[!VAR "FoundIndex"="'false'"!]
[!VAR "MasterPncToChFctPtrIndex"="num:i(0)"!]
[!FOR "Idx" = "1" TO "count(text:split($MasterPncToChFromOsApp_ToOsApp,' '))"!]
  [!IF "string(text:split($MasterPncToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = ($CurrentString)"!]
    [!VAR "FoundIndex"="'true'"!]  
    [!BREAK!]
  [!ENDIF!]
  [!VAR "MasterPncToChFctPtrIndex" = "$MasterPncToChFctPtrIndex + 1"!]
[!ENDFOR!]
[!IF "$FoundIndex = 'false'"!]
  [!VAR "MasterPncToChFctPtrIndex"= "num:i(255)"!]
[!ENDIF!]
[!ENDMACRO!]

[!MACRO "GetChToUser_FromOsAppToOsAppList"!]
[!VAR "ChToUserFromOsApp_ToOsApp" = "''"!]
[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMRteUsage = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true')"!]
  [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]
    [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="ComMChannelPartitionRef"!]
    [!VAR "ChannelId" = "ComMChannelId"!]
    [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMChannelPerPnc/*"!]
      [!IF "node:value(node:ref(.)/ComMChannelId) = ($ChannelId)"!]
        [!LOOP "../../ComMUserPerPnc/*"!]
          [!CALL "GetUserOsApplication","UserEcuCPartitionRef"="node:ref(.)/ComMUserEcucPartitionRef"!]
          [!IF "$UserOsApplication != $ChannelOsApplication"!]
            [!VAR "CurrentString" = "''"!]
            [!VAR "CurrentString"= "concat($CurrentString,$ChannelOsApplication)"!]
            [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
            [!VAR "CurrentString"= "concat($CurrentString, $UserOsApplication)"!]
            [!VAR "ChannelToUserFound" = "'false'"!]
            [!FOR "Idx1" = "1" TO "count(text:split($ChToUserFromOsApp_ToOsApp,' '))"!]
              [!IF "($CurrentString) = string(text:split($ChToUserFromOsApp_ToOsApp,' ')[position() = $Idx1])"!]
                [!VAR "ChannelToUserFound" = "'true'"!]
                [!BREAK!]
              [!ENDIF!]
            [!ENDFOR!] [!/* [!FOR "Idx1" = "1" TO "count(text:split($ChToUserFromOsApp_ToOsApp,' '))"!] */!]        
            [!IF "$ChannelToUserFound = 'false'"!]
              [!IF "count(text:split($ChToUserFromOsApp_ToOsApp,' ')) = 0"!]
                [!VAR "ChToUserFromOsApp_ToOsApp" = "$CurrentString"!]
              [!ELSE!]
               [!VAR "ChToUserFromOsApp_ToOsApp" = "concat($ChToUserFromOsApp_ToOsApp,' ')"!]
               [!VAR "ChToUserFromOsApp_ToOsApp" = "concat($ChToUserFromOsApp_ToOsApp,$CurrentString)"!]
              [!ENDIF!]
            [!ENDIF!]
          [!ENDIF!]
        [!ENDLOOP!]
      [!ENDIF!]
    [!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMChannelPerPnc/*"!]*/!]
    [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*/ComMUserPerChannel/*"!]
      [!IF "(../../ComMChannelId) = ($ChannelId)"!]
        [!CALL "GetUserOsApplication","UserEcuCPartitionRef"="node:ref(ComMUserChannel)/ComMUserEcucPartitionRef"!]
        [!IF "$UserOsApplication != $ChannelOsApplication"!]
          [!VAR "CurrentString" = "''"!]
          [!VAR "CurrentString"= "concat($CurrentString,$ChannelOsApplication)"!]
          [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
          [!VAR "CurrentString"= "concat($CurrentString, $UserOsApplication)"!]
          [!VAR "ChannelToUserFound" = "'false'"!]
          [!FOR "Idx1" = "1" TO "count(text:split($ChToUserFromOsApp_ToOsApp,' '))"!]
            [!IF "($CurrentString) = string(text:split($ChToUserFromOsApp_ToOsApp,' ')[position() = $Idx1])"!]
              [!VAR "ChannelToUserFound" = "'true'"!]
              [!BREAK!]
            [!ENDIF!]
          [!ENDFOR!] [!/* [!FOR "Idx1" = "1" TO "count(text:split($ChToUserFromOsApp_ToOsApp,' '))"!] */!]        
          [!IF "$ChannelToUserFound = 'false'"!]
            [!IF "count(text:split($ChToUserFromOsApp_ToOsApp,' ')) = 0"!]
              [!VAR "ChToUserFromOsApp_ToOsApp" = "$CurrentString"!]
            [!ELSE!]
             [!VAR "ChToUserFromOsApp_ToOsApp" = "concat($ChToUserFromOsApp_ToOsApp,' ')"!]
             [!VAR "ChToUserFromOsApp_ToOsApp" = "concat($ChToUserFromOsApp_ToOsApp,$CurrentString)"!]
            [!ENDIF!]
          [!ENDIF!]
        [!ENDIF!]
      [!ENDIF!]
    [!ENDLOOP!] [!/* [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*/ComMUserPerChannel/*"!] */!]
  [!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*"!]*/!]
[!ENDIF!] [!/*[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMRteUsage = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true')"!]*/!]
[!ENDMACRO!]

[!MACRO "GetChToUser_FromOsAppToOsAppIndex","ChToUserFromOsApp_ToOsApp","FromOsApplication","ToOsApplication"!]
[!VAR "CurrentString" = "$FromOsApplication"!]
[!VAR "CurrentString" = "concat($CurrentString,'->')"!]
[!VAR "CurrentString" = "concat($CurrentString, $ToOsApplication)"!]
[!VAR "FoundIndex"="'false'"!]
[!VAR "ChToUserFctPtrIndex"="num:i(0)"!]
[!FOR "Idx" = "1" TO "count(text:split($ChToUserFromOsApp_ToOsApp,' '))"!]
  [!IF "string(text:split($ChToUserFromOsApp_ToOsApp,' ')[position() = $Idx]) = ($CurrentString)"!]
    [!VAR "FoundIndex"="'true'"!]  
    [!BREAK!]
  [!ENDIF!]
  [!VAR "ChToUserFctPtrIndex" = "$ChToUserFctPtrIndex + 1"!]
[!ENDFOR!]
[!IF "$FoundIndex = 'false'"!]
  [!VAR "ChToUserFctPtrIndex"= "num:i(255)"!]
[!ENDIF!]
[!ENDMACRO!]

[!MACRO "GetInhibitionToCh_FromOsAppToOsAppList"!]
[!VAR "InhibitionToChFromOsApp_ToOsApp" = "''"!]
[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true')"!]
  [!CALL "GetInhibitionOsApplication"!]
  [!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
    [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef" = "ComMChannelPartitionRef"!]
    [!VAR "ToOsApplication"= "$ChannelOsApplication"!]
    [!IF "$InhibitionOsApplication != $ToOsApplication"!]
      [!VAR "CurrentString" = "''"!]
      [!VAR "CurrentString"= "concat($CurrentString, $InhibitionOsApplication)"!]
      [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
      [!VAR "CurrentString"= "concat($CurrentString, $ToOsApplication)"!]
      [!VAR "StringFound" = "'false'"!]
      [!FOR "Idx" = "1" TO "count(text:split($InhibitionToChFromOsApp_ToOsApp,' '))"!]
        [!IF "string(text:split($InhibitionToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
          [!VAR "StringFound" = "'true'"!]
        [!ENDIF!]
      [!ENDFOR!] 
      [!IF "$StringFound = 'false'"!]
        [!IF "count(text:split($InhibitionToChFromOsApp_ToOsApp,' ')) = 0"!]
            [!VAR "InhibitionToChFromOsApp_ToOsApp" = "$CurrentString"!]
        [!ELSE!]
          [!VAR "InhibitionToChFromOsApp_ToOsApp"= "concat($InhibitionToChFromOsApp_ToOsApp, ' ')"!]
          [!VAR "InhibitionToChFromOsApp_ToOsApp"= "concat($InhibitionToChFromOsApp_ToOsApp, $InhibitionOsApplication)"!]
          [!VAR "InhibitionToChFromOsApp_ToOsApp"= "concat($InhibitionToChFromOsApp_ToOsApp,'->')"!]
          [!VAR "InhibitionToChFromOsApp_ToOsApp"= "concat($InhibitionToChFromOsApp_ToOsApp, $ToOsApplication)"!]
        [!ENDIF!]
      [!ENDIF!]
    [!ENDIF!] [!/*[!IF "$InhibitionOsApplication != $ToOsApplication"!]*/!]
  [!ENDLOOP!] [!/*[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]*/!]
[!ENDIF!] [!/* [!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true')"!] */!]
[!ENDMACRO!]

[!MACRO "GetInhibitionToCh_FromOsAppToOsAppIndex","InhibitionToChFromOsApp_ToOsApp","FromOsApplication","ToOsApplication"!]
[!VAR "CurrentString" = "$FromOsApplication"!]
[!VAR "CurrentString" = "concat($CurrentString,'->')"!]
[!VAR "CurrentString" = "concat($CurrentString, $ToOsApplication)"!]
[!VAR "FoundIndex"="'false'"!]
[!VAR "InhibitionToChFctPtrIndex"="num:i(0)"!]
[!FOR "Idx" = "1" TO "count(text:split($InhibitionToChFromOsApp_ToOsApp,' '))"!]
  [!IF "string(text:split($InhibitionToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = ($CurrentString)"!]
    [!VAR "FoundIndex"="'true'"!]  
    [!BREAK!]
  [!ENDIF!]
  [!VAR "InhibitionToChFctPtrIndex" = "$InhibitionToChFctPtrIndex + 1"!]
[!ENDFOR!]
[!IF "$FoundIndex = 'false'"!]
  [!VAR "InhibitionToChFctPtrIndex"= "num:i(255)"!]
[!ENDIF!]
[!ENDMACRO!]

[!MACRO "GetUserToMasterPnc_FromOsAppToOsAppList"!]
[!VAR "UserToMasterPncFromOsApp_ToOsApp" = "''"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]
  [!CALL "GetMasterPncOsApplication"!]
  [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]
    [!VAR "UserId" = "ComMUserIdentifier"!]
    [!IF "num:i(count(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*/ComMUserPerPnc/*[number(node:ref(.)/ComMUserIdentifier) = $UserId])) > 0"!]
      [!CALL "GetUserOsApplication","UserEcuCPartitionRef"="ComMUserEcucPartitionRef"!]
      [!IF "$UserOsApplication != $MasterPncOsApplication"!]
        [!VAR "CurrentString" = "''"!]
        [!VAR "CurrentString"= "concat($CurrentString, $UserOsApplication)"!]
        [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
        [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
        [!VAR "StringFound" = "'false'"!]
        [!FOR "Idx" = "1" TO "count(text:split($UserToMasterPncFromOsApp_ToOsApp,' '))"!]
          [!IF "string(text:split($UserToMasterPncFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
            [!VAR "StringFound" = "'true'"!]
          [!ENDIF!]
        [!ENDFOR!] 
        [!IF "$StringFound = 'false'"!]
          [!IF "count(text:split($UserToMasterPncFromOsApp_ToOsApp,' ')) = 0"!]
              [!VAR "UserToMasterPncFromOsApp_ToOsApp" = "$CurrentString"!]
          [!ELSE!]
            [!VAR "UserToMasterPncFromOsApp_ToOsApp"= "concat($UserToMasterPncFromOsApp_ToOsApp, ' ')"!]
            [!VAR "UserToMasterPncFromOsApp_ToOsApp"= "concat($UserToMasterPncFromOsApp_ToOsApp, $UserOsApplication)"!]
            [!VAR "UserToMasterPncFromOsApp_ToOsApp"= "concat($UserToMasterPncFromOsApp_ToOsApp,'->')"!]
            [!VAR "UserToMasterPncFromOsApp_ToOsApp"= "concat($UserToMasterPncFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
          [!ENDIF!]
        [!ENDIF!]
      [!ENDIF!]
    [!ENDIF!] [!/*[!IF "num:i(count(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*[1]/ComMUserPerPnc/*[number(node:ref(.)/ComMUserIdentifier) = $UserId]))"!]*/!]
  [!ENDLOOP!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]*/!]
[!ENDMACRO!]

[!MACRO "GetUserToMasterPnc_FromOsAppToOsAppIndex","UserToMasterPncFromOsApp_ToOsApp","FromOsApplication","ToOsApplication"!]
[!VAR "CurrentString" = "$FromOsApplication"!]
[!VAR "CurrentString" = "concat($CurrentString,'->')"!]
[!VAR "CurrentString" = "concat($CurrentString, $ToOsApplication)"!]
[!VAR "FoundIndex"="'false'"!]
[!VAR "UserToMasterPncFctPtrIndex"="num:i(0)"!]
[!FOR "Idx" = "1" TO "count(text:split($UserToMasterPncFromOsApp_ToOsApp,' '))"!]
  [!IF "string(text:split($UserToMasterPncFromOsApp_ToOsApp,' ')[position() = $Idx]) = ($CurrentString)"!]
    [!VAR "FoundIndex"="'true'"!]  
    [!BREAK!]
  [!ENDIF!]
  [!VAR "UserToMasterPncFctPtrIndex" = "$UserToMasterPncFctPtrIndex + 1"!]
[!ENDFOR!]
[!IF "$FoundIndex = 'false'"!]
  [!VAR "UserToMasterPncFctPtrIndex"= "num:i(255)"!]
[!ENDIF!]
[!ENDMACRO!]

[!MACRO "GetUserToInhibition_FromOsAppToOsAppList"!]
[!VAR "UserToInhibitionFromOsApp_ToOsApp" = "''"!]
[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true')"!]
  [!CALL "GetInhibitionOsApplication"!]
  [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]
    [!CALL "GetChannelsOfUser","UserName"="node:name(.)","FilterByOsApplication"="'false'","OsApplication"="''"!]
    [!CALL "GetUserOsApplication","UserEcuCPartitionRef"="ComMUserEcucPartitionRef"!]
    [!IF "$UserOsApplication != $InhibitionOsApplication"!]
      [!VAR "CurrentString" = "''"!]
      [!VAR "CurrentString"= "concat($CurrentString, $UserOsApplication)"!]
      [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
      [!VAR "CurrentString"= "concat($CurrentString, $InhibitionOsApplication)"!]
      [!VAR "StringFound" = "'false'"!]
      [!FOR "Idx" = "1" TO "count(text:split($UserToInhibitionFromOsApp_ToOsApp,' '))"!]
        [!IF "string(text:split($UserToInhibitionFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
          [!VAR "StringFound" = "'true'"!]
        [!ENDIF!]
      [!ENDFOR!] [!/*[!FOR "Idx" = "1" TO "count(text:split($UserToInhibitionFromOsApp_ToOsApp,' '))"!]*/!]
      [!IF "$StringFound = 'false'"!]
        [!IF "count(text:split($UserToInhibitionFromOsApp_ToOsApp,' ')) = 0"!]
            [!VAR "UserToInhibitionFromOsApp_ToOsApp" = "$CurrentString"!]
        [!ELSE!]
          [!VAR "UserToInhibitionFromOsApp_ToOsApp"= "concat($UserToInhibitionFromOsApp_ToOsApp, ' ')"!]
          [!VAR "UserToInhibitionFromOsApp_ToOsApp"= "concat($UserToInhibitionFromOsApp_ToOsApp, $UserOsApplication)"!]
          [!VAR "UserToInhibitionFromOsApp_ToOsApp"= "concat($UserToInhibitionFromOsApp_ToOsApp,'->')"!]
          [!VAR "UserToInhibitionFromOsApp_ToOsApp"= "concat($UserToInhibitionFromOsApp_ToOsApp, $InhibitionOsApplication)"!]
        [!ENDIF!]
      [!ENDIF!] [!/*[!IF "$StringFound = 'false'"!]*/!]
    [!ENDIF!] [!/*[!IF "$UserOsApplication != $InhibitionOsApplication"!]*/!]
  [!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMUser/*"!]*/!]
[!ENDIF!] [!/*[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true')"!]*/!]
[!ENDMACRO!]

[!MACRO "GetUserToInhibition_FromOsAppToOsAppIndex","UserToInhibitionFromOsApp_ToOsApp","FromOsApplication","ToOsApplication"!]
[!VAR "CurrentString" = "$FromOsApplication"!]
[!VAR "CurrentString" = "concat($CurrentString,'->')"!]
[!VAR "CurrentString" = "concat($CurrentString, $ToOsApplication)"!]
[!VAR "FoundIndex"="'false'"!]
[!VAR "UserToInhibitionFctPtrIndex"="num:i(0)"!]
[!FOR "Idx" = "1" TO "count(text:split($UserToInhibitionFromOsApp_ToOsApp,' '))"!]
  [!IF "string(text:split($UserToInhibitionFromOsApp_ToOsApp,' ')[position() = $Idx]) = ($CurrentString)"!]
    [!VAR "FoundIndex"="'true'"!]  
    [!BREAK!]
  [!ENDIF!]
  [!VAR "UserToInhibitionFctPtrIndex" = "$UserToInhibitionFctPtrIndex + 1"!]
[!ENDFOR!]
[!IF "$FoundIndex = 'false'"!]
  [!VAR "UserToInhibitionFctPtrIndex"= "num:i(255)"!]
[!ENDIF!]
[!ENDMACRO!]

[!MACRO "GetChToInhibition_FromOsAppToOsAppList"!]
[!VAR "ChToInhibitionFromOsApp_ToOsApp" = "''"!]
[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true')"!]
  [!CALL "GetInhibitionOsApplication"!]
  [!CALL "GetUsedChannelsOsApplications"!]
  [!FOR "Idx" = "1" TO "count(text:split($FoundChannelsOsApplications,' '))"!]
    [!VAR "FromOsApplication" = "string(text:split($FoundChannelsOsApplications,' ')[position() = $Idx])"!]
    [!VAR "ToOsApplication" = "$InhibitionOsApplication"!]
    [!IF "$FromOsApplication != $ToOsApplication"!]
      [!VAR "CurrentString" = "''"!]
      [!VAR "CurrentString"= "concat($CurrentString, $FromOsApplication)"!]
      [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
      [!VAR "CurrentString"= "concat($CurrentString, $ToOsApplication)"!]
      [!IF "count(text:split($ChToInhibitionFromOsApp_ToOsApp,' ')) = 0"!]
        [!VAR "ChToInhibitionFromOsApp_ToOsApp" = "$CurrentString"!]
      [!ELSE!]
        [!VAR "ChToInhibitionFromOsApp_ToOsApp" = "concat($ChToInhibitionFromOsApp_ToOsApp,' ')"!]
        [!VAR "ChToInhibitionFromOsApp_ToOsApp" = "concat($ChToInhibitionFromOsApp_ToOsApp,$CurrentString)"!]
      [!ENDIF!]
    [!ENDIF!] [!/*[!IF "$FromOsApplication != $ToOsApplication"!]*/!]
  [!ENDFOR!] [!/*[!FOR "Idx" = "1" TO "count(text:split($FoundChannelsOsApplications,' '))"!]*/!]
[!ENDIF!] [!/*[!IF "(as:modconf('ComM')[1]/ComMGeneral/ComMModeLimitationEnabled = 'true') or (as:modconf('ComM')[1]/ComMGeneral/ComMWakeupInhibitionEnabled = 'true')"!]*/!]
[!ENDMACRO!]

[!MACRO "GetChToInhibition_FromOsAppToOsAppIndex","ChToInhibitionFromOsApp_ToOsApp","FromOsApplication","ToOsApplication"!]
[!VAR "CurrentString" = "$FromOsApplication"!]
[!VAR "CurrentString" = "concat($CurrentString,'->')"!]
[!VAR "CurrentString" = "concat($CurrentString, $ToOsApplication)"!]
[!VAR "FoundIndex"="'false'"!]
[!VAR "ChToInhibitionFctPtrIndex"="num:i(0)"!]
[!FOR "Idx" = "1" TO "count(text:split($ChToInhibitionFromOsApp_ToOsApp,' '))"!]
  [!IF "string(text:split($ChToInhibitionFromOsApp_ToOsApp,' ')[position() = $Idx]) = ($CurrentString)"!]
    [!VAR "FoundIndex"="'true'"!]  
    [!BREAK!]
  [!ENDIF!]
  [!VAR "ChToInhibitionFctPtrIndex" = "$ChToInhibitionFctPtrIndex + 1"!]
[!ENDFOR!]
[!IF "$FoundIndex = 'false'"!]
  [!VAR "ChToInhibitionFctPtrIndex"= "num:i(255)"!]
[!ENDIF!]
[!ENDMACRO!]

[!MACRO "GetUsedEcuMChannelsOsApplications"!]
[!VAR "FoundEcuMChannelsOsApplications"="''"!]
[!IF "node:exists(as:modconf('EcuM')[1]/EcuMGeneral/EcuMCrossCoreComMWakeup) and (node:value(as:modconf('EcuM')[1]/EcuMGeneral/EcuMCrossCoreComMWakeup) = 'true')"!]
  [!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*/EcuMComMChannelRef)), 'ComMChannelId'))"!]
    [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef"="ComMChannelPartitionRef"!]
    [!VAR "OsApplicationAssignmentFound" = "'false'"!]
    [!FOR "Idx" = "1" TO "count(text:split($FoundEcuMChannelsOsApplications,' '))"!]
      [!IF "(string(text:split($FoundEcuMChannelsOsApplications,' ')[position() = $Idx]) = $ChannelOsApplication)"!]
        [!VAR "OsApplicationAssignmentFound" = "'true'"!]
      [!ENDIF!]
    [!ENDFOR!]
    [!IF "$OsApplicationAssignmentFound = 'false'"!]
      [!IF "count(text:split($FoundEcuMChannelsOsApplications,' ')) = 0"!]
        [!VAR "FoundEcuMChannelsOsApplications" = "$ChannelOsApplication"!]
      [!ELSE!]
       [!VAR "FoundEcuMChannelsOsApplications" = "concat($FoundEcuMChannelsOsApplications,' ')"!]
       [!VAR "FoundEcuMChannelsOsApplications" = "concat($FoundEcuMChannelsOsApplications,$ChannelOsApplication)"!]
      [!ENDIF!]
    [!ENDIF!]    
  [!ENDLOOP!] [!/*[!LOOP "util:distinct(node:order(util:distinct(node:refs(as:modconf('EcuM')[1]/EcuMConfiguration/*[1]/EcuMCommonConfiguration/EcuMWakeupSource/*/EcuMComMChannelRef)), 'ComMChannelId'))"!]*/!]
[!ENDIF!] [!/*[!IF "node:exists(as:modconf('EcuM')[1]/EcuMGeneral/EcuMCrossCoreComMWakeup) and (node:value(as:modconf('EcuM')[1]/EcuMGeneral/EcuMCrossCoreComMWakeup) = 'true')"!]*/!]
[!ENDMACRO!]

[!MACRO "GetUsedDcmChannelsOsApplications"!]
[!VAR "FoundDcmChannelsOsApplications"="''"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMDcmUsage = 'true'"!]
  [!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*/ComMChannel/*, 'ComMChannelId'))"!]
    [!IF "count(util:distinct(node:refs(as:modconf('Dcm')[1]/DcmConfigSet/*/DcmDsl/DcmDslProtocol/DcmDslProtocolRow/*/DcmDslConnection/*/DcmDslProtocolRx/*/DcmDslProtocolRxComMChannelRef))[node:exists(ComMChannelId) and (ComMChannelId = node:current()/ComMChannelId)]) != 0"!]
      [!CALL "GetChannelOsApplication","ChannelEcuCPartitionRef" = "ComMChannelPartitionRef"!]
      [!VAR "OsApplicationAssignmentFound" = "'false'"!]
      [!FOR "Idx" = "1" TO "count(text:split($FoundDcmChannelsOsApplications,' '))"!]
        [!IF "(string(text:split($FoundDcmChannelsOsApplications,' ')[position() = $Idx]) = $ChannelOsApplication)"!]
          [!VAR "OsApplicationAssignmentFound" = "'true'"!]
        [!ENDIF!]
      [!ENDFOR!]
      [!IF "$OsApplicationAssignmentFound = 'false'"!]
        [!IF "count(text:split($FoundDcmChannelsOsApplications,' ')) = 0"!]
          [!VAR "FoundDcmChannelsOsApplications" = "$ChannelOsApplication"!]
        [!ELSE!]
         [!VAR "FoundDcmChannelsOsApplications" = "concat($FoundDcmChannelsOsApplications,' ')"!]
         [!VAR "FoundDcmChannelsOsApplications" = "concat($FoundDcmChannelsOsApplications,$ChannelOsApplication)"!]
        [!ENDIF!]
      [!ENDIF!]
    [!ENDIF!]
  [!ENDLOOP!] [!/*[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*/ComMChannel/*, 'ComMChannelId'))"!]*/!]    
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMDcmUsage = 'true'"!]*/!]
[!ENDMACRO!]

[!MACRO "GetNumberOfGatewayTypePassiveChannels"!]
[!VAR "NrOfGatewayTypePassiveChannels" = "num:i(0)"!]
[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
  [!IF "node:exists(ComMPncGatewayType) and (ComMPncGatewayType = 'COMM_GATEWAY_TYPE_PASSIVE')"!]
    [!VAR "NrOfGatewayTypePassiveChannels" = "num:i($NrOfGatewayTypePassiveChannels + 1)"!]
  [!ENDIF!]
[!ENDLOOP!]  
[!ENDMACRO!]

[!MACRO "GetSynchShutDownChToMasterPnc_FromOsAppToOsAppList"!]
[!VAR "SynchShutDownChToMasterPncFromOsApp_ToOsApp" = "''"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]
  [!IF "node:exists(as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled) and (as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled = 'true')"!]
    [!CALL "GetActiveChMixedWithPassive"!]     
    [!IF "$ActiveChMixedWithPassive"!]
      [!CALL "GetMasterPncOsApplication"!]
      [!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
        [!IF "node:exists(ComMPncGatewayType) and (ComMPncGatewayType = 'COMM_GATEWAY_TYPE_PASSIVE')"!]
          [!CALL "GetChannelOsApplication", "ChannelEcuCPartitionRef" = "ComMChannelPartitionRef"!]
          [!IF "$ChannelOsApplication != $MasterPncOsApplication "!]
            [!VAR "CurrentString" = "''"!]
            [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
            [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
            [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
            [!VAR "StringFound" = "'false'"!]
            [!FOR "Idx" = "1" TO "count(text:split($SynchShutDownChToMasterPncFromOsApp_ToOsApp,' '))"!]
              [!IF "string(text:split($SynchShutDownChToMasterPncFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
                [!VAR "StringFound" = "'true'"!]
              [!ENDIF!]
            [!ENDFOR!]
            [!IF "$StringFound = 'false'"!]
              [!IF "count(text:split($SynchShutDownChToMasterPncFromOsApp_ToOsApp,' ')) = 0"!]
                  [!VAR "SynchShutDownChToMasterPncFromOsApp_ToOsApp" = "$CurrentString"!]
              [!ELSE!]
                [!VAR "SynchShutDownChToMasterPncFromOsApp_ToOsApp"= "concat($SynchShutDownChToMasterPncFromOsApp_ToOsApp, ' ')"!]
                [!VAR "SynchShutDownChToMasterPncFromOsApp_ToOsApp"= "concat($SynchShutDownChToMasterPncFromOsApp_ToOsApp, $ChannelOsApplication)"!]
                [!VAR "SynchShutDownChToMasterPncFromOsApp_ToOsApp"= "concat($SynchShutDownChToMasterPncFromOsApp_ToOsApp,'->')"!]
                [!VAR "SynchShutDownChToMasterPncFromOsApp_ToOsApp"= "concat($SynchShutDownChToMasterPncFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
              [!ENDIF!]
            [!ENDIF!]
          [!ENDIF!][!/*[!IF "$ChannelOsApplication != $MasterPncOsApplication "!]*/!]
        [!ENDIF!][!/*[!IF "node:exists(ComMPncGatewayType) and (ComMPncGatewayType = 'COMM_GATEWAY_TYPE_PASSIVE')"!]*/!]
      [!ENDLOOP!][!/*[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]*/!]
    [!ENDIF!][!/*[!IF "$ActiveChMixedWithPassive"!] */!]
  [!ENDIF!][!/*[!IF "node:exists(as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled) and (as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled = 'true')"!]*/!]
[!ENDIF!][!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]*/!]
[!ENDMACRO!]

[!MACRO "GetSynchShutDownChToMasterPnc_FromOsAppToOsAppIndex","SynchShutDownChToMasterPncFromOsApp_ToOsApp","FromOsApplication","ToOsApplication"!]
[!VAR "CurrentString" = "$FromOsApplication"!]
[!VAR "CurrentString" = "concat($CurrentString,'->')"!]
[!VAR "CurrentString" = "concat($CurrentString, $ToOsApplication)"!]
[!VAR "FoundIndex"="'false'"!]
[!VAR "SynchShutDownChToMasterPncFctPtrIndex"="num:i(0)"!]
[!FOR "Idx" = "1" TO "count(text:split($SynchShutDownChToMasterPncFromOsApp_ToOsApp,' '))"!]
  [!IF "string(text:split($SynchShutDownChToMasterPncFromOsApp_ToOsApp,' ')[position() = $Idx]) = ($CurrentString)"!]
    [!VAR "FoundIndex"="'true'"!]  
    [!BREAK!]
  [!ENDIF!]
  [!VAR "SynchShutDownChToMasterPncFctPtrIndex" = "$SynchShutDownChToMasterPncFctPtrIndex + 1"!]
[!ENDFOR!]
[!IF "$FoundIndex = 'false'"!]
  [!VAR "SynchShutDownChToMasterPncFctPtrIndex"= "num:i(255)"!]
[!ENDIF!]
[!ENDMACRO!]


[!MACRO "GetActiveChMixedWithPassive"!]
[!VAR "ActiveChMixedWithPassive" = "'false'"!]
[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
  [!VAR "ActiveChannelFound" = "'false'"!]
  [!VAR "PassiveChannelFound" = "'false'"!]
  [!IF "node:exists(ComMPncGatewayType) and (ComMPncGatewayType = 'COMM_GATEWAY_TYPE_ACTIVE')"!]
    [!VAR "ActiveChannelFound" = "'true'"!]
  [!ENDIF!]
  [!IF "node:exists(ComMPncGatewayType) and (ComMPncGatewayType = 'COMM_GATEWAY_TYPE_PASSIVE')"!]
    [!VAR "PassiveChannelFound" = "'true'"!]
  [!ENDIF!]
  [!IF "($ActiveChannelFound) and ($PassiveChannelFound)"!]
    [!VAR "ActiveChMixedWithPassive" = "'true'"!]
  [!ENDIF!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetSynchShutDownMasterPncToCh_FromOsAppToOsAppList"!]
[!VAR "SynchShutDownMasterPncToChFromOsApp_ToOsApp"= "''"!]
[!IF "node:exists(as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled) and (as:modconf('ComM')[1]/ComMGeneral/ComMSynchronizedPncShutdownEnabled = 'true')"!]
  [!CALL "GetMasterPncOsApplication"!]
  [!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMChannel/*, 'ComMChannelId'))"!]
    [!IF "node:exists(ComMPncGatewayType) and (ComMPncGatewayType = 'COMM_GATEWAY_TYPE_ACTIVE')"!]
      [!CALL "GetChannelOsApplication", "ChannelEcuCPartitionRef" = "ComMChannelPartitionRef"!]
      [!IF "$ChannelOsApplication != $MasterPncOsApplication "!]
        [!VAR "CurrentString" = "''"!]
        [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
        [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
        [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
        [!VAR "StringFound" = "'false'"!]
        [!FOR "Idx" = "1" TO "count(text:split($SynchShutDownMasterPncToChFromOsApp_ToOsApp,' '))"!]
          [!IF "string(text:split($SynchShutDownMasterPncToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
            [!VAR "StringFound" = "'true'"!]
          [!ENDIF!]
        [!ENDFOR!]
        [!IF "$StringFound = 'false'"!]
          [!IF "count(text:split($SynchShutDownMasterPncToChFromOsApp_ToOsApp,' ')) = 0"!]
              [!VAR "SynchShutDownMasterPncToChFromOsApp_ToOsApp" = "$CurrentString"!]
          [!ELSE!]
            [!VAR "SynchShutDownMasterPncToChFromOsApp_ToOsApp"= "concat($SynchShutDownMasterPncToChFromOsApp_ToOsApp, ' ')"!]
            [!VAR "SynchShutDownMasterPncToChFromOsApp_ToOsApp"= "concat($SynchShutDownMasterPncToChFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
            [!VAR "SynchShutDownMasterPncToChFromOsApp_ToOsApp"= "concat($SynchShutDownMasterPncToChFromOsApp_ToOsApp,'->')"!]
            [!VAR "SynchShutDownMasterPncToChFromOsApp_ToOsApp"= "concat($SynchShutDownMasterPncToChFromOsApp_ToOsApp, $ChannelOsApplication)"!]
          [!ENDIF!]
        [!ENDIF!]
      [!ENDIF!][!/*[!IF "$ChannelOsApplication != $MasterPncOsApplication "!]*/!]
    [!ENDIF!][!/* [!IF "node:exists(node:ref(.)/ComMPncGatewayType) and (node:ref(.)/ComMPncGatewayType = 'COMM_GATEWAY_TYPE_ACTIVE')"!] */!]
  [!ENDLOOP!]
[!ENDIF!]
[!ENDMACRO!]


[!MACRO "GetSynchShutDownMasterPncToCh_FromOsAppToOsAppIndex","SynchShutDownMasterPncToChFromOsApp_ToOsApp","FromOsApplication","ToOsApplication"!]
[!VAR "CurrentString" = "$FromOsApplication"!]
[!VAR "CurrentString" = "concat($CurrentString,'->')"!]
[!VAR "CurrentString" = "concat($CurrentString, $ToOsApplication)"!]
[!VAR "FoundIndex"="'false'"!]
[!VAR "SynchShutDownMasterPncToChFctPtrIndex"="num:i(0)"!]
[!FOR "Idx" = "1" TO "count(text:split($SynchShutDownMasterPncToChFromOsApp_ToOsApp,' '))"!]
  [!IF "string(text:split($SynchShutDownMasterPncToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = ($CurrentString)"!]
    [!VAR "FoundIndex"="'true'"!]  
    [!BREAK!]
  [!ENDIF!]
  [!VAR "SynchShutDownMasterPncToChFctPtrIndex" = "$SynchShutDownMasterPncToChFctPtrIndex + 1"!]
[!ENDFOR!]
[!IF "$FoundIndex = 'false'"!]
  [!VAR "SynchShutDownMasterPncToChFctPtrIndex"= "num:i(255)"!]
[!ENDIF!]
[!ENDMACRO!]

[!MACRO "GetEvaluateChannelMasterPncToCh_FromOsAppToOsAppList"!]
[!VAR "EvaluateChannelMasterPncToChFromOsApp_ToOsApp" = "''"!]
[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]
  [!CALL "GetMasterPncOsApplication"!]
  [!/*Part needed by pnc state machine to channel */!]
  [!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*"!]
    [!LOOP "ComMChannelPerPnc/*"!]
      [!VAR "ChannelName" = "node:name(node:ref(.))"!]
      [!CALL "GetChannelOsApplicationByName","ChannelName"="$ChannelName"!]
      [!IF "$MasterPncOsApplication != $ChannelOsApplication"!]
        [!VAR "CurrentString" = "''"!]
        [!VAR "CurrentString"= "concat($CurrentString, $MasterPncOsApplication)"!]
        [!VAR "CurrentString"= "concat($CurrentString,'->')"!]
        [!VAR "CurrentString"= "concat($CurrentString, $ChannelOsApplication)"!]
        [!VAR "StringFound" = "'false'"!]
        [!FOR "Idx" = "1" TO "count(text:split($EvaluateChannelMasterPncToChFromOsApp_ToOsApp,' '))"!]
          [!IF "string(text:split($EvaluateChannelMasterPncToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = $CurrentString"!]
            [!VAR "StringFound" = "'true'"!]
          [!ENDIF!]
        [!ENDFOR!]
        [!IF "$StringFound = 'false'"!]
          [!IF "count(text:split($EvaluateChannelMasterPncToChFromOsApp_ToOsApp,' ')) = 0"!]
              [!VAR "EvaluateChannelMasterPncToChFromOsApp_ToOsApp" = "$CurrentString"!]
          [!ELSE!]
            [!VAR "EvaluateChannelMasterPncToChFromOsApp_ToOsApp"= "concat($EvaluateChannelMasterPncToChFromOsApp_ToOsApp, ' ')"!]
            [!VAR "EvaluateChannelMasterPncToChFromOsApp_ToOsApp"= "concat($EvaluateChannelMasterPncToChFromOsApp_ToOsApp, $MasterPncOsApplication)"!]
            [!VAR "EvaluateChannelMasterPncToChFromOsApp_ToOsApp"= "concat($EvaluateChannelMasterPncToChFromOsApp_ToOsApp,'->')"!]
            [!VAR "EvaluateChannelMasterPncToChFromOsApp_ToOsApp"= "concat($EvaluateChannelMasterPncToChFromOsApp_ToOsApp, $ChannelOsApplication)"!]
          [!ENDIF!]
        [!ENDIF!]
      [!ENDIF!] [!/*[!IF "$MasterPncOsApplication != $ChannelOsApplication"!]*/!]
    [!ENDLOOP!] [!/*[!LOOP "ComMChannelPerPnc/*"!]*/!]
  [!ENDLOOP!] [!/*[!LOOP "as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*"!]*/!]
[!ENDIF!] [!/*[!IF "as:modconf('ComM')[1]/ComMGeneral/ComMPncSupport ='true'"!]*/!]
[!ENDMACRO!]

[!MACRO "GetEvaluateChannelMasterPncToCh_FromOsAppToOsAppIndex","EvaluateChannelMasterPncToChFromOsApp_ToOsApp","FromOsApplication","ToOsApplication"!]
[!VAR "CurrentString" = "$FromOsApplication"!]
[!VAR "CurrentString" = "concat($CurrentString,'->')"!]
[!VAR "CurrentString" = "concat($CurrentString, $ToOsApplication)"!]
[!VAR "FoundIndex"="'false'"!]
[!VAR "EvaluateChannelMasterPncToChFctPtrIndex"="num:i(0)"!]
[!FOR "Idx" = "1" TO "count(text:split($EvaluateChannelMasterPncToChFromOsApp_ToOsApp,' '))"!]
  [!IF "string(text:split($EvaluateChannelMasterPncToChFromOsApp_ToOsApp,' ')[position() = $Idx]) = ($CurrentString)"!]
    [!VAR "FoundIndex"="'true'"!]  
    [!BREAK!]
  [!ENDIF!]
  [!VAR "EvaluateChannelMasterPncToChFctPtrIndex" = "$EvaluateChannelMasterPncToChFctPtrIndex + 1"!]
[!ENDFOR!]
[!IF "$FoundIndex = 'false'"!]
  [!VAR "EvaluateChannelMasterPncToChFctPtrIndex"= "num:i(255)"!]
[!ENDIF!]
[!ENDMACRO!]

[!MACRO "GetMaxPncId"!]
[!VAR "MaxPnxcId" = "num:i(0)"!]
[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*,'ComMPncId'))"!]
  [!VAR "MaxPnxcId" = "ComMPncId"!]
[!ENDLOOP!]
[!ENDMACRO!]

[!MACRO "GetMinPncId"!]
[!VAR "MinPnxcId" = "num:i(0)"!]
[!LOOP "util:distinct(node:order(as:modconf('ComM')[1]/ComMConfigSet/*[1]/ComMPnc/*,'ComMPncId'))"!]
  [!VAR "MinPnxcId" = "ComMPncId"!]
  [!BREAK!]
[!ENDLOOP!]
[!ENDMACRO!]

[!ENDNOCODE!][!//
[!ENDIF!][!//