/**
 * \file
 *
 * \brief AUTOSAR Dlt
 *
 * This file contains the implementation of the AUTOSAR
 * module Dlt.
 *
 * \version 1.9.2
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2024 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/* MISRA-C:2012 Deviation List
 *
 * MISRAC2012-1) Deviated Rule: 8.3 (Required)
 *    "All declarations of an object or function shall use the same names and type qualifiers."
 *
 *    Reason:
 *    The function declaration is generated by the RTE with another parameter name.
 *
 *
 * MISRAC2012-2) Deviated Rule: 8.3 (Required)
 *    "All declarations of an object or function shall use the same names and type qualifiers."
 *
 *    Reason:
 *    The type for pointer to uint8 used by the RTE uses the name Dlt_Uint8Ptr and has the same
 *    type as the one used in the function definition.
 *
 **/
/*==[Includes]================================================================*/

#if (defined DLT_INTERNAL_USAGE)
#error DLT_INTERNAL_USAGE is already defined
#endif
#define DLT_INTERNAL_USAGE

#include <Dlt_BSW.h>

#if (DLT_INCLUDE_RTE == STD_ON)
#include <Rte_Dlt.h>
#elif (DLT_ENABLE_BSW_DISTRIBUTION == STD_ON)
#include <Rte_Type.h>
#endif

/*==[Macros]==================================================================*/

#if(defined DLT_UINT16_FROM_BYTE_ARRAY_MSB_IDX)
#error DLT_UINT16_FROM_BYTE_ARRAY_MSB_IDX already defined
#endif
/** \brief Create an uint16 value from the first two elements of an uint8 array. MSB first (big endian) */
#define DLT_UINT16_FROM_BYTE_ARRAY_MSB_IDX(ptr, idx) ( (uint16) ( ((uint16)((ptr)[idx]) << 8U) \
                                                       | ((uint16)((ptr)[idx + 1U])) ) )

#if(defined DLT_FILL_BYTE_ARRAY_FROM_BYTE_ARRAY)
#error DLT_FILL_BYTE_ARRAY_FROM_BYTE_ARRAY already defined
#endif
/** \brief Fill destination byte array with 4 bytes from the source array at a specific offset */
#define DLT_FILL_BYTE_ARRAY_FROM_BYTE_ARRAY(dest, offset, src) \
  do                                                           \
  {                                                            \
    (dest)[0U] = (src)[(offset)];                              \
    (dest)[1U] = (src)[(offset + 1U)];                         \
    (dest)[2U] = (src)[(offset + 2U)];                         \
    (dest)[3U] = (src)[(offset + 3U)];                         \
  } while(0)

/** \brief Create an uint32 value from the first four elements of the uint8 array. MSB first (big endian) */
#define DLT_UINT32_FROM_BYTE_ARRAY_MSB(arr, idx) ( (uint32) \
                                                ( ((uint32)((arr)[idx]) << 24U) \
                                                | ((uint32)((arr)[idx + 1U]) << 16U) \
                                                | ((uint32)((arr)[idx + 1U]) << 8U)  \
                                                | ((uint32)((arr)[idx + 1U]) ) ) )

/*==[Variables with internal linkage]=========================================*/

#if (DLT_CONTROL_SERVICE_PORT == STD_ON)
#define DLT_START_SEC_VAR_CLEARED_8
#include <Dlt_MemMap.h>

STATIC VAR(uint8, DLT_VAR) Dlt_GetLogInfoByteArray[DLT_GET_LOG_INFO_RETURN_SIZE];

#define DLT_STOP_SEC_VAR_CLEARED_8
#include <Dlt_MemMap.h>
#endif

/*==[Definition of functions with internal linkage]==========================*/

#if (DLT_INCLUDE_RTE == STD_ON)

#define Dlt_START_SEC_CODE
#include <Dlt_MemMap.h>

#if ((DLT_MESSAGE_SERVICE_PORT == STD_ON) || (DLT_DEFAULT_ASR_RETVAL < AUTOSAR_431))
/* Deviation MISRAC2012-2 */
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_SendLogMessage(
    Dlt_SessionIDType session_id,
    P2CONST(Dlt_MessageLogInfoType, AUTOMATIC, DLT_APPL_CONST) log_info,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) log_data,
    uint16 log_data_length)
{
#if (DLT_PROTOCOL_VERSION == 2U)
  return Dlt_ASR43_SendLogMessage(session_id, log_info, log_data, log_data_length, NULL_PTR);
#else
  return Dlt_ASR43_SendLogMessage(session_id, log_info, log_data, log_data_length);
#endif
}

/* Deviation MISRAC2012-2 */
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_SendTraceMessage(
    Dlt_SessionIDType session_id,
    P2CONST(Dlt_MessageTraceInfoType, AUTOMATIC, DLT_APPL_CONST) trace_info,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) trace_data,
    uint16 trace_data_length)
{
#if (DLT_PROTOCOL_VERSION == 2U)
  return Dlt_ASR43_SendTraceMessage(session_id, trace_info, trace_data, trace_data_length, NULL_PTR);
#else
  return Dlt_ASR43_SendTraceMessage(session_id, trace_info, trace_data, trace_data_length);
#endif
}

#if (DLT_DEFAULT_ASR_RETVAL >= AUTOSAR_431)
/* Deviation MISRAC2012-2 */
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_SendLogMessageWithAttributes(
    Dlt_SessionIDType session_id,
    P2CONST(Dlt_MessageLogInfoType, AUTOMATIC, DLT_APPL_CONST) log_info,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) log_data,
    uint16 log_data_length,
    P2CONST(Dlt_MessageAttributesType, AUTOMATIC, DLT_APPL_CONST) attributes)
{
  Dlt_ReturnType retVal = DLT_E_NOT_SUPPORTED;
#if (DLT_PROTOCOL_VERSION == 1U)
  /* !LINKSTO Dlt.SWS_Dlt_00787,1 */
  if (attributes == NULL_PTR)
#endif
  {
#if (DLT_PROTOCOL_VERSION == 1U)
    retVal = Dlt_ASR43_SendLogMessage(session_id, log_info, log_data, log_data_length);
#else
    retVal = Dlt_ASR43_SendLogMessage(session_id, log_info, log_data, log_data_length, attributes);
#endif
  }
  return retVal;
}

/* Deviation MISRAC2012-2 */
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_SendTraceMessageWithAttributes(
    Dlt_SessionIDType session_id,
    P2CONST(Dlt_MessageTraceInfoType, AUTOMATIC, DLT_APPL_CONST) trace_info,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) trace_data,
    uint16 trace_data_length,
    P2CONST(Dlt_MessageAttributesType, AUTOMATIC, DLT_APPL_CONST) attributes)
{
  Dlt_ReturnType retVal = DLT_E_NOT_SUPPORTED;
#if (DLT_PROTOCOL_VERSION == 1U)
  /* !LINKSTO Dlt.SWS_Dlt_00782,1 */
  if (attributes == NULL_PTR)
#endif
  {
#if (DLT_PROTOCOL_VERSION == 1U)
    retVal = Dlt_ASR43_SendTraceMessage(session_id, trace_info, trace_data, trace_data_length);
#else
    retVal = Dlt_ASR43_SendTraceMessage(session_id, trace_info, trace_data, trace_data_length, attributes);
#endif
  }
  return retVal;
}
#endif
#endif

#if (DLT_MESSAGE_SERVICE_PORT == STD_ON)
#if ((DLT_DEFAULT_ASR_RETVAL == AUTOSAR_431) || (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_20_11))
/* Deviation MISRAC2012-2 */
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_RegisterContext(
    Dlt_SessionIDType session_id,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) app_id,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) context_id,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) app_description,
    uint8 len_app_description,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) context_description,
    uint8 len_context_description)
#elif (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_22_11)
/* Deviation MISRAC2012-2 */
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_RegisterContext(
    Dlt_SessionIDType session_id,
    Dlt_ApplicationIDType app_id,
    Dlt_ContextIDType context_id,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) app_description,
    uint8 len_app_description,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) context_description,
    uint8 len_context_description)
#endif
{
  return Dlt_ASR43_RegisterContext(session_id,
                                   app_id,
                                   context_id,
                                   app_description,
                                   len_app_description,
                                   context_description,
                                   len_context_description);
}

#if ((DLT_DEFAULT_ASR_RETVAL == AUTOSAR_431) || (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_20_11))
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_UnregisterContext(
    Dlt_SessionIDType sessionId,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) appId,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) contextId)
#elif (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_22_11)
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_UnregisterContext(
    Dlt_SessionIDType sessionId,
    Dlt_ApplicationIDType appId,
    Dlt_ContextIDType contextId)
#endif
{
  return Dlt_ASR43_UnregisterContext(sessionId,
                                     appId,
                                     contextId);
}

#endif /* #if (DLT_MESSAGE_SERVICE_PORT == STD_ON) */

#if (DLT_DEFAULT_ASR_RETVAL < AUTOSAR_431)
/* Deviation MISRAC2012-2 */
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_RegisterContext(
    Dlt_SessionIDType session_id,
    Dlt_ApplicationIDType app_id,
    Dlt_ContextIDType context_id,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) app_description,
    uint8 len_app_description,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) context_description,
    uint8 len_context_description)
{
  return Dlt_ASR43_RegisterContext(session_id,
                                   app_id,
                                   context_id,
                                   app_description,
                                   len_app_description,
                                   context_description,
                                   len_context_description);
}

#endif

#if ( (DLT_DEFAULT_ASR_RETVAL < AUTOSAR_431) && (DLT_IMPLEMENT_NV_RAM_STORAGE == STD_ON) )
/* Deviation MISRAC2012-1 */
FUNC(Dlt_ReturnType, DLT_CODE) Dlt_Rte_StorePersistent(Dlt_SessionIDType session_id)
{
  return Dlt_StorePersistent(session_id);
}
#endif

#if (DLT_CONTROL_SERVICE_PORT == STD_ON)

#if ((DLT_DEFAULT_ASR_RETVAL == AUTOSAR_431) || (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_20_11))
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_SetLogChannelAssignment(
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) appId,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) contextId,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) logChannelName,
    Dlt_AssignmentOperationType addRemoveOp)
#elif (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_22_11)
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_SetLogChannelAssignment(
    Dlt_ApplicationIDType appId,
    Dlt_ContextIDType contextId,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) logChannelName,
    Dlt_AssignmentOperationType addRemoveOp)
#endif
{
  /* !LINKSTO Dlt.EB_Req_DltControlService_SetLogChannelAssignment_Error, 1 */
  Std_ReturnType retVal = DLT_E_ERROR;

  if (E_OK == Dlt_ASR43_SetLogChannelAssignment(appId, contextId, logChannelName, addRemoveOp))
  {
    retVal = DLT_E_OK;
  }

  return retVal;
}

FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_GetLogChannelNames(
    P2VAR(uint8, AUTOMATIC, DLT_APPL_DATA) numberOfLogChannels,
    P2VAR(uint8, AUTOMATIC, DLT_APPL_DATA) logChannelNames)
{
  /* !LINKSTO Dlt.EB_Req_DltControlService_GetLogChannelNames_Error, 1 */
  Std_ReturnType retVal = DLT_E_ERROR;

  if (E_OK == Dlt_ASR43_GetLogChannelNames(numberOfLogChannels, logChannelNames))
  {
    retVal = DLT_E_OK;
  }

  return retVal;
}

FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_SetLogChannelThreshold(
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) logChannelName,
    Dlt_MessageLogLevelType newThreshold,
    boolean newTraceStatus)
{
  /* !LINKSTO Dlt.EB_Req_DltControlService_SetLogChannelThreshold_Error, 1 */
  Std_ReturnType retVal = DLT_E_ERROR;

  if (E_OK == Dlt_ASR43_SetLogChannelThreshold(logChannelName, newThreshold, newTraceStatus))
  {
    retVal = DLT_E_OK;
  }

  return retVal;
}

FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_GetLogChannelThreshold(
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) logChannelName,
    P2VAR(Dlt_MessageLogLevelType, AUTOMATIC, DLT_APPL_DATA) logChannelThreshold,
    P2VAR(boolean, AUTOMATIC, DLT_APPL_DATA) traceStatus)
{
  /* !LINKSTO Dlt.EB_Req_DltControlService_GetLogChannelThreshold_Error, 1 */
  Std_ReturnType retVal = DLT_E_ERROR;

  if (E_OK == Dlt_ASR43_GetLogChannelThreshold(logChannelName, logChannelThreshold, traceStatus))
  {
    retVal = DLT_E_OK;
  }

  return retVal;
}

#if ((DLT_DEFAULT_ASR_RETVAL == AUTOSAR_431) || (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_20_11))
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_SetLogLevel(
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) appId,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) contextId,
    Dlt_MessageLogLevelType newLogLevel)
#elif (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_22_11)
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_SetLogLevel(
    Dlt_ApplicationIDType appId,
    Dlt_ContextIDType contextId,
    Dlt_MessageLogLevelType newLogLevel)
#endif
{
  /* !LINKSTO Dlt.EB_Req_DltControlService_SetLogLevel_Error, 1 */
  Std_ReturnType retVal = DLT_E_ERROR;

  if (E_OK == Dlt_ASR43_SetLogLevel(appId, contextId, newLogLevel))
  {
    retVal = DLT_E_OK;
  }

  return retVal;
}

#if ((DLT_DEFAULT_ASR_RETVAL == AUTOSAR_431) || (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_20_11))
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_SetTraceStatus(
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) appId,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) contextId,
    boolean newTraceStatus)
#elif (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_22_11)
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_SetTraceStatus(
    Dlt_ApplicationIDType appId,
    Dlt_ContextIDType contextId,
    boolean newTraceStatus)
#endif
{
  /* !LINKSTO Dlt.EB_Req_DltControlService_SetTraceStatus_Error, 1 */
  Std_ReturnType retVal = DLT_E_ERROR;

  if (E_OK == Dlt_ASR43_SetTraceStatus(appId, contextId, newTraceStatus))
  {
    retVal = DLT_E_OK;
  }

  return retVal;
}

#if ((DLT_DEFAULT_ASR_RETVAL == AUTOSAR_431) || (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_20_11))
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_GetTraceStatus(
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) appId,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) contextId,
    P2VAR(boolean, AUTOMATIC, DLT_APPL_DATA) traceStatus)
#elif (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_22_11)
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_GetTraceStatus(
    Dlt_ApplicationIDType appId,
    Dlt_ContextIDType contextId,
    P2VAR(boolean, AUTOMATIC, DLT_APPL_DATA) traceStatus)
#endif
{
  /* !LINKSTO Dlt.EB_Req_DltControlService_GetTraceStatus_Error, 1 */
  Std_ReturnType retVal = DLT_E_ERROR;

  if (E_OK == Dlt_ASR43_GetTraceStatus(appId, contextId, traceStatus))
  {
    retVal = DLT_E_OK;
  }

  return retVal;
}

#if ((DLT_DEFAULT_ASR_RETVAL == AUTOSAR_431) || (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_20_11))
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_GetLogInfo(
    uint8 options,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) appId,
    P2CONST(uint8, AUTOMATIC, DLT_APPL_CONST) contextId,
    P2VAR(uint8, AUTOMATIC, DLT_APPL_DATA) status,
    P2VAR(Dlt_LogInfoType, AUTOMATIC, DLT_APPL_DATA) logInfo)
#elif (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_22_11)
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_GetLogInfo(
    uint8 options,
    Dlt_ApplicationIDType appId,
    Dlt_ContextIDType contextId,
    P2VAR(uint8, AUTOMATIC, DLT_APPL_DATA) status,
    P2VAR(Dlt_LogInfoType, AUTOMATIC, DLT_APPL_DATA) logInfo)
#endif
{
  /* !LINKSTO Dlt.EB_Req_DltControlService_GetLogInfo_Error, 1 */
  Std_ReturnType retVal = DLT_E_ERROR;

  if (E_OK == Dlt_ASR43_GetLogInfo(options, appId, contextId, status, Dlt_GetLogInfoByteArray))
  {
    uint16 AppIdx, AppIdxEnd;
    uint16 AppIdMaxCount = 0U;
    uint16 CtxIdMaxCount = 0U;
    uint32 GlobalArrayIndex = 0U;

    logInfo->appIdCount = DLT_UINT16_FROM_BYTE_ARRAY_MSB_IDX(Dlt_GetLogInfoByteArray, GlobalArrayIndex);
    GlobalArrayIndex += 2U;

    if (logInfo->appIdCount > DLT_MAX_COUNT_APP_IDS_FOR_GET_LOG_INFO)
    {
      AppIdxEnd = DLT_MAX_COUNT_APP_IDS_FOR_GET_LOG_INFO;
    }
    else
    {
      AppIdxEnd = logInfo->appIdCount;
    }

    for (AppIdx = 0U; AppIdx < AppIdxEnd; AppIdx++)
    {
      uint16 CtxIdx, CtxIdxEnd;

#if ((DLT_DEFAULT_ASR_RETVAL == AUTOSAR_431) || (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_20_11))
      DLT_FILL_BYTE_ARRAY_FROM_BYTE_ARRAY(logInfo->appIdInfo[AppIdx].appId, GlobalArrayIndex, Dlt_GetLogInfoByteArray);

#else
      logInfo->appIdInfo[AppIdx].appId = DLT_UINT32_FROM_BYTE_ARRAY_MSB(Dlt_GetLogInfoByteArray, GlobalArrayIndex);
#endif
      GlobalArrayIndex += 4U;
      logInfo->appIdInfo[AppIdx].contextIdCount = DLT_UINT16_FROM_BYTE_ARRAY_MSB_IDX(Dlt_GetLogInfoByteArray, GlobalArrayIndex);
      GlobalArrayIndex += 2U;

      if (logInfo->appIdInfo[AppIdx].contextIdCount > DLT_MAX_COUNT_CTX_IDS_FOR_GET_LOG_INFO)
      {
        CtxIdxEnd = DLT_MAX_COUNT_CTX_IDS_FOR_GET_LOG_INFO;
      }
      else
      {
        CtxIdxEnd = logInfo->appIdInfo[AppIdx].contextIdCount;
      }

      for (CtxIdx = 0U; CtxIdx < CtxIdxEnd; CtxIdx++)
      {
#if ((DLT_DEFAULT_ASR_RETVAL == AUTOSAR_431) || (DLT_DEFAULT_ASR_RETVAL == AUTOSAR_20_11))
        DLT_FILL_BYTE_ARRAY_FROM_BYTE_ARRAY(logInfo->appIdInfo[AppIdx].contextInfoList[CtxIdx].contextId, GlobalArrayIndex, Dlt_GetLogInfoByteArray);
#else
        logInfo->appIdInfo[AppIdx].contextInfoList[CtxIdx].contextId = DLT_UINT32_FROM_BYTE_ARRAY_MSB(Dlt_GetLogInfoByteArray, GlobalArrayIndex);
#endif
        GlobalArrayIndex += 4U;
        logInfo->appIdInfo[AppIdx].contextInfoList[CtxIdx].logLevel = Dlt_GetLogInfoByteArray[GlobalArrayIndex];
        GlobalArrayIndex += 1U;
        logInfo->appIdInfo[AppIdx].contextInfoList[CtxIdx].traceStatus = Dlt_GetLogInfoByteArray[GlobalArrayIndex];
        GlobalArrayIndex += 1U;

        if (DLT_GETLOGINFO_OPTIONS_WITH_DESC == options)
        {
          logInfo->appIdInfo[AppIdx].contextInfoList[CtxIdx].contextDescLen = Dlt_GetLogInfoByteArray[GlobalArrayIndex];
          GlobalArrayIndex += 1U;
          TS_MemCpy(&logInfo->appIdInfo[AppIdx].contextInfoList[CtxIdx].contextDesc, &Dlt_GetLogInfoByteArray[GlobalArrayIndex], Dlt_GetLogInfoByteArray[GlobalArrayIndex - 1U]);
          GlobalArrayIndex += Dlt_GetLogInfoByteArray[GlobalArrayIndex - 1U];
        }

        CtxIdMaxCount += 1U;

        if (CtxIdMaxCount == DLT_MAX_COUNT_CTX_IDS_FOR_GET_LOG_INFO)
        {
          break;
        }
      }

      if (DLT_GETLOGINFO_OPTIONS_WITH_DESC == options)
      {
        logInfo->appIdInfo[AppIdx].appDescLen = Dlt_GetLogInfoByteArray[GlobalArrayIndex];
        GlobalArrayIndex += 1U;
        TS_MemCpy(&logInfo->appIdInfo[AppIdx].appDesc, &Dlt_GetLogInfoByteArray[GlobalArrayIndex], Dlt_GetLogInfoByteArray[GlobalArrayIndex - 1U]);
        GlobalArrayIndex += Dlt_GetLogInfoByteArray[GlobalArrayIndex - 1U];
      }

      AppIdMaxCount += 1U;

      if ((AppIdMaxCount == DLT_MAX_COUNT_APP_IDS_FOR_GET_LOG_INFO) || (CtxIdMaxCount == DLT_MAX_COUNT_CTX_IDS_FOR_GET_LOG_INFO))
      {
        break;
      }
    }

    retVal = DLT_E_OK;
    TS_MemBZero(&Dlt_GetLogInfoByteArray, DLT_GET_LOG_INFO_RETURN_SIZE);
  }

  return retVal;
}

FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_GetDefaultLogLevel(
    P2VAR(Dlt_MessageLogLevelType, AUTOMATIC, DLT_APPL_DATA) defaultLogLevel)
{
  /* !LINKSTO Dlt.EB_Req_DltControlService_GetDefaultLogLevel_Error, 1 */
  Std_ReturnType retVal = DLT_E_ERROR;

  if (E_OK == Dlt_ASR43_GetDefaultLogLevel(defaultLogLevel))
  {
    retVal = DLT_E_OK;
  }

  return retVal;
}

FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_SetDefaultLogLevel(Dlt_MessageLogLevelType newLogLevel)
{
  /* !LINKSTO Dlt.EB_Req_DltControlService_SetDefaultLogLevel_Error, 1 */
  Std_ReturnType retVal = DLT_E_ERROR;

  if (E_OK == Dlt_ASR43_SetDefaultLogLevel(newLogLevel))
  {
    retVal = DLT_E_OK;
  }

  return retVal;
}

FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_GetDefaultTraceStatus(
    P2VAR(boolean, AUTOMATIC, DLT_APPL_DATA) traceStatus)
{
  /* !LINKSTO Dlt.EB_Req_DltControlService_GetDefaultTraceStatus_Error, 1 */
  Std_ReturnType retVal = DLT_E_ERROR;

  if (E_OK == Dlt_ASR43_GetDefaultTraceStatus(traceStatus))
  {
    retVal = DLT_E_OK;
  }

  return retVal;
}

FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_SetDefaultTraceStatus(boolean newTraceStatus)
{
  /* !LINKSTO Dlt.EB_Req_DltControlService_SetDefaultTraceStatus_Error, 1 */
  Std_ReturnType retVal = DLT_E_ERROR;

  if (E_OK == Dlt_ASR43_SetDefaultTraceStatus(newTraceStatus))
  {
    retVal = DLT_E_OK;
  }

  return retVal;
}

FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_SetMessageFiltering(boolean status)
{
  /* !LINKSTO Dlt.EB_Req_DltControlService_SetMessageFiltering_Error, 1 */
  Std_ReturnType retVal = DLT_E_ERROR;

  if (E_OK == Dlt_ASR43_SetMessageFiltering(status))
  {
    retVal = DLT_E_OK;
  }

  return retVal;
}

FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_ResetToFactoryDefault(void)
{
  /* !LINKSTO Dlt.EB_Req_DltControlService_ResetToFactoryDefault_Error, 1 */
  Std_ReturnType retVal = DLT_E_ERROR;

  if (E_OK == Dlt_ASR43_ResetToFactoryDefault())
  {
    retVal = DLT_E_OK;
  }

  return retVal;
}

FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_StoreConfiguration(void)
{
  /* !LINKSTO Dlt.EB_Req_DltControlService_StoreConfiguration_Error, 1 */
  Std_ReturnType retVal = DLT_E_ERROR;

  if (E_OK == Dlt_ASR43_StoreConfiguration())
  {
    retVal = DLT_E_OK;
  }

  return retVal;
}
#endif /* #if (DLT_CONTROL_SERVICE_PORT == STD_ON) */

#if (DLT_DEFAULT_ASR_RETVAL >= AUTOSAR_431)
#if (DLT_POLL_BUFFER_SPACE_ON_RTE == STD_ON)
FUNC(Std_ReturnType, DLT_CODE) Dlt_Rte_GetRemainingBufferSize(P2CONST(uint8, AUTOMATIC, RTE_APPL_CONST) logChannelName, P2VAR(uint32, AUTOMATIC, DLT_APPL_DATA) BufferSize)
{
  Dlt_ReturnType retVal = E_NOT_OK;

  if (E_OK == Dlt_GetRemainingBufferSize(logChannelName, BufferSize))
  {
    retVal = DLT_E_OK;
  }

  return retVal;
}
#endif
#endif

#define Dlt_STOP_SEC_CODE
#include <Dlt_MemMap.h>

#endif /* #if (DLT_RTE_USAGE == STD_ON) */
